README.md

- Added Community section
- Added benchmark link
- Other wording or consistency fixes

update Community section and other fixes

---

helm/chaos-mesh/templates/collector-mysql.yaml
helm/chaos-mesh/templates/controller-manager-deployment.yaml
helm/chaos-mesh/templates/dashboard-deployment.yaml
pkg/collector/collector.go

Bump deployment api version to apps/v1

---

README.md

Add the twitter account

---

doc/network_chaos.md

Add docs for network-chaos.  Explain the purpose of each parameter in yaml.

add network_chaos.md

---

controllers/iochaos/fs/types.go

Signed-off-by: cwen0 <cwenyin0@gmail.com> 
fix https://github.com/pingcap/chaos-mesh/issues/105

iochaos: fix the issue that the process return anyway in the loop

---

doc/io_chaos.md

document: fix broken link

---

doc/network_chaos.md

document: update link

---

README.md

I'm not sure whether the format of the title is wrong.

fix a format type

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md

We did not have issue and pr template. In here add one

Add pr and issue template

---

Makefile

Add code coverage in codecov, close #129 
Tests 
- Unit test
Code changes
Side effects
- No
- No
```release-note
NONE
```

Add code cov

---

doc/io_chaos.md

Signed-off-by: cwen0 <cwenyin0@gmail.com>  
fix #136 
add some common errnos to iochaos document

doc: add some common errnos to iochaos document

---

README.md

Updated the Roadmap link
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Update Roadmap with link

---

ROADMAP.md

Added long-term roadmap
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Add long-term roadmap.

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/question.md

fix issue template
just fix issue template
Tests 
- No code
Code changes
- No code change
Side effects
- Change issue template
- None
- None

fix issue template

---

README.md
doc/faqs.md

Signed-off-by: mahjonp <junpeng.man@gmail.com>
Add a FAQs document, refer: #151 
```
None
```
Code changes
```
None
```
Side effects
```
None
```
```
None
```
```release-note
NONE
```

Docs: add FAQs

---

controllers/networkchaos/netem/types.go
controllers/networkchaos/partition/types.go

Signed-off-by: cwen0 <cwenyin0@gmail.com>   
fix # https://github.com/pingcap/chaos-mesh/issues/157
check the length of the containers statuses before using the states of cotnainer

check the length of the container statuses

---

examples/chaosfs-configmap/tiflash-configmap.yaml

Signed-off-by: cwen0 <cwenyin0@gmail.com> 
add ConfigMap example for TiFlash
Tests 

examples: add TiFlash ConfigMap 

---

README.md
pkg/collector/collector.go
pkg/utils/selector_test.go

* add badges in README.md
* format some code

add badges in README.md

---

doc/DEVELOP.md

Update the link to the [Develop a New Chaos] doc
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Update doc link 

---

pkg/chaosdaemon/util.go

Check length of containerID
Tests
- No code
Code changes
Side effects
-NO
- NO
```release-note
NONE
```

check length of containerID in chaos-daemon

---

go.mod
go.sum
pkg/webhook/config/config_test.go
pkg/webhook/config/setup_test.go

Add unit test (webhook/config/config_test.go)
Tests 
- Unit test
Code changes
Side effects
- NO
- NO
```release-note
NONE
```

Add unit test (webhook/config/config_test.go)

---

README.md
ROADMAP.md

ADD container kill in README
Tests 
- No code
Code changes
- NO
Side effects
- NO
```release-note
NONE
```

ADD container kill in README

---

doc/time_chaos.md

Fix the example time chaos.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Fix timechaos doc

---

doc/DEVELOP.md
pkg/time/time_darwin.go

1. README.md path
2. function signature on darwin
* #276 
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```

Trivial fix

---

helm/chaos-mesh/values.yaml

set `imagePullPolicy` to `Always `
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Fix imagePullPolicy in Chart file

---

examples/web-show/deploy.sh
install.sh

fix install chaos mesh failed caused by the access to github
* use local file 
* ensure pod status  
* fix sort invalid option
Tests 

use local file instead of downloading from github and ensure pod status 

---

pkg/time/time_linux.go

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

time-chaos: fix the length of fakeImage

---

README.md

Added link to development guide

Add contribute info

---

images/chaos-dashboard/package.json
images/chaos-dashboard/yarn.lock

Upgrade acorn to version 7.1.1 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Upgrade acorn to version 7.1.1

---

images/chaos-dashboard/package.json
images/chaos-dashboard/yarn.lock

update minimist to v1.2.2
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

update minimist to v1.2.2

---

Makefile

Tests 
Code changes
Side effects
```release-note
NONE
```

Update Makefile, add `groupimports` to `.PHONY`

---

Dockerfile

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Update controller-gen version v0.2.5

---

helm/chaos-mesh/templates/post-install-webhook-job.yaml

#367 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Add post-upgrade hook when helm upgrade

---

api/v1alpha1/iochaos_types.go
api/v1alpha1/kernelchaos_types.go
api/v1alpha1/networkchaos_types.go
api/v1alpha1/podchaos_types.go
api/v1alpha1/timechaos_types.go
config/crd/bases/pingcap.com_iochaos.yaml
config/crd/bases/pingcap.com_kernelchaos.yaml
config/crd/bases/pingcap.com_networkchaos.yaml
config/crd/bases/pingcap.com_podchaos.yaml
config/crd/bases/pingcap.com_timechaos.yaml
doc/pod_chaos.md
manifests/crd.yaml

add the usage of value in PodChaos to the document.

clarify the usage of the value field in PodChaos

---

pkg/chaosdaemon/util.go

Remove unused code 
Tests 
- Unit test
Code changes
Side effects
n/a
```release-note
NONE
```

remove unused code in util file

---

tools.go

Tests 
- None
Code changes
Side effects
- None
- None
```release-note
NONE
```

format tools.go with gofmt -s

---

pkg/webhook/config/config_test.go
pkg/webhook/inject/inject_test.go

fix gofmt issues on https://goreportcard.com/report/github.com/pingcap/chaos-mesh#ineffassign
Tests 
- Unit test
Code changes
Side effects
- NONE
- NONE
```release-note
NONE
```

format inject_test.go config_test.go with gofmt -s

---

.github/workflows/ci.yml
Makefile
hack/lib.sh
pkg/chaosdaemon/ipset_server_test.go

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

add CI workflows

---

Dockerfile

Remove unused `RUN mkdir /src`, `WORKDIR` will create folder if it doesn’t exist.
reference: https://docs.docker.com/engine/reference/builder/#workdir
>  If the WORKDIR doesn’t exist, it will be created even if it’s not used in any subsequent Dockerfile instruction.
Tests 
- Manual test
Code changes
Side effects

remove unused mkdir

---

test/e2e/chaos/basic.go

organize the e2e case 
```release-note
NONE
```

organize the e2e case 

---

doc/sidecar_configmap.md
examples/chaosfs-configmap/cockroachdb-configmap.yaml
examples/chaosfs-configmap/pd-configmap.yaml
examples/chaosfs-configmap/tiflash-configmap.yaml
examples/chaosfs-configmap/tikv-configmap.yaml
examples/etcd/etcd-configmap.yaml
helm/chaos-mesh/values.yaml

Use v0.8.0 Image tag 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

use v0.8.0 image tag

---

.github/workflows/ci.yml

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

update CI action

---

.github/workflows/ci.yml

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

cherry-pick: update CI action (#452)

---

doc/faqs.md
doc/io_chaos.md
doc/kernel_chaos.md
doc/pod_chaos.md
doc/run_chaos_mesh.md
doc/sidecar_configmap.md
doc/time_chaos.md

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Chore: docs update and cleanup

---

README.md

Updated formating for community meeting
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Update format for monthly meeting

---

controllers/common/types.go
controllers/iochaos/fs/types.go
controllers/kernelchaos/types.go
controllers/networkchaos/netem/types.go
controllers/networkchaos/partition/types.go
controllers/networkchaos/tbf/types.go
controllers/podchaos/containerkill/types.go
controllers/podchaos/podfailure/types.go
controllers/podchaos/podkill/types.go
controllers/podchaos/types.go
controllers/stresschaos/types.go
controllers/timechaos/types.go

Fixes #494
Cleanup several duplicate assignments and unused parameters.
Also, improve the slice and map allocations.

Cleanup redundant logic

---

test/image/e2e/Dockerfile

Remove mysql client in the e2e image

---

cmd/controller-manager/main.go
controllers/kernelchaos/types.go
controllers/kernelchaos_controller.go

Add event recorder to kernel controller

---

api/v1alpha1/common_types.go
api/v1alpha1/iochaos_types.go
api/v1alpha1/kernelchaos_types.go
api/v1alpha1/networkchaos_types.go
api/v1alpha1/podchaos_types.go
api/v1alpha1/stresschaos_types.go
api/v1alpha1/timechaos_types.go
config/crd/bases/pingcap.com_iochaos.yaml
config/crd/bases/pingcap.com_kernelchaos.yaml
config/crd/bases/pingcap.com_networkchaos.yaml
config/crd/bases/pingcap.com_podchaos.yaml
config/crd/bases/pingcap.com_stresschaos.yaml
config/crd/bases/pingcap.com_timechaos.yaml
controllers/common/types.go
doc/pause.md
manifests/crd.yaml
test/e2e/chaos/basic.go

Use annotation to pause chaos

---

go.mod
go.sum
hack/run-e2e.sh
pkg/chaosfs/pb/injure.pb.go
pkg/chaosfs/pb/injure.proto
pkg/chaosfs/server.go
pkg/chaosfs/server_test.go
test/config.go
test/e2e/chaos/basic.go
test/e2e/config/config.go
test/pkg/fixture/fixture.go

Fixes #503 
Added a new grpc method `Injected` to return whether chaosfs sidecar is injected or not.
Checklist:

Add injected grpc method

---

pkg/collector/collector.go
pkg/core/archive_experiment.go
pkg/store/experiment/experiment.go

Archive experiment to db

---

api/v1alpha1/iochaos_types.go
config/crd/bases/pingcap.com_iochaos.yaml
config/crd/bases/pingcap.com_kernelchaos.yaml
config/crd/bases/pingcap.com_networkchaos.yaml
config/crd/bases/pingcap.com_podchaos.yaml
config/crd/bases/pingcap.com_stresschaos.yaml
config/crd/bases/pingcap.com_timechaos.yaml
manifests/crd.yaml
pkg/apiserver/common/common.go
pkg/apiserver/experiment/experiment.go
pkg/chaosfs/pb/injure.pb.go
pkg/webhook/config/config.go
pkg/webhook/config/watcher/watcher.go
test/action.go

* remove next_start filed from iochaos 
* make format
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

remove next_start from iochaos

---

api/v1alpha1/common_types.go
api/v1alpha1/zz_generated.deepcopy.go
controllers/iochaos/fs/types.go
controllers/kernelchaos/types.go
controllers/networkchaos/netem/types.go
controllers/networkchaos/partition/types.go
controllers/networkchaos/tbf/types.go
controllers/podchaos/containerkill/types.go
controllers/podchaos/podfailure/types.go
controllers/podchaos/podkill/types.go
controllers/stresschaos/types.go
controllers/timechaos/types.go
pkg/collector/collector.go

Rename field to podRecords

---

controllers/kernelchaos/types.go
pkg/utils/chaosdaemon.go
pkg/utils/chaosdaemon_test.go

Fixes #535 
Return error when failed to get pid.

fix kernel chaos panic

---

Makefile

#362 
This PR decreases repeating build time by ~25%
Keep `pingcap/binary` running for incremental build in container. Inspired by [Tips & Tricks for Making Your Golang Container Builds 10x Faster](https://medium.com/windmill-engineering/tips-tricks-for-making-your-golang-container-builds-10x-faster-4cc618a43827)
Tests
```
$  time make image-binary
make image-binary  0.44s user 0.75s system 0% cpu 2:17.63 total
$ time TAILY_BUILD=1 make image-binary
TAILY_BUILD=1 make image-binary  0.50s user 0.76s system 1% cpu 1:34.11 total
```
Code changes
Side effects
None
```release-note
NONE
```

Use taily-build to speed up binary building

---

pkg/apiserver/common/common.go

```
{
"error": true,
"message": "error.api.internal_server_error: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:chaos-testing:chaos-controller-manager\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope",
"code": "error.api.internal_server_error",
"full_text": "error.api.internal_server_error: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:chaos-testing:chaos-controller-manager\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n at github.com/pingcap/chaos-mesh/pkg/apiserver/common.(*Service).getKinds()\n\t/src/pkg/apiserver/common/common.go:1 …
```

use v1alpha1.AllKinds instead of filtering crd

---

pkg/apiserver/event/event.go

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix swagger api router

---

helm/chaos-mesh/values.yaml

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Bump prometheus version to latest

---

pkg/apiserver/archive/experiment.go
pkg/apiserver/event/event.go
pkg/core/archive_experiment.go
pkg/store/experiment/experiment.go
pkg/store/experiment/experiment_test.go

Implement list archives

---

controllers/common/types.go
controllers/twophase/types.go
test/e2e/chaos/basic.go

Fixes #450 
Manual tested and it works.
will add E2E test case for this later.

Fix pause resume logic

---

pkg/collector/server.go

Log name should be `collector` instead of `controllers`.

Fix log name in chaos server

---

.github/workflows/ci.yml

fix groupimports in CI

---

pkg/apiserver/experiment/experiment.go

fix #579 
Add `nil` checker
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix get experiment detail

---

Dockerfile
Makefile
cmd/chaos-dashboard/main.go
hack/generate_swagger_spec.sh
hack/update_install_script.sh
helm/chaos-mesh/README.md
helm/chaos-mesh/templates/chaos-server-configmap.yaml
helm/chaos-mesh/templates/chaos-server-deployment.yaml
helm/chaos-mesh/templates/chaos-server-pvc.yaml
helm/chaos-mesh/values.yaml
images/chaos-dashboard/Dockerfile
install.sh
pkg/apiserver/server.go
pkg/core/event.go
tools.json

* rename chaos-server to chaos-dashboard 
* install chaos-dashboard with `install.sh` 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Rename chaos-server to chaos-dashboard

---

Dockerfile
pkg/apiserver/experiment/experiment.go

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix experiment detail api panic

---

docs/sidecar_configmap.md
docs/template_config.md

chore: fix typos in doc

---

ui/src/lib/formikhelpers.ts

fix: save container_name

---

docs/setup_env.md

Update setup_env.md
Replace legacy `make install-kustomize` and `make install-kubebuilder` to `make ensure-all`
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```

update make ensure-all in setup_env.md

---

helm/chaos-mesh/README.md
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
helm/chaos-mesh/templates/ingress.yaml
helm/chaos-mesh/values.yaml

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Add ingress for dashboard

---

api/v1alpha1/common_types.go
controllers/twophase/twophase_suite_test.go
controllers/twophase/types.go
pkg/apiserver/experiment/experiment.go
pkg/collector/collector.go

add waiting phase
add waiting phase
Tests
- No code
Code changes
Side effects
- NO
```release-note
NONE
```

[add] add waiting phase

---

test/e2e/chaos/basic.go

Fixes #591 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Add e2e test cases to test invalid sidecar config file

---

pkg/apiserver/common/common.go
pkg/apiserver/experiment/experiment.go

fix: swagger params missing

---

ADOPTERS.md

Update adopter list
Tests
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Add DataStax in adopter list

---

README.md

Move the adopters to README

---

website/docs/installation/get_started_on_kind.md
website/docs/installation/get_started_on_minikube.md
website/docs/installation/installation.md
website/sidebars.js

fix: relative paths' problem when first rendering

---

pkg/apiserver/experiment/experiment.go

Signed-off-by: “fewdan” <fuyihao@syvip.com>
add force delete
add force delete
Tests
- No code
Code changes
Side effects
- NO
- NO
```release-note
NONE
```

[add] add force delete

---

website/docs/development_guides/dev_hello_world.md
website/docs/development_guides/develop.md
website/docs/development_guides/setup_env.md
website/docs/installation/get_started_on_kind.md
website/docs/installation/get_started_on_minikube.md
website/docs/installation/installation.md
website/docs/user_guides/io_chaos.md
website/docs/user_guides/kernel_chaos.md
website/docs/user_guides/sidecar_configmap.md

fix document links

---

website/docs/user_guides/experiment_scope.md
website/docs/user_guides/kernel_chaos.md
website/docs/user_guides/network_chaos.md
website/docs/user_guides/pod_chaos.md
website/docs/user_guides/time_chaos.md
website/sidebars.js

Add a document to describe how to define experiment scope

---

website/docs/use_cases/multi_data_center.md
website/sidebars.js

Add a document showing how to simulate multi-data center scenarios

Add a document showing how to simulate multi-data center scenarios

---

pkg/apiserver/experiment/experiment.go

add target kind in experiments/detail
add target kind in experiments/detail
Tests
- No code
Code changes
Side effects
- NO
- NO
```release-note
NONE
```

[update]add target kind in experiments/detail

---

website/docs/use_cases/multi_data_centers.md

Refine the format of multi-data center document.
Tests
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Refine the format and punctuation

---

pkg/apiserver/experiment/experiment.go

update experiments/state
Unify the capitalization in “experiments/state” with the “experiments” interface.

[update] experiments/state

---

ui/src/api/experiments.ts
ui/src/api/experiments.type.ts
ui/src/components/EventsTable/index.tsx
ui/src/components/ExperimentPaper/index.tsx
ui/src/components/NewExperiment/index.tsx
ui/src/components/StatusPanel/index.tsx
ui/src/lib/d3/eventsChart.ts
ui/src/pages/Archives/index.tsx
ui/src/pages/ExperimentDetail/index.tsx
ui/src/pages/Experiments/index.tsx
ui/src/routes.tsx
ui/src/slices/experiments.ts

This PR synchronizes the recent API changes in the dashboard.

chore: dashboard patch of #720 and #713

---

README.md

Tests
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

update zoom link

---

test/cmd/e2e_helper/main.go
test/e2e/chaos/basic.go
test/pkg/fixture/fixture.go

Add e2e tests for network partition and network delay chaos
Code changes

add e2e test for network chaos

---

pkg/utils/selector.go

Signed-off-by: Gallardot <tttick@163.com>
Tests
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Bug fix for SelectPods

---

website/docs/installation/get_started_on_kind.md
website/docs/use_cases/multi_data_centers.md
website/docs/user_guides/run_chaos_experiment.md

fix: broken links in docs

---

website/blog/2020-01-15-chaos-mesh-your-chaos-engineering-solution.md
website/blog/2020-03-18-run-your-first-chaos-experiment.md
website/blog/2020-04-20-simulating-clock-skew-in-k8s-without-affecting-other-containers-on-node.md
website/blog/2020-07-28-chaos-mesh-join-cncf-sandbox-project.md
website/docusaurus.config.js

Website: add twitter preview image

---

install.sh
pkg/apiserver/archive/experiment.go

Update pkg/apiserver/archive/experiment.go
Change the return field to lowercase letters
Tests
- No code
Code changes

[update] update pkg/apiserver/archive/experiment.go

---

ui/src/api/archives.type.ts
ui/src/api/events.type.ts
ui/src/api/experiments.type.ts
ui/src/components/EventDetail/index.tsx
ui/src/components/EventsTable/index.tsx
ui/src/components/ExperimentEventsPreview/index.tsx
ui/src/components/ExperimentPaper/index.tsx
ui/src/components/NewExperiment/index.tsx
ui/src/lib/d3/chaosBarChart.ts
ui/src/lib/d3/eventsChart.ts
ui/src/lib/search.ts
ui/src/pages/Archives/index.tsx
ui/src/pages/ExperimentDetail/index.tsx
ui/src/pages/Experiments/index.tsx
ui/src/pages/Overview/index.tsx

Due to changes in the API fields, it's also needed to update the dashboard's type fields.
Related: #749.

fix: api compatibility of dashboard

---

ui/README.md
ui/src/api/archives.ts
ui/src/api/events.ts
ui/src/api/events.type.ts
ui/src/api/experiments.ts
ui/src/api/experiments.type.ts
ui/src/components/EventsTable/index.tsx
ui/src/components/ExperimentPaper/index.tsx
ui/src/components/JSONEditor/index.tsx
ui/src/components/NewExperiment/index.tsx
ui/src/lib/d3/insertCommonStyle.ts
ui/src/lib/search.ts
ui/src/pages/ExperimentDetail/index.tsx
ui/src/pages/Experiments/index.tsx
ui/src/store.ts

This PR adds these features:
- Now can update the experiment in detail page
- Create an experiment by archives
- Add `uuid:xxx` search filter in the events table

chore: update experiment and some other little features

---

website/docs/development_guides/develop.md
website/docs/installation/installation.md
website/docs/user_guides/sidecar_template.md

[update] update the website

---

website/docs/faqs.md

Update faq.md - Question

---

website/docs/development_guides/develop.md
website/docs/development_guides/setup_env.md
website/docs/installation/installation.md
website/docs/user_guides/pause.md

[update] webstie docs

---

.dockerignore
Dockerfile

Fix build with swagger and UI.
Remove swagger and UI related source codes from `.dockerignore`
Tests
```
SWAGGER=1 UI=1 make image
```

add ui and swagger files

---

helm/chaos-mesh/README.md
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
helm/chaos-mesh/templates/chaos-dashboard-pvc.yaml
helm/chaos-mesh/values.yaml

1. dashboard deployment do not use global timezone
2. dashboard pvc has syntax error
1. dashboard deployment use global timezone configuration if there is one
2. fix pvc syntax error
NA
Tests
- Unit test
NA
- E2E test
NA
- Manual test
deploy the new configuration manually.
- No code
Code changes
Side effects
No

add timezone for dashbaord and fix pvc in dashboard

---

ui/src/components/TopContainer/Sidebar.tsx

chore: add GitHub and Doc links in dashboard

---

pkg/store/event/event.go

[update] update api/events

---

website/docs/use_cases/multi_data_centers.md
website/docs/user_guides/kernel_chaos.md
website/docs/user_guides/network_chaos.md
website/docs/user_guides/pod_chaos.md
website/docs/user_guides/run_chaos_experiment.md
website/docs/user_guides/stress_chaos.md
website/docs/user_guides/time_chaos.md

doc: minor update

---

pkg/apiserver/experiment/experiment.go
pkg/apiserver/server.go
pkg/apivalidator/target_validator.go
pkg/core/archive_experiment.go

Check the fields when creating or updating an experiment
Check the fields when creating or updating an experiment
Tests
Side effects
```release-note
NONE
```

[update] Check the fields when creating or updating an experiment

---

ui/src/components/ExperimentPaper/index.tsx
ui/src/lib/d3/eventsChart.ts

- Fix timeline in detail page when events are empty
- Fix experiment status empty error in experiments page
Tests
Side effects
```release-note
NONE
```

fix: some bugs

---

helm/chaos-mesh/Chart.yaml

release chart 0.1.1

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh
manifests/chaosfs-sidecar.yaml

Tests
Side effects
```release-note
NONE
```

Release v0.9.0

---

install.sh

Tests
Side effects
```release-note
NONE
```

fix install scripts

---

controllers/stresschaos/types.go

Tests
Side effects
```release-note
NONE
```

fix stressChaos empty container name

---

CONTRIBUTING.md

Fixes misspelled word in Contributing guide
One letter added. From 'yam' to 'yaml'
Tests
Side effects
```release-note
NONE
```

Spelling fix

---

helm/chaos-mesh/values.yaml
install.sh
manifests/chaosfs-sidecar.yaml

Tests
Side effects
```release-note
NONE
```

update image tag

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh
manifests/chaosfs-sidecar.yaml

Tests
Side effects
```release-note
NONE
```

Release v0.9.1

---

ui/src/components/NewExperiment/index.tsx

As the title.
Tests
Side effects
```release-note
NONE
```

chore: add uuid suffix at load experiments

---

pkg/collector/server.go

add client.Reader in chaos-dashboard
Tests
Side effects
```release-note
NONE
```

[update] add client.Reader in chaos-dashboard

---

.github/workflows/ci.yml
Makefile

https://github.com/chaos-mesh/chaos-mesh/pull/896#pullrequestreview-486643308

Add command to check install script

---

website/docs/faqs.md

Reference from this issue #899  will be helpful to OpenShift users  
Tests
Side effects
```release-note
NONE
```

Update FAQ for Openshift scc

---

website/docusaurus.config.js
website/package.json
website/src/pages/interactiveTutorial.js
website/yarn.lock

As the title.
Tests
Side effects
```release-note
NONE
```

docs: add katacoda tutorial

---

.github/workflows/upload_latest_install_files.yml
.github/workflows/upload_release_install_files.yml

Tests
Side effects
```release-note
NONE
```

clean github action

---

controllers/httpchaos_controller.go
controllers/iochaos_controller.go
controllers/networkchaos_controller.go
controllers/podchaos_controller.go
controllers/stresschaos_controller.go
controllers/timechaos_controller.go
go.mod

https://github.com/chaos-mesh/chaos-mesh/issues/921
when delete chaos will get `not found` error log, users may be confused about it.
add an adjustment, print info log for `not found`
Tests
Side effects
```release-note
NONE
```

refine not found error log

---

ui/src/i18n/en.json
ui/src/i18n/zh.json
ui/src/pages/ExperimentDetail/index.tsx

As the title. An i18n problem and a data fetching problem.
Tests
Side effects
```release-note
NONE
```

fix: tiny errors in frontend

---

controllers/networkchaos/partition/types.go
controllers/networkchaos/podnetworkmanager/podnetworkmanager.go
controllers/networkchaos/trafficcontrol/types.go

This is a follow-up PR for #946 .
Enhanced the pod error check.
Tests
Side effects
No
```release-note
NONE
```

chore: follow up fix pause resume while pod not found or not running.

---

pkg/apivalidator/scope_validator.go
ui/src/components/ExperimentListItem/index.tsx

This PR fixes the labels' validation problem temporarily and should be recheck after version 1.0
Also, resolve a tiny bug about displaying the experiment state.
Tests
Side effects
```release-note
NONE
```

fix: validation problem in dashboard

---

cmd/controller-manager/main.go
controllers/common/types.go
controllers/common/types_test.go
controllers/iochaos_controller.go
controllers/kernelchaos_controller.go
controllers/networkchaos_controller.go
controllers/podchaos_controller.go
controllers/stresschaos_controller.go
controllers/timechaos_controller.go
helm/chaos-mesh/templates/controller-manager-deployment.yaml
helm/chaos-mesh/templates/controller-manager-rbac.yaml
helm/chaos-mesh/values.yaml
install.sh
pkg/config/controller.go
pkg/utils/selector.go
pkg/webhook/config/watcher/config.go
pkg/webhook/config/watcher/config_test.go
pkg/webhook/config/watcher/watcher.go
pkg/webhook/config/watcher/watcher_test.go

Manually cherry-pick for namespace scoped chaos.
There are conflicts because of http chaos controller.
Already cleaned up.

[add] Support namespace scoped chaos (#872)

---

pkg/collector/collector.go

https://github.com/chaos-mesh/chaos-mesh/issues/959
Before creating an event, check whether the event exists.
Tests
Side effects
```release-note
NONE
```

[update] fix multiple events have been recoreded

---

helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
NONE
```

Release v1.0

---

helm/chaos-mesh/Chart.yaml

Tests
Side effects
```release-note
NONE
```

Release chart-0.3.0

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
NONE
```

Use v1.0.0 tag

---

website/blog/2020-9-25-chaos-mesh-1.0-chaos-engineering-on-kubernetes-made-easier.md

As the title.
Tests
Side effects
```release-note
NONE
```

fix: link of release note

---

install.sh

fix issue https://github.com/chaos-mesh/chaos-mesh/issues/1003
add `}`
Tests
Side effects
```release-note
NONE
```

minor fix on install.sh

---

README.md

Deadlinks in the Readme
Updated getting started with KIND and MINIKUBE in Readme extracting oinks from the Docs.
Tests
Side effects
```release-note
NONE
```

Remove Deadlinks from Readme

---

website/docs/concepts/blast-radius.md
website/sidebars.js
website/versioned_docs/version-0.9.0/concepts/blast-radius.md
website/versioned_docs/version-0.9.0/concepts/chaos-engineering.md
website/versioned_docs/version-0.9.1/concepts/blast-radius.md
website/versioned_docs/version-0.9.1/concepts/chaos-engineering.md
website/versioned_docs/version-1.0.0/concepts/blast-radius.md
website/versioned_docs/version-1.0.0/concepts/chaos-engineering.md
website/versioned_sidebars/version-0.9.0-sidebars.json
website/versioned_sidebars/version-0.9.1-sidebars.json
website/versioned_sidebars/version-1.0.0-sidebars.json

#951 
Added to Concepts in the docs 
Tests
Side effects
```release-note
Yes, Concepts section added to the documentation  
```

adding to chaos mesh concept docs

---

install.sh

Signed-off-by: mikechengwei <842725815@qq.com>
fix install shell bug cause by pr  https://github.com/chaos-mesh/chaos-mesh/pull/954

fix install shell bug

---

Dockerfile

upgrade toda to v0.1.3 (#1032)

---

website/blog/2020-01-15-chaos-mesh-your-chaos-engineering-solution.md

Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
a complement to #1033 
My bad, missed one link
Reference: https://github.com/chaos-mesh/chaos-mesh/runs/1241812171
Tests
```release-note
NONE
```

bugfix: fix broken link

---

ui/src/components/NewExperiment/Stepper/Scope.tsx
ui/src/components/NewExperiment/Stepper/ScopePodsTable.tsx

As the title.
Tests
Side effects
```release-note
NONE
```

fix: key identity problem

---

hack/update_install_script.sh
install.sh

Tests
Side effects
```release-note
NONE
```

cherry-pick pr 954

---

ui/src/api/experiments.type.ts
ui/src/components/EventsTable/index.tsx
ui/src/components/NewExperiment/Stepper/Scope.tsx
ui/src/components/NewExperiment/Stepper/ScopePodsTable.tsx
ui/src/pages/ExperimentDetail/index.tsx

As the title. Also with little bug fixes.
Tests
Side effects
```release-note
NONE
```

chore: add error message in detail page

---

website/blog/2020-10-14-chaos-mesh-x-hacktoberfest.md

Signed-off-by: BellaXiang <42797797+BellaXiang@users.noreply.github.com>
Fix a typo in the hacktoberfest blog
Fix a typo in the hacktoberfest blog

Fix a typo in the hacktoberfest blog

---

README.md
website/blog/2020-9-18-chaos-mesh-action-integrate-chaos-engineering-into-your-ci.md

Signed-off-by: BellaXiang <42797797+BellaXiang@users.noreply.github.com>
Update the Readme document
- update the blog list
- adjust the structure
- add the "media coverage" part
- fix URL of "chaos-mesh-action: Integrate Chaos Engineering into Your CI" blog

update readme document

---

pkg/apiserver/experiment/experiment.go

Tests
Side effects
```release-note
NONE
```

fix: missing PartitionAction

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Update image tag and the default version

Release v1.0.1

---

website/docs/chaos_experiments/pod_chaos.md

Fixed #950 .
Revised the document.
Tests
Side effects
```release-note
NONE
```

doc: add container kill example in pod chaos experiments doc.

---

cmd/chaos-dashboard/main.go

Support MySQL, PostgreSQL, SQL Server as chaos-dashboard db store.
import these DB drivers.
Tests
Side effects
```release-note
NONE
```

import more db drivers

---

website/blog/2020-9-25-chaos-mesh-1.0-chaos-engineering-on-kubernetes-made-easier.md

Signed-off-by: colstuwjx <colstuwjx@gmail.com>
The latest N PRs all failed due to the markdown lint check, and this PR is going to fix this issue. See the error check capture below:
Correct the dead link.
Tests
Side effects
```release-note
NONE
```

fix: correct blog dead link to make lint happy.

---

controllers/twophase/twophase_suite_test.go

Signed-off-by: mikechengwei <842725815@qq.com>
#1079 
Remove second compare.
Tests

Fix twophase_suite_test.go applyAgain test

---

helm/chaos-mesh/README.md

Resolve CI errors.
Tests
Side effects
```release-note
NONE
```

fix: links

---

CONTRIBUTING.md

Signed-off-by: mikechengwei <842725815@qq.com>
Rename `./hack/local-up-chaos-mesh` to `./hack/local-up-chaos-mesh.sh`.
Sorry, this is caused by my carelessness
Tests

Fix CONTRIBUTING.md 

---

api/v1alpha1/zz_generated.chaosmesh.go
cmd/chaos-builder/impl.go

Fix #1095 
`action.IsValid()` is the correct way to check whether there is a field called `Action`
- Manual test
Test through creating and removing some `StressChaos` and `TimeChaos` on dashboard.

fix dashboard crash due to reflect.IsZero

---

pkg/apiserver/experiment/experiment.go

Accessing certain API interfaces may cause chaos-dashboard panic
Exit the function directly when an error is encountered 
Tests
Side effects
```release-note
NONE
```

fix error handling in chaos-dashboard to avoid panic

---

pkg/bpm/bpm.go
pkg/bpm/build_darwin.go
pkg/bpm/build_linux.go

#1124 
Tests
Side effects
```release-note
NONE
```

Fix bpm on mac

---

pkg/core/archive_experiment.go
ui/src/components/NewExperiment/Stepper/Scope.tsx
ui/src/lib/formikhelpers.ts
ui/src/slices/experiments.ts

Resolve #1108.
Tests
Side effects
```release-note
NONE
```

fix: form related bugs in dashboard

---

api/v1alpha1/zz_generated.chaosmesh.go
controllers/networkchaos/partition/types.go
controllers/networkchaos/trafficcontrol/types.go

https://github.com/chaos-mesh/chaos-mesh/issues/1114
If a pod appears in both source and target, it will appear repeatedly in pod records.
Make a distinction in the message.
Tests
Side effects
```release-note
NONE
```

[update] update network podRecords

---

controllers/networkchaos/partition/types.go
controllers/networkchaos/trafficcontrol/types.go

cherry pick pr 1117  to release1.0
Tests
Side effects
```release-note
NONE
```

cherry pick pr 1117  to release1.0

---

Dockerfile
cmd/chaos-daemon/main.go
images/chaos-daemon/Dockerfile
pkg/chaosdaemon/iochaos_server.go
pkg/fusedev/fusedev.go
test/e2e/chaos/basic.go

Cherry-pick #1104 to release-1.0

upgrade toda to 0.1.8 (#1104)

---

ui/src/i18n/zh.json
ui/src/pages/ArchiveReport/index.tsx

As the title.
Tests
Side effects
```release-note
NONE
```

chore: correct i18n

---

ui/src/i18n/en.json
ui/src/i18n/zh.json
ui/src/pages/ArchiveReport/index.tsx

Cherry-pick #1149.
Tests
Side effects
```release-note
NONE
```

chore: correct i18n (#1149)

---

api/v1alpha1/zz_generated.chaosmesh.go
cmd/chaos-builder/impl.go

Add missing `Status` field used in the dashboard.
Tests
Side effects
```release-note
NONE
```

fix: missing experiment status

---

ui/src/components/NewExperiment/Stepper/index.tsx
ui/src/components/NewExperiment/index.tsx

resolve #1153.
Tests
Side effects
```release-note
NONE
```

fix: allow resubmission

---

pkg/apiserver/experiment/experiment.go

Tests
Side effects
```release-note
NONE
```

fix swagger API

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
NONE
```

Release v1.0.2

---

test/e2e/chaos/basic.go

Signed-off-by: colstuwjx <colstuwjx@gmail.com>
Try to fix #1048 .
Add the mixed network partition and delay chaos inside test cases.
Tests
Side effects
```release-note
NONE
```

chore: separate common helpers and add mix delay/partition chaos test.

---

api/v1alpha1/common_validation.go

Fix bugs:
The value of a failed string parse is meaningless and skip it better.
Skip the validation of value from a failed parse.
Tests
Side effects
```release-note
NONE
```

api/v1alpha1: fix validate bugs.

---

pkg/apiserver/archive/archive.go
pkg/apiserver/experiment/experiment.go

The pr hasn't fixed bugs and just use more precise words.
Use more precise words instead of.
Tests
Side effects
```release-note
NONE
```

pkg/apiserver: use more precise words.

---

pkg/mapreader/reader.go

No bugs just to remove redundant code.
Remove redundant code.
Tests
Side effects
```release-note
NONE
```

pkg/mapreader: remove redundant code.

---

README.md

Update adopters with Qihoo 360.
Tests
Side effects
```release-note
NONE
```

add adopter

---

api/v1alpha1/podchaos_webhook.go

The statement `break` is redundant.
Remove it.
Tests
Side effects
```release-note
NONE
```

api/v1alpha1: remove reduntant code.

---

README.md

Signed-off-by: shinytang6 <1074461480@qq.com>
Tests
Side effects
```release-note
NONE
```

docs: update crd types

---

pkg/store/dbstore/store.go

The `driver` and `data sources` are more useful in some scenes.
Add detail info to log.
Tests
Side effects
```release-note
NONE
```

pkg/store/dbstore: add detail info to log.

---

pkg/store/event/event.go

Log names are not very consistent:
```
event/event.go
32:var log = ctrl.Log.WithName("eventStore")
experiment/experiment.go
28:var log = ctrl.Log.WithName("store/experiment")
dbstore/store.go
29:	log = ctrl.Log.WithName("store/dbstore")
```
Rename to `store/event`
Tests
Side effects
```release-note
NONE
```

pkg/store/event: Rename log name.

---

pkg/apiserver/experiment/experiment.go

Signed-off-by: Yue <g1enyy0ung@gmail.com>
Resolve #1209.
Tests
Side effects
```release-note
NONE
```

fix: init TargetScope to prevent panic

---

controllers/dnschaos/types.go

Signed-off-by: Gallardot tttick@163.com
Tests
Side effects
```release-note
NONE
```

Tiny fix for DNSChaos

---

README.md

Tests
Side effects
```release-note
NONE
```
@dcalvin @zhouqiang-cl

add: new blog link to README

---

api/v1alpha1/jvmchaos_webhook.go
pkg/router/route_table.go

* Add an error check 
* Remove the useless function
Tests
Side effects
```release-note
NONE
```

Handling errors returned from setup webhook 

---

ui/src/components/NewExperimentNext/data/basic.ts
ui/src/components/NewExperimentNext/form/Scheduler.tsx

Resolve #1225.
Tests
Side effects
```release-note
NONE
```

fix: can't set to immediate job

---

controllers/iochaos/podiochaosmanager/podiochaosmanager.go
controllers/iochaos/types.go
controllers/networkchaos/partition/types.go
controllers/networkchaos/podnetworkmanager/podnetworkmanager.go
controllers/networkchaos/trafficcontrol/types.go

Cherry pick #1215 to `release-1.0`

Fix networkchaos/iochaos recover slow (#1215)

---

helm/chaos-mesh/templates/_helpers.tpl
helm/chaos-mesh/templates/chaos-daemon-service.yaml
install.sh
pkg/utils/grpc.go

Cherry-pick #1206 to `release-1.0`
Actually, it's a reimplementation but not a `cherry-pick`. Please review carefully.

 Connect daemon through endpoint (#1206)

---

hack/update_install_script.sh
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
helm/chaos-mesh/values.yaml
install.sh
pkg/apiserver/common/common.go
pkg/clientpool/client.go
pkg/clientpool/client_test.go
pkg/collector/server.go
pkg/config/dashboard.go

dashboard support set config to disable token
add a config for disabling token, if it is true, will use the local client.
Tests
Side effects
```release-note
NONE
```

dashboard: support set config to disable token

---

README.md

add Apache APISIX as adopter.
We are using this project to test the stability of Apache APISIX.
Tests
Side effects
```release-note
NONE
```

doc: add Apache APISIX as adopter.

---

hack/local-up-chaos-mesh.sh

Tests
Side effects
```release-note
NONE
```

chore: enable UI and swagger API in local_up_chaos_mesh.sh

---

CONTRIBUTING.md

Removed hacktoberfest content since it's ended.
As the title said.
Tests
Side effects
```release-note
NONE
```

doc: remove hacktoberfest since it's ended.

---

examples/dns-chaos-example.yaml

add an example configuration file for DNS chaos
Tests
Side effects
```release-note
NONE
```

dns chaos: add example configuration file

---

cmd/chaos-daemon/main.go
cmd/chaosfs/main.go
cmd/controller-manager/main.go
pkg/chaosdaemon/dns_server.go
pkg/router/reconciler.go
pkg/router/route_table.go

Tests
Side effects
```release-note
NONE
```

fix typos and some optimizes

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

* Update image tag 
* Update default version
Tests
Side effects
```release-note
NONE
```

Release v1.0.3

---

helm/chaos-mesh/templates/controller-manager-rbac.yaml
helm/chaos-mesh/templates/prometheus-rbac.yaml
install.sh
manifests/tiller-rbac.yaml

cherry-pick #1294
Tests
Side effects
```release-note
NONE
```

fix invalid metadata name in helm chart files (#1294)

---

test/integration_test/network/run.sh

fix issue https://github.com/chaos-mesh/chaos-mesh/issues/1306
Tests
Side effects
```release-note
NONE
```

integration test: minor update on delay network

---

go.mod

Because many packages may require a higher version of go,  so upgrade go version to go1.15.
update go version to go1.15
Tests
Side effects
```release-note
NONE
```

update go version to go 1.15

---

ui/src/components/NewExperimentNext/Step2.tsx
ui/src/components/NewExperimentNext/data/basic.ts
ui/src/components/SearchTrigger/index.tsx
ui/src/lib/formikhelpers.ts

This PR aims to simplify ns setting up when creating experiments.
The namespace in the basic scope will move to advanced options. If it's not set, the dashboard will use the first namespace selectors to fill it.
Tests
Side effects
```release-note
NONE
```

chore: set ns automatically

---

Dockerfile

Fix #1329
upgrade today to 0.1.10:
- chown after mkdir and symlink  https://github.com/chaos-mesh/toda/pull/11
Tests
Side effects
```release-note
NONE
```

build: upgrade toda to 0.1.10

---

.github/workflows/integration_test.yml
.github/workflows/script_test.yml
pkg/apiserver/utils/auth.go
test/integration_test/dashboard_authority/busybox-manager.yaml
test/integration_test/dashboard_authority/busybox-viewer.yaml
test/integration_test/dashboard_authority/cluster-manager.yaml
test/integration_test/dashboard_authority/cluster-viewer.yaml
test/integration_test/dashboard_authority/run.sh
test/integration_test/run.sh
test/integration_test/utils/check_contains

1. minor update on archive API, only manager role can delete archive experiment
2. add integration test
Tests
Side effects
```release-note
NONE
```

dashboard: add integration test for authority

---

.dockerignore

The background build & publish CI process always failed. It will be fixed in this PR.

fix image build error

---

Makefile

chore: add recipe "config" into .PHONY

---

.github/workflows/stale.yml

Resolve #1339.
* Add more exempt issue labels: "type/enhancement,type/suggestion,type/bug"  
* Extend idle number of days before marking issue and pr
Tests
Side effects
```release-note
NONE
```

Github Action: add more exempt issue labels

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Update image tag and chart files version

Update image tag and chart file version

---

Makefile

Add tag to `pingcap/build-env`
Tests
Side effects
```release-note
NONE
```

fix makefile 

---

pkg/chaosctl/cmd/root.go

Signed-off-by: Yilin Chen <sticnarf@gmail.com>
Typo.
Fix componentes -> components
Tests
Side effects
```release-note
NONE
```

fix a typo in a comment

---

controllers/twophase/state_machine.go

Signed-off-by: Ruihang Xia <i@waynest.com>
Typo.
Fix excuting -> executing
Tests
Side effects
```release-note
NONE
```

fix a typo in log message

---

.github/ISSUE_TEMPLATE/bug-report.md

Add `chaos mesh version` on issues template

update issues template

---

pkg/store/dbstore/store.go

fix issue https://github.com/chaos-mesh/chaos-mesh/issues/1384
https://github.com/mattn/go-sqlite3/blob/master/README.md#faq
When you get a database is locked. Please use the following options.
Add to DSN: cache=shared
Example:
db, err := sql.Open("sqlite3", "file:locked.sqlite?cache=shared")
Second please set the database connections of the SQL package to 1.
db.SetMaxOpenConns(1)
here is an sample:
```golang
package main
import (
"fmt"
"sync"
"github.com/jinzhu/gorm"
_ "github.com/jinzhu/gorm/dialects/sqlite"
)
type Node struct {
Name   string `gorm:"primary_key" json:"name"`
Kind   string `json:"kind"`
Config string `json:"config"`
}
func main() {
// test config
refineConfig := false
threadNum := 10000
dns := "/tmp/sqlite_data"
if …
```

dashbaord: set config for sqlite to avoid error `database is locked`

---

images/chaos-daemon/Dockerfile

Fix a lot of bugs in the file system: 
* Fix bugs caused by TTLs
* Fix bugs after renaming a nonempty directory
It passes most parts of `pjdtests` now. The only left parts are: 1. paths longer than 4096 bytes. 2. `stat` after remove the file.

Upgrade toda to v0.1.17

---

GOVERNANCE.md

@dcalvin @zhouqiang-cl PTAL
Tests
Side effects
```release-note
NONE
```

Add Governance Doc for Chaos Mesh Project

---

ui/package.json
ui/src/components-mui/Paper/index.tsx
ui/src/components-mui/PaperContainer/index.tsx
ui/src/components-mui/PaperTop/index.tsx
ui/src/components/EventDetail/index.tsx
ui/src/components/EventsTable/index.tsx
ui/src/components/ExperimentListItem/index.tsx
ui/src/components/NewExperimentNext/LoadFrom/index.tsx
ui/src/components/NewExperimentNext/Step1.tsx
ui/src/components/TopContainer/Navbar.tsx
ui/src/components/YAML/index.tsx
ui/src/components/YAMLEditor/index.tsx
ui/src/pages/Dashboard/Predefined.tsx
ui/src/pages/Dashboard/Welcome.tsx
ui/src/pages/Dashboard/index.tsx
ui/src/pages/Events/index.tsx
ui/src/pages/ExperimentDetail/index.tsx
ui/src/pages/Settings/index.tsx
ui/yarn.lock

Tests
Side effects
```release-note
NONE
```

chore: cherry pick from #1427 (reduce bundle size)

---

ui/yarn.lock

Tests
Side effects
```release-note
NONE
```

fix: lockfile

---

ui/src/components/ExperimentListItem/index.tsx
ui/src/components/FormField/LabelField.tsx
ui/src/components/FormField/TextField.tsx
ui/src/components/NewExperimentNext/LoadFrom/index.tsx
ui/src/components/NewExperimentNext/Step2.tsx
ui/src/components/NewExperimentNext/form/Scheduler.tsx
ui/src/lib/formikhelpers.ts
ui/src/pages/ExperimentDetail/index.tsx
ui/src/pages/Experiments/index.tsx
ui/src/slices/experiments.ts

This PR mainly fixes some bugs as below:
- Correct the scheduler filling after loading an experiment from **LoadFrom** or external
- Reduce re-render in `newExperiments` page when creating
- Delay the data fetching after giving an operation on experiments (start, pause, etc.) to prevent the data from not updated
- Split problem (in function `helper1`) in parsing labels and annotations (shouldn't cut all semicolon, only cut the first)
Tests
Side effects
```release-note
NONE
```

fix: some bug fixes related to the UI

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
NONE
```

Use v1.1.1 as the default image tag and update chart file version

---

pkg/chaosctl/debug/iochaos/iochaos.go
pkg/chaosctl/debug/networkchaos/networkchaos.go
pkg/chaosctl/debug/stresschaos/stresschaos.go

Fix https://github.com/chaos-mesh/chaos-mesh/issues/1400
do not quit the loop while debugPod returns an error.
Tests
Side effects
```release-note
NONE
```

fix(chaosctl): best-effort-chaosctl

---

README.md

Tests
Side effects
```release-note
NONE
```

update Zoom link on readme

---

api/v1alpha1/stresschaos_types.go
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
install.sh
pkg/apiserver/experiment/experiment.go
pkg/config/dashboard.go
pkg/core/experiment.go
ui/src/api/common.type.ts
ui/src/components/NewExperimentNext/Step1.tsx
ui/src/components/NewExperimentNext/data/target.ts
ui/src/components/TopContainer/index.tsx
ui/src/lib/formikhelpers.ts
ui/src/slices/globalStatus.ts

Since the automatic cherry-pick failed, I manually uploaded the relevant changes.
Tests
Side effects
```release-note
NONE
```

chore: cherry-pick from #1461

---

pkg/chaosdaemon/ipset_server.go

doc: fix spell

---

ui/package.json
ui/src/components/FormField/LabelField.tsx
ui/src/lib/formikhelpers.ts
ui/src/pages/Dashboard/Predefined.tsx
ui/src/pages/Dashboard/index.tsx
ui/yarn.lock

- Fix some problems related to the interface
- Remove unused `tsd` dependency
Tests
Side effects
```release-note
NONE
```

fix(v1.1): some ui problems

---

ui/src/components/NewExperimentNext/data/target.ts
ui/src/components/NewExperimentNext/form/Stress.tsx

As the title.
Tests
Side effects
```release-note
NONE
```

chore: cherry pick 1523

---

Makefile
images/build-env/Dockerfile

add options to build on arm (#1542)

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
NONE
```

Use v1.1.2 as the default image tag and update chart file version

---

api/v1alpha1/httpchaos_webhook.go

fix typo, and other small change
Tests
Side effects
```release-note
NONE
```

fix typo on http chaos

---

controllers/awschaos/detachvolume/types.go
controllers/awschaos/ec2stop/types.go

fix-typo (aws-finalizer)

---

pkg/collector/collector.go

https://github.com/chaos-mesh/chaos-mesh/issues/1590
check the pointer is empty.
Tests
Side effects
```release-note
NONE
```

to avoid dashboard panic, judge that the pointer is nil

---

api/webhook/validate_auth.go
cmd/chaos-controller-manager/main.go
controllers/config/config.go
controllers/config/types_test.go
controllers/dnschaos/types.go
controllers/httpchaos/types.go
controllers/iochaos/types.go
controllers/jvmchaos/types.go
controllers/kernelchaos/types.go
controllers/networkchaos/partition/types.go
controllers/networkchaos/trafficcontrol/types.go
controllers/podchaos/containerkill/types.go
controllers/podchaos/podfailure/types.go
controllers/podchaos/podkill/types.go
controllers/stresschaos/types.go
controllers/timechaos/types.go
helm/chaos-mesh/README.md
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
helm/chaos-mesh/templates/controller-manager-deployment.yaml
helm/chaos-mesh/values.yaml
install.sh
pkg/apiserver/common/common.go
pkg/chaosctl/cmd/logs.go
pkg/chaosctl/common/common.go
pkg/config/controller.go
pkg/config/dashboard.go
pkg/selector/selector.go
pkg/selector/selector_test.go
pkg/webhook/inject/inject.go

only inject pod in namespace with annotation (#1550)

---

MAINTAINERS.md

Tests
Side effects
```release-note
NONE
```

fix: maintainers-list

---

ui/src/components/Token/index.tsx
ui/src/components/TopContainer/Auth.tsx
ui/src/i18n/en.json
ui/src/i18n/zh.json

This PR prevents duplicate tokens be submitted.
Tests
Side effects
```release-note
NONE
```

fix: token name duplicate

---

ui/src/components/Token/index.tsx
ui/src/components/TopContainer/Auth.tsx
ui/src/i18n/en.json
ui/src/i18n/zh.json

Cherry-pick from #1644.
Tests
Side effects
```release-note
NONE
```

fix: token name duplicate (#1644)

---

.github/workflows/upload_latest_files.yml
.github/workflows/upload_release_files.yml

Tests
Side effects
```release-note
NONE
```

fix github action

---

api/v1alpha1/stresschaos_types.go
api/v1alpha1/stresschaos_webhook.go
api/v1alpha1/stresschaos_webhook_test.go
config/crd/bases/chaos-mesh.org_stresschaos.yaml
go.mod
go.sum
helm/chaos-mesh/crds/chaos-mesh.org_stresschaos.yaml
manifests/crd.yaml
ui/src/components/NewExperiment/types.ts
ui/src/components/NewExperimentNext/data/target.ts
ui/src/components/NewExperimentNext/form/Stress.tsx

Revert "Use bigheap to inject heap stress (#776)" (#1581)

---

ui/src/lib/d3/eventsChart.ts
ui/src/lib/d3/insertCommonStyle.ts
ui/src/lib/utils.ts
ui/src/pages/Dashboard/Recent.tsx
ui/src/pages/Events/index.tsx
ui/src/pages/ExperimentDetail/index.tsx

Resolve #1671.
1. Use the `truncate` function to cut long text.
2. Fix events chart regeneration in different window sizes.
Tests
Side effects
```release-note
NONE
```

fix(ui): long text is not truncated

---

controllers/iochaos/types.go
hack/lib.sh
pkg/chaosctl/debug/networkchaos/networkchaos.go
pkg/core/workflow.go
pkg/router/reconciler.go
ui/src/pages/Settings/Other.tsx

Signed-off-by: Gallardot <tttick@163.com>
some tiny typo.
PS: why don't we do some spell checking using github action?
Tests
Side effects
```release-note
NONE
```

fix tiny typo

---

.github/workflows/ci.yml
.github/workflows/upload_latest_files.yml
.github/workflows/upload_release_files.yml

cherry-pick #1692 to release-1.1
---
Signed-off-by: hexilee <i@hexilee.me>
Follow the upgrade in #1688.
Tests
Side effects
```release-note
NONE
```

update go version to 1.15.11 in github workflows(#1692)

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

* Update image tag 
* Update helm chart version 
Tests
Side effects
```release-note
NONE
```

Set v1.1.3 tag

---

pkg/chaosctl/cmd/debug.go
pkg/chaosctl/cmd/logs.go
pkg/chaosctl/common/common.go
pkg/chaosctl/common/common_test.go
pkg/chaosctl/debug/iochaos/iochaos.go
pkg/chaosctl/debug/networkchaos/networkchaos.go
pkg/chaosctl/debug/stresschaos/stresschaos.go

It won't work properly now. Since it is originally designed upon `twophase`. This pr only intends to fix compile errors.

Fix chaosctl

---

helm/chaos-mesh/templates/dns-deployment.yaml
helm/chaos-mesh/values.yaml

Signed-off-by: hexilee <i@hexilee.me>
#1714
Add `podAnnotations` field for `dnsServer` part in helm configuration; inject `podAnnotation` into annotations part of `dns-deployment.yaml`.
Tests
Side effects
```release-note
NONE
```

support setting annotations for dnsServer deployment

---

pkg/chaosdaemon/container.go

Signed-off-by: AsterNighT <klxjt99@outlook.com>
Tests
Side effects
```release-note
NONE
```

Fix wrong log

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
NONE
```

Set default tag to v1.1.4

---

hack/update_install_script.sh
helm/chaos-mesh/values.yaml

Install Chaos Dashboard by default. 
Tests
Side effects
```release-note
NONE
```

Helm: install chaos-dashboard by default

---

pkg/apiserver/archive/archive.go
pkg/apiserver/archive/archive_test.go
pkg/apiserver/event/event_test.go
pkg/apiserver/experiment/experiment.go
pkg/core/event.go
pkg/core/experiment.go
pkg/store/event/event.go
pkg/store/experiment/experiment.go

Modify the interfaces for deleting experiments and archives.
cherry pick to release-1.2 
Support batch selection.
Tests
Side effects
```release-note
NONE
```

[update] batch delete archives and experiments

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
NONE
```

Set default tag to v1.2.0

---

controllers/config/types_test.go

This PR removes unused function [newPod](https://github.com/chaos-mesh/chaos-mesh/blob/f1c817e07ea339d41ded06055998c9a1e9f135e9/controllers/config/types_test.go#L114) and imported files!

Remove unused function newPod and imported files

---

pkg/chaosdaemon/crclients/client_test.go
pkg/chaosdaemon/crclients/docker/client_test.go

Signed-off-by: aSquare14 <atibhi.a@gmail.com>
Tests
Side effects
```release-note
NONE
```

(bugsbash) fix unchecked errors

---

Makefile
api/v1alpha1/go.sum

chore: appending go mod tidy check on other go.mod

---

api/v1alpha1/schedule_type_test.go
api/v1alpha1/schedule_types.go
cmd/chaos-controller-manager/main.go
cmd/chaos-controller-manager/provider/controller.go
config/crd/bases/chaos-mesh.org_schedules.yaml
controllers/desiredphase/desiredphase_test.go
controllers/desiredphase/suit_test.go
controllers/finalizers/controller.go
controllers/finalizers/finalizers_test.go
controllers/finalizers/suit_test.go
controllers/schedule/cron/utils.go
controllers/schedule/schedule_test.go
controllers/schedule/suit_test.go
controllers/utils/test/provider.go
helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
manifests/crd.yaml

Tests
Side effects
```release-note
NONE
```

Nirvana controller tests

---

api/v1alpha1/stresschaos_types.go

Fix size percentile issue in memory stress
If user specifies the size in %, it will not work. 
Tests
Side effects
```release-note
NONE
```

Fix size percentile issue in memory stress

---

api/v1alpha1/zz_generated.workflow.chaosmesh.go
cmd/chaos-builder/workflow.go
config/crd/bases/chaos-mesh.org_workflownodes.yaml
config/crd/bases/chaos-mesh.org_workflows.yaml
examples/workflow/workflow.yaml
helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
manifests/crd.yaml

This PR changes the field names in EmbedChaos from snake_case to camelCase like #1850.
It also updates the example of workflow.
Tests
Side effects
```release-note
NONE
```

chore: change items in embed chaos to camelCase

---

api/v1alpha1/schedule_types.go
api/v1alpha1/zz_generated.chaosmesh_test.go
api/v1alpha1/zz_generated.deepcopy.go
api/v1alpha1/zz_generated.workflow.chaosmesh.go
api/v1alpha1/zz_generated.workflow.chaosmesh_test.go
controllers/desiredphase/controller.go
controllers/schedule/active/controller.go
controllers/schedule/cron/controller.go
controllers/schedule/fx.go
controllers/schedule/pause/controller.go

Fix #1817
1. Skip the spawn when it was paused
2. Automatically pause the active objects

implement pause controller

---

pkg/workflow/controllers/workflow_entry_reconciler.go

The rest part of #1828, I forgot to update the startTime. :cry: 
When the entry controller applying, update the startTime of the workflow.
Tests
Side effects
```release-note
NONE
```

feat: update the start time of workflow

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
NONE
```

Update default image tag to v1.2.1

---

ui/src/components/TopContainer/Auth.tsx
ui/src/pages/Settings/TokensTable.tsx

Resolve #1851.
Tests
Side effects
```release-note
NONE
```

fix: can not delete last token

---

README.md

Tests
Side effects
```release-note
NONE
```

README: update the URL of build status

---

pkg/apiserver/event/event_test.go
pkg/apiserver/experiment/experiment.go
pkg/apiserver/schedule/schedule.go
pkg/collector/event_collector.go
pkg/core/event.go
pkg/store/event/event.go
pkg/store/event/event_test.go
test/integration_test/dashboard_authority/run.sh

update dashboard api and integration test
Tests
Side effects
```release-note
NONE
```

update dashboard api and integration test

---

.github/workflows/upload_latest_files.yml

Tests
Side effects
```release-note
NONE
```

Temporarily disable upload latest files

---

controllers/fx.go
examples/workflow/parallel.yaml
examples/workflow/serial.yaml

Controllers of the workflow are not set up.
And the example also has invalid fields.
This PR is only a quick fix, and I think it need refactor: moving all the workflow controllers into `/controllers` is much better.
Tests
Side effects
```release-note
NONE
```

fix: startup workflow bootstrap with fx

---

pkg/apiserver/archive/archive.go
pkg/apiserver/archive/archive_test.go

update archive fileds
1. change "start_time" to "created_at"
2. remove "action"
Tests
Side effects
```release-note
NONE
```

update archive fileds

---

Makefile

Signed-off-by: AsterNighT <klxjt99@outlook.com>
goimport would report an error for too many arguments.
Make it no longer format external packege.
Tests
Side effects
```release-note
NONE
```

Fix go import

---

.github/workflows/script_test.yml

Disable script test temporarily. This test will block merge action and we will reopen this test when dashboard is ready. 
Tests
Side effects
```release-note
NONE
```

.github: disable script test temporarily

---

pkg/apiserver/schedule/schedule.go
pkg/apiserver/utils/state.go

add schedule state
* Need to update Chaos Dashboard component.
Tests
Side effects
```release-note
```

[add] schedule state

---

pkg/core/experiment.go
pkg/core/schedule.go
pkg/store/schedule/schedule.go

update DeleteIncompleteSchedules
* None
Tests
Side effects
```release-note
```

[dashboard]: update DeleteIncompleteSchedules

---

api/v1alpha1/stresschaos_types.go
e2e-test/go.sum
go.mod
go.sum
pkg/apiserver/experiment/experiment.go
pkg/apiserver/schedule/schedule.go

update experiments and schedules
update experiments and schedules
* None
Tests
Side effects
```release-note
```

[dashboard] update experiments and schedules

---

tools/schedule-migration/migrate.sh

Signed-off-by: AsterNighT <klxjt99@outlook.com>
Tests
Side effects
```release-note
```

Fix: migration script

---

pkg/apiserver/schedule/schedule.go

Issue Number: close #1987  
fix schedule detail
* None
Tests
Side effects
```release-note
```

[dashboard] fix schedule detail

---

.github/workflows/upload_latest_files.yml

Uploading artifacts, these are required for `install.sh`

chore: enable uploading artifacts

---

.github/workflows/upload_latest_files.yml

upload `crd-v1beta1.yaml` to aws s3

upload crd-v1beta1.yaml

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

use default image version v2.0.0-beta.1

---

examples/workflow/custom-task.yaml
examples/workflow/parallel.yaml
examples/workflow/serial.yaml

As the definition of Workflow and WorkflowNode has been updated, the example should also be updated.
What's Changed: 
- change the related field name in example
* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: WIP.
* Need to cheery-pick to the release branch. Yes, release-2.0
Tests
Side effects
```release-note
```

update the example of workflow

---

controllers/podchaos/podfailure/types.go
helm/chaos-mesh/templates/controller-manager-rbac.yaml
install.sh

Manually apply #2020 on release-1.2

chore: use patch instead of update

---

ui/src/api/experiments.ts
ui/src/api/workflows.type.ts
ui/src/components/NewWorkflow/index.tsx
ui/src/components/Search/index.tsx
ui/src/i18n/en.json
ui/src/i18n/zh.json
ui/src/lib/formikhelpers.ts
ui/src/lib/search.ts
ui/src/pages/Archives/Single.tsx
ui/src/pages/Workflows/Single.tsx

The dashboard search in the navbar supports searching all objects now, including `Workflows`, `Schedules`, `Experiments`, and `Archives`.
And also fixes an error about creating a workflow.
* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: N
* Need to update Chaos Dashboard component, related issue: N
* Need to cheery-pick to the release branch: Y
Tests
Side effects
```release-note
```

chore: full search

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Update the version of the images

update image version

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
```

Update default image tag to v1.2.2

---

pkg/apiserver/experiment/experiment.go
pkg/apiserver/schedule/schedule.go
pkg/apiserver/workflow/workflow.go

Issue Number: close #2035  
sort experiments(schedules and workflows)
sort experiments(schedules and workflows)
Tests
Side effects
```release-note
```

[dashboard] sort experiments(schedules and workflows)

---

pkg/core/workflow.go
pkg/core/workflow_test.go

Issue Number: It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2051 .
- return `conditionalBranches` in the Dashboard API.
* Need to update Chaos Dashboard component, related issue: Yes, will be tracked in the issue #2051.
* Need to cheery-pick to the release branch. Yes.
Tests
Side effects
```release-note
```

feat: dashboard API of task node

---

.github/workflows/upload_latest_files.yml
.github/workflows/upload_release_files.yml
Makefile

Upload `schedule-migration` to `https://mirrors.chaos-mesh.org`
Downlow binary from https://mirrors.chaos-mesh.org/${tag}/schedule-migration
* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:  https://github.com/chaos-mesh/website-zh/pull/37
Tests
Side effects
```release-note
```

.github: upload schedule-migration binary

---

api/v1alpha1/workflownode_types.go
controllers/utils/recorder/workflow.go
pkg/workflow/controllers/bootstrap.go
pkg/workflow/controllers/chaos_node_reconciler.go
pkg/workflow/controllers/deadline_reconciler.go
pkg/workflow/controllers/parallel_node_reconciler.go
pkg/workflow/controllers/serial_node_reconciler.go
pkg/workflow/controllers/task_reconciler.go
pkg/workflow/controllers/workflow_entry_reconciler.go

Issue Number: close #2050
- new event entities 
- emitting events in the reconciler of workflow
* Need to cheery-pick to the release branch:  Yes, release-2.0
Tests
Side effects
```release-note
```

feat: enriching events for workflow

---

.github/workflows/upload_latest_files.yml

Add `tools/schedule-migration/**` path
Tests
Side effects
```release-note
```

.github: add 'tools/schedule-migration/**' path

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Update the image version to v2.0.0-beta.3

chore: bump the version to v2.0.0-beta.3

---

Makefile
api/v1alpha1/suite_test.go
cmd/chaos-controller-manager/provider/suit_test.go
controllers/desiredphase/suit_test.go
controllers/finalizers/suit_test.go
controllers/schedule/suit_test.go
pkg/webhook/inject/setup_test.go
pkg/workflow/controllers/suite_test.go

Issue Number: https://github.com/chaos-mesh/chaos-mesh/issues/1974
test: TEST_USE_EXISTING_CLUSTER replace USE_EXISTING_CLUSTER
Tests
Side effects
None

TEST_USE_EXISTING_CLUSTER replace USE_EXISTING_CLUSTER

---

pkg/core/workflow.go

Issue Number: close #2118
Tests
Side effects
```release-note
```

fix: missing created_at field

---

ui/src/components/ObjectConfiguration/Node.tsx
ui/src/components/ObjectConfiguration/index.tsx
ui/src/pages/Archives/Single.tsx
ui/src/pages/Experiments/Single.tsx
ui/src/pages/Schedules/Single.tsx

Issue Number: close #2119
Tests
Side effects
```release-note
```

chore: show status in single page

---

controllers/stresschaos/types.go

Without this PR, the former `stress-ng` instance created by controller but failed will never be collected and recoverd, because the next retry will overwrite the pid information.
Add a recover logic after failing to apply.

recover after failing to apply

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

chore: bump image version

---

.github/workflows/upload_release_files.yml
Makefile
tools/schedule-migration/main.go
tools/schedule-migration/migrate.sh
tools/schedule-migration/readme.md

Pack the migrate script and the binary. Fix some bugs on `migrate.sh` and the tool.
Tests
Side effects

Upload schedule migration

---

ADOPTERS.md

Tests
Side effects
```release-note
```

chores: update chaos mesh adopters

---

ADOPTERS.md

Issue Number: close #2155
Tests
Side effects
```release-note
```

fix(#2155): 404 not found

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

Tests
Side effects
```release-note
```

chore: bump image version to v1.2.3

---

CONTRIBUTING.md
helm/chaos-mesh/README.md

- several links are broken in `CONTRIBUTING.MD` and `helm/chaos-mesh/README.md`
- update the links 
- 
Tests
Side effects
```release-note
```

chore: fix urls

---

pkg/core/workflow.go
pkg/core/workflow_test.go

Signed-off-by: jackwener <jakevingoo@gmail.com>
Issue Number: #2054 
​	Eliminate redundant code
Just Eliminate the unneccessary code.
- None
Tests
Side effects
- No Side effects
```release-note
None
```

Workflow: Eliminate redundant code

---

controllers/action/delegate.go
controllers/chaosimpl/awschaos/detachvolume/impl.go
controllers/chaosimpl/awschaos/ec2restart/impl.go
controllers/chaosimpl/awschaos/ec2stop/impl.go
controllers/chaosimpl/dnschaos/types.go
controllers/chaosimpl/gcpchaos/diskloss/impl.go
controllers/chaosimpl/gcpchaos/nodereset/impl.go
controllers/chaosimpl/gcpchaos/nodestop/impl.go
controllers/chaosimpl/httpchaos/impl.go
controllers/chaosimpl/iochaos/impl.go
controllers/chaosimpl/jvmchaos/impl.go
controllers/chaosimpl/kernelchaos/types.go
controllers/chaosimpl/networkchaos/partition/impl.go
controllers/chaosimpl/networkchaos/trafficcontrol/impl.go
controllers/chaosimpl/podchaos/containerkill/impl.go
controllers/chaosimpl/podchaos/podfailure/impl.go
controllers/chaosimpl/podchaos/podkill/impl.go
controllers/chaosimpl/stresschaos/impl.go
controllers/chaosimpl/timechaos/impl.go

static interface check 
check static interface
#2163
Tests
Side effects
```release-note
```

Refactor static interface 'controllers-action-delegate'

---

ui/src/api/workflows.type.ts
ui/src/lib/cytoscape.ts

Issue Number: close #2054
- frontend related changes about #2221
- remove redundant nested `children`
Tests
Side effects
```release-note
```

chore: related changes on frontend about #2221

---

.github/pull_request_template.md

Problem Summary: 
What's Changed: update pull_request_template.md
* No
Tests
Side effects
```release-note
```

fix: add some annotation to pull request template

---

MAINTAINERS.md

Signed-off-by: Ben Ye <ben.ye@bytedance.com>
cc @cwen0

Update my company info

---

ui/src/components/NewExperimentNext/form/Scope.tsx

Issue Number: close #2329
Refer to #2218, this is a legacy name that needs to be modified.
Tests
Side effects
```release-note
```

fix: phase_selectors to phaseSelectors

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

chore: bump image version to 2.0.2

---

pkg/bpm/bpm.go

chaos-daemon: fix nil pointer dereference in chaos-daemon (#2289)

---

.github/workflows/upload_image.yml

It's a part of #2475;
- manually cherry-pick #2482 into branch `release-2.0`. 
- do not hardcode `chaos-mesh` in the CI file, use `github.repository_owner` instead.
- add `workflow_dispatch` for manually trigger
Tests
Manually tested at https://github.com/STRRL/chaos-mesh/actions/runs/1433092652
Side effects
```text
```

chore: short the project name for image(#2482)

---

.github/workflows/upload_image.yaml
Makefile
images/chaos-kernel/Dockerfile

it's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2483
- `chaos-kernel` is not built with GitHub Action 
- add `chaos-kernel` to upload_image.yaml
Tests
I manually tested it at https://github.com/STRRL/chaos-mesh/actions/runs/1434823231 and https://github.com/STRRL/chaos-mesh/actions/runs/1437744350
Side effects
```text
```

Building chaos kernel for release 2.0

---

.github/workflows/upload_image.yml
Makefile
images/chaos-kernel/Dockerfile

It's a part of #2483, close #2491
- try to build chaos-kernel with GitHub Action
Tests
I am trying to test it at https://github.com/STRRL/chaos-mesh/actions/runs/1434757478
Side effects
```text
```

Building chaos kernel on master

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

release ready for 2.0.4
- bump image and helm chart version to 2.0.4
Tests
Side effects
```text
```

chore: bump version to 2.0.4

---

ui/src/lib/formikhelpers.ts
ui/src/lib/utils.test.ts
ui/src/lib/utils.ts
ui/src/setupTests.ts

When creating a new object from the dashboard, it hasn't cleaned up all empty values before submitting to API.
Clean up before submitting.
Tests
Side effects
```text
```

fix: sanitize generated object

---

.github/workflows/upload_env_image.yml
Makefile
ci/pingcap_chaos_mesh_build_kind.groovy

Close https://github.com/chaos-mesh/chaos-mesh/issues/2475
- rename image:
- from `ghcr.io/chaos-mesh/chaos-mesh/build-env` to `ghcr.io/chaos-mesh/build-env`
- from `ghcr.io/chaos-mesh/chaos-mesh/dev-env` to `ghcr.io/chaos-mesh/dev-env`
- update GitHub Action Workflow, use `github.repository_owner` as the project name( I think it would be easier for contributors building their own build-env and dev-env with manually dispatched github actions than hard-coding PROJECT as `chaos-mesh`. )
Tests
Side effects
```text
```

chore: change project name for build-env and dev-env

---

pkg/dashboard/store/store.go

close https://github.com/chaos-mesh/chaos-mesh/issues/2463
Tests
Side effects
```text
```

dashboard: remove datasource in log

---

helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
install.sh

close https://github.com/chaos-mesh/chaos-mesh/issues/2516.
related issue: #1996 
- remove `rollme`, because it seems we do not need it.
Tests
Side effects
```text
```

chore: remove useless rollme

---

controllers/chaosimpl/dnschaos/types.go
controllers/chaosimpl/jvmchaos/impl.go
controllers/chaosimpl/podchaos/containerkill/impl.go
controllers/chaosimpl/stresschaos/impl.go
controllers/chaosimpl/timechaos/impl.go
controllers/chaosimpl/utils/record.go

> Problem Summary: Container had been misspelt as “Contianer”"
> What's Changed: Fix the typo and update all the references
Tests
Side effects
```text
```

Fix ContianerRecordDecoder typo

---

pkg/dashboard/apiserver/workflow/workflow.go

Close #2537
- did not resolve errors from kubernetes client properly
- use `utils.SetAPIMachinaryError` instead or `c.Error`
Tests
Side effects
```text
```

chore: resolve error with utils pakcage

---

ui/src/components/NewExperimentNext/LoadFrom/index.tsx
ui/src/components/ObjectConfiguration/Node.tsx
ui/src/lib/idb.ts

Tests
Side effects
```text
```

fix: can't load schedule archives (#2524)

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

chore: bump version to 2.0.5

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

chore: bump version to 1.2.4

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

bump version to 2.1.0

---

.github/workflows/codecov_unittest.yaml

ci: add rebuild dev-env and build-env in codecov test

---

ui/app/src/components/NewExperimentNext/data/types.ts

fix #2723 
field name changed from `dns-hostname` to `dns-domain-name`
https://github.com/chaos-mesh/chaos-mesh/blob/be7f0c7977457d94f9f2efc2f65ea6abecce46d8/api/v1alpha1/physical_machine_chaos_types.go#L320
Tests
Side effects
```text
```
```shell
```

Dashboard: fix wrong field name in PhysicalMachineChaos 

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

We're ready for releasing Chaos Mesh 2.1.2 :D

chore: bump version to 2.1.2

---

helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

We are ready for releasing Chaos Mesh v2.0.6

chore: bump version to 2.0.6

---

.github/.licenserc.yaml

`make boilerplate` takes soo much time (about 20 min) on my local machine, and I found it tries to walk through the `node_modules`.
update `.licenserc.yaml`, appending more entries to ignore
- `.cache`
- `ui/node_modules`
- `**/*.log`
Tests
Side effects
```text
```
```shell
```

license check ignore more files

---

pkg/apiserver/utils/state.go
ui/src/api/experiments.type.ts
ui/src/components-mui/StatusLabel/index.tsx
ui/src/i18n/en.json
ui/src/i18n/zh.json

cherry-pick: #2708 
Tests
Side effects
```text
```
```shell
```

feat: add deleting status (cherry-pick #2708)

---

.github/workflows/integration_test.yml
.github/workflows/upload_latest_files.yml
.github/workflows/upload_release_files.yml

It's a part of  https://github.com/chaos-mesh/chaos-mesh/issues/2783
Tests
Side effects
```text
```
```shell
```

chore: setup go 1.17 and python in github actions

---

CHANGELOG.md

It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2799;
Create `CHANGELOG.md` for release-2.1.
Tests
Side effects
```text
```
```shell
```

chore: create CHANGELOG.md for release-2.1

---

CHANGELOG.md

It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2799
Create `CHANGELOG.md` for release-2.0
Tests
Side effects
```text
```
```shell
```

chore: add changelog for release-2.0

---

examples/nginx/http-patch-response.yaml
examples/nginx/nginx.yaml

Add example YAML for Nginx and HTTPChaos, for demo
Tests
Side effects
```text
```
```shell
```

HTTPChaos: add example for nginx

---

api/v1alpha1/gcpchaos_types.go
config/crd/bases/chaos-mesh.org_gcpchaos.yaml
config/crd/bases/chaos-mesh.org_schedules.yaml
config/crd/bases/chaos-mesh.org_workflownodes.yaml
config/crd/bases/chaos-mesh.org_workflows.yaml
helm/chaos-mesh/crds/chaos-mesh.org_gcpchaos.yaml
helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
manifests/crd-v1beta1.yaml
manifests/crd.yaml

Tests
Side effects
```text
```
```shell
```

docs: fix the description of GCPChaos (#2791)

---

CHANGELOG.md

This PR would append a for #2753.

chore: append changelog for #2753, cherry-picked from #2708

---

CHANGELOG.md

- appending missing changelogs
Tests
Side effects
```text
```
```shell
```

appending missing changelogs for branch release-2.1

---

CHANGELOG.md

- update CHANGELOG.md
Tests
Side effects
```release-note
```

append missing changelogs for branch release-2.0

---

Makefile

close https://github.com/chaos-mesh/chaos-mesh/issues/2829
remove duplicated recipes, rearrange the dependencies.
No need to cherry-pick to any branch, I would resolve it manally.
Tests
Side effects
```text
```
```shell
```

chore: remove duplicated chaos-daemon recipe

---

CHANGELOG.md
helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

- Bump version to 2.1.3
- Update changelog

ready for 2.1.3

---

CHANGELOG.md

Not a problem.
- update changelog for release v2.0.7 and v2.1.3
Tests
Side effects
```text
```
```shell
```

chore: update changelog for released version 2.1.3 and 2.0.7

---

ui/app/src/i18n/zh.json

close #2835
- change the i18n file
Tests
Side effects
```text
```
```shell
```

chore: update zh-cn i18n for serial

---

install.sh

This PR fixes some bugs introduced by #2797:
- Re-add incorrectly deleted `deploy_volume_provisioner`
- Remove unused local vars
Tests
Side effects
```text
```
```shell
```

fix: some errors in install.sh

---

CHANGELOG.md
install.sh

Manually cherry-pick #2797.
Tests
Side effects
```text
```
```shell
```

removed docker registry mirror #2797

---

helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
helm/chaos-mesh/templates/controller-manager-deployment.yaml
install.sh

This PR uses an `if` condition to prevent generating empty `priorityClassName`.
Tests
Side effects
```text
```
```shell
```

fix: remove empty priorityClassName

---

install.sh

Manually cherry-pick #2858.
Tests
Side effects
```text
```
```shell
```

fix: some errors in install.sh #2858

---

helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
helm/chaos-mesh/templates/controller-manager-deployment.yaml
helm/chaos-mesh/templates/dns-deployment.yaml
helm/chaos-mesh/templates/prometheus-deployment.yaml
install.sh

Manually cherry-pick #2863.
Tests
Side effects
```text
```
```shell
```

fix: remove empty priorityClassName (#2863)

---

ui/app/src/components/NewExperimentNext/Step1.tsx
ui/app/src/components/NewExperimentNext/Step2.tsx
ui/app/src/components/NewExperimentNext/form/Mode.tsx
ui/app/src/components/NewExperimentNext/form/Scope.tsx
ui/app/src/lib/formikhelpers.ts

Close #2816
add `mode` input box on physical machine chaos
Tests
Side effects
```text
```
```shell
```

support `mode` on physical machine chaos

---

CHANGELOG.md
api/v1alpha1/physical_machine_chaos_types.go
api/v1alpha1/physical_machine_chaos_webhook.go

cherry pick from https://github.com/chaos-mesh/chaos-mesh/pull/2850 by manual.
fix issue: #2813 
Tests
Side effects
```text
```
```shell
```

PhysicalMachineChaos: add validate for network bandwidth

---

.github/workflows/ci.yml
.github/workflows/ci_skip.yml

Close #2934
Tests
Side effects
```text
```
```shell
```

Trigger verify action when helm chart is modified

---

ui/app/src/components/NewExperimentNext/form/Scope.tsx

Close #2914.
Tests
Side effects
```text
```
```shell
```

fix(ui): pod phases should be first letter capitalized

---

images/chaos-daemon/Dockerfile

The rs-tproxy repository is renamed to chaos-tproxy according to https://github.com/chaos-mesh/chaos-tproxy/pull/32
Tests
Side effects
```text
```
```shell
```

rename rs-tproxy to chaos-tproxy in Dockerfile of chaos-daemon

---

images/chaos-daemon/Dockerfile

cherry-pick(#2959)
-----------
The rs-tproxy repository is renamed to chaos-tproxy according to https://github.com/chaos-mesh/chaos-tproxy/pull/32
Tests
Side effects
```text
```
```shell
```

cherry-pick(#2959): rename rs-tproxy to chaos-tproxy in Dockerfile of chaos-daemon

---

CHANGELOG.md

- appending changelog
Tests
Side effects
```text
```
```shell
```

chore: appending changelog for #2902

---

ui/app/src/index.tsx

Now we can switch to `React.StrictMode` because MUI v5 is released. 🥳
Ref: https://github.com/mui/material-ui/issues/13394.
Tests
Side effects
```text
```
```shell
```

chore(ui): run in StrictMode

---

pkg/ctrlserver/graph/k8s-utils.go
pkg/ctrlserver/graph/schema.resolvers.go

cherry-pick #3017
-----------
Close #3007
Straightly select daemon pods by k8s client.
Tests
Side effects
```text
```
```shell
```

cherry-pick(#3017): fix chaos-daemon selection bug in ctrlserver

---

cmd/chaos-dashboard/main.go
pkg/dashboard/apiserver/handler.go
pkg/dashboard/apiserver/workflow/fx.go
pkg/dashboard/apiserver/workflow/workflow.go

Close #2877 
Move package level variable log into struct Service as a field.
Tests
Side effects
```text
```
```shell
```

Refine logging in `pkg/dashboard/apiserver/workflow`

---

CHANGELOG.md
helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

We are going to release v2.1.4
- bump image version
- rotate CHANGELOG
Tests
Side effects
```text
```
```shell
```

ready for 2.1.4

---

.github/workflows/upload_image.yml
pkg/time/fake_image.go
pkg/time/fake_image_linux_amd64.go
pkg/time/fakeclock/fake_gettimeofday.c

- try to fix arm64 compiling error: https://github.com/chaos-mesh/chaos-mesh/actions/runs/2015886763
- cherry-pick #2849 and #2935 into release-2.1
Tests
Side effects
```text
```
```shell
```

cherrypick #2849 and #2935 into release-2.1

---

ADOPTERS.md

Signed-off-by: haizi-cui <63744634+haizi-cui@users.noreply.github.com>
Tests
Side effects
```text
```
```shell
```

Add Maycur as Adopter

---

CHANGELOG.md

Append changelogs for #2555, #2950, #2990, and #3038.
Tests
Side effects
```text
```
```shell
```

append batches of changelogs

---

e2e-test/cmd/e2e_helper/Dockerfile

e2e: build e2e helper in go 1.18

---

CHANGELOG.md
api/v1alpha1/stresschaos_types.go
controllers/common/records/controller.go

Signed-off-by: xianglingao <xianglingao@tencent.com>
- fix #3100 on release-2.1
- cherry-pick #3102 into release-2.1
- append changelog
Tests
Side effects
```text
```
```shell
```

fix bug: cpu stress can not reach pod limit in some situation (#3102)

---

CHANGELOG.md

appending changelog for https://github.com/chaos-mesh/chaos-mesh/pull/3102
Tests
Side effects
```text
```
```shell
```

chore: append changelog for #3102

---

helm/chaos-mesh/templates/dns-deployment.yaml
helm/chaos-mesh/templates/dns-rbac.yaml

Fix the cluster role name for DNS server 
Use the correct cluster role name
Tests
Side effects
```text
```
```shell
```

Fix clusterrole name in DNS server

---

helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
install.sh

background ref #1206
Tests
Side effects
```text
remove host port declare in chaos-daemon-daemonset
```
```shell
```

remove host port declare in chaos-daemon-daemonset.yaml

---

.gitignore
CHANGELOG.md

Add changelogs to `CHANGELOG.md`
Tests
Side effects
```text
```
```shell
```

Append missing changelogs for branch `release-2.1`

---

CHANGELOG.md
helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

ready for 2.1.5
Tests
Side effects
```text
```
```shell
```

ready for 2.1.5

---

CHANGELOG.md

update changelogs for released version `v2.1.5`
Tests
Side effects
```text
```
```shell
```

chore: update changelogs for 2.1.5

---

Makefile
api/v1alpha1/physical_machine_chaos_webhook_test.go
api/v1alpha1/statuscheck_webhook_test.go

close https://github.com/chaos-mesh/chaos-mesh/issues/3165
CHANGELOG
Tests
Side effects
```text
```
```shell
```

test: active tests under api/v1alpha1

---

cmd/chaos-controller-manager/main.go
pkg/metrics/chaos-controller-manager.go

manually cherrypick #2912 into release-2.1

chore: refactor logging in pkg/metrics

---

.github/pull_request_template.md
.github/workflows/must_update_changelog.yml
CHANGELOG.md

* ci: new check for changelog
* chore: update changelog
* chore: update pr template
* chore: rename file
* chore: remove colon
* refactor: use job level env
cherry-pick #3148 into release-2.1
CHANGELOG
Tests
Side effects
```text
```
```shell
git commit …
```

ci: new check for changelog (#3148)

---

pkg/time/fake_image_linux_arm64.go

Signed-off-by: andrewmatilde <davis6813585853062@outlook.com>
Make arm64 build well.
#3191
CHANGELOG
Tests
Side effects
```text
```
```shell
```

fix not implement:fake_image_linux_arm64

---

CHANGELOG.md
helm/chaos-mesh/templates/_certs.tpl
helm/chaos-mesh/values.yaml

- it's a part of https://github.com/chaos-mesh/chaos-mesh/issues/3015;
- user could provide certain cabundle for webhooks
- add new `webhook.caBundlePEM` in "values.yaml"
- prefer to use `webhook.caBundlePEM` if it already exsited
CHANGELOG
Tests
Side effects
```text
```
```shell
```

chore: user could specify certain ca bundle for webhook

---

CHANGELOG.md

Update the changelog for release 2.2.0

chore: update chenglog for release 2.2.0

---

CHANGELOG.md
ui/app/src/App.tsx
ui/app/src/IntlProvider.tsx
ui/app/src/components/AutoForm/Info.tsx
ui/app/src/components/AutoForm/Schedule.tsx
ui/app/src/components/AutoForm/index.tsx
ui/app/src/components/FormField/AutocompleteField.tsx
ui/app/src/components/NewExperimentNext/Step2.tsx
ui/app/src/components/Scope/index.test.tsx
ui/app/src/components/Scope/index.tsx
ui/app/src/components/TopContainer/index.tsx
ui/app/src/lib/utils.test.ts
ui/app/src/lib/utils.ts
ui/app/src/slices/experiments.ts
ui/app/src/test-utils.tsx
ui/packages/mui-extends/src/AutocompleteField/index.tsx
ui/packages/mui-extends/src/FormControl/index.tsx
ui/packages/mui-extends/test/__snapshots__/storyshots.test.js.snap

Close #3224
This PR distinguishes between different scopes when creating `NetworkChaos`.
Also, you can also see some non-related changes, most of these are needed for testing. So the core changes of this PR I have marked below:
https://github.com/chaos-mesh/chaos-mesh/blob/f4a20a74e354f2ac22ea95edc848a71919912367/ui/app/src/components/Scope/index.tsx#L64-L66
It checks if the `scope` key is the target field of the `NetworkChaos`.
CHANGELOG
Tests
Side effects
```text
```
If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the …

fix(ui): isolate scopes when creating NetworkChaos

---

README.md

- add the badges for OpenSFF CII Best Practices: https://bestpractices.coreinfrastructure.org/en/projects/4185
- like that: 
[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/3680/badge)](https://bestpractices.coreinfrastructure.org/projects/3680)
CHANGELOG
Tests
Side effects
```text
```
```shell
```

chore: add CII best practices badge for Chaos Mesh

---

CHANGELOG.md
images/chaos-daemon/Dockerfile

Fix some bugs in chaos-tproxy v0.4.5: fix endless loop in graceful shutdown of config server; fix network on route.
Upgrade the chaos-tproxy binary to v0.4.6
CHANGELOG
Tests
Side effects
```text
```
```shell
```

bump chaos-tproxy to v0.4.6

---

.github/pull_request_template.md

The lifecycle of release-2.0 reaches the end, we should replace it with release-2.2 in PR template.
CHANGELOG
Tests
Side effects
```text
```
```shell
```

update cherry-pick options in PR template

---

cmd/chaos-controller-manager/main.go
cmd/chaos-controller-manager/provider/controller.go
cmd/chaos-controller-manager/provider/doc.go
controllers/types/types.go

appending more comments and docs
CHANGELOG
Tests
Side effects
```text
```
```shell
```

enriching comments and docs for chaos-controller-manager

---

controllers/chaosimpl/networkchaos/trafficcontrol/impl.go

Signed-off-by: xianglingao <xianglingao@tencent.com>
fix this discussion: https://github.com/chaos-mesh/chaos-mesh/discussions/2638
CHANGELOG
Tests
Side effects
```shell
```

remove duplicated code

---

README.md

https://medium.com/chaosiq/integrate-your-reliability-toolkit-with-your-world-part-2-e012f2c2a7f6 is dead, we should replace it with https://web.archive.org/web/20220223141503/https://blog.reliably.com/integrate-your-reliability-toolkit-with-your-world-part-2-e012f2c2a7f6.
CHANGELOG
Tests
Side effects
```shell
```

fix readme: replace deadlink with web-archive link

---

CHANGELOG.md
pkg/bpm/build_linux.go
pkg/chaosdaemon/stress_server_linux.go

cherry-pick #3405 to release-2.2

 stresschaos: run pause before choom (#3405)

---

CHANGELOG.md
images/chaos-daemon/Dockerfile

Signed-off-by: andrewmatilde <davis6813585853062@outlook.com>
Fix some bugs in chaos-tproxy v0.5.0.
Fix : https://github.com/chaos-mesh/chaos-tproxy/issues/50
Fix network on bridge ARP & FDB
Upgrade the chaos-tproxy binary to v0.5.1
CHANGELOG
Tests
Side effects
```shell
```

bump tproxy to 0.5.1

---

ui/app/src/i18n/en.json
ui/app/src/i18n/zh.json

Close #3438
CHANGELOG
Tests
Side effects
```shell
```

chore(i18n): experiment type to inject into

---

helm/chaos-mesh/README.md

controllerManager.image.x is repeated. one should be chaosDaemon.image.x
Signed-off-by: yi.tang <tinetkiller@gmail.com>

fix doc error

---

helm/chaos-mesh/README.md

dashboard.persistentVolume.enable -> dashboard.persistentVolume.enabled
CHANGELOG
Tests
Side effects
```shell
```

Fix helm chart README typo

---

GOVERNANCE.md

As mentioned in https://github.com/chaos-mesh/chaos-mesh/discussions/3433, update the governance rule for member.
CHANGELOG
Tests
Side effects
```shell
```

chore: update the goverance for member

---

CHANGELOG.md
pkg/ctrl/server/schema.resolvers.go

Some methods in ctrl server are unimplemented, they may panic when you use chaosctl.
CHANGELOG
Tests
Side effects
```shell
```

implement some missing methods in ctrl server

---

MAINTAINERS.md

In accordance with our [Governance](https://github.com/chaos-mesh/chaos-mesh/blob/master/GOVERNANCE.md#committer), I am pleased to promote @Hexilee  as a new committer. I would like to hereby thank him for his great contributions to the project and look forward to seeing more of his growth and engagements.
Chaos Mesh is the first full-time project for me, and I learn how open source communities work and govern from it, which affects my values of open source greatly. I have contributed to Chaos Mesh for more than one year and it provides me a stage to communicate with users and developers in the world, I believe this project will benefit my whole career.  Becoming a Chaos Mesh Committer is not only a recognition for my contributions, but also a …

Promote "Chenxi Li" to committer

---

.github/.licenserc.yaml
CHANGELOG.md
helm/chaos-mesh/templates/chaos-daemon-service.yaml
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
helm/chaos-mesh/templates/controller-manager-service.yaml
install.sh
manifests/monitoring/README.md
manifests/monitoring/prometheus-kubernetes-service-discovery/prometheus-additional.yaml
manifests/monitoring/prometheus-operator/chaos-controller-manager-servicemonitor.yaml
manifests/monitoring/prometheus-operator/chaos-daemon-servicemonitor.yaml
manifests/monitoring/prometheus-operator/chaos-dashboard-servicemonitor.yaml
pkg/metrics/chaos-daemon.go

Tests
Side effects
```text
```
```shell
```

Guide and example manifests for monitoring chaos mesh

---

CHANGELOG.md
pkg/config/dashboard/dashboard.go
pkg/dashboard/collector/server.go
pkg/dashboard/swaggerdocs/docs.go
pkg/dashboard/swaggerdocs/swagger.json
pkg/dashboard/swaggerdocs/swagger.yaml

This PR manually cherrypick #3476 into release-2.1

chore: configure QPS and Burst for chaos dashboard (#3476)

---

CHANGELOG.md
pkg/chaosdaemon/jvm_server.go

close https://github.com/chaos-mesh/chaos-mesh/issues/3472
- copy missing file `/usr/local/byteman/lib/chaos-agent.jar` into applications container / mount namespace
CHANGELOG
Tests
Side effects
```shell
```

fix JVMChaos missing file: /usr/local/byteman/lib/chaos-agent.jar

---

CHANGELOG.md
helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

CHANGELOG
Tests
Side effects
```shell
```

Bump version to v2.1.7

---

CHANGELOG.md
ui/app/src/components/AutoForm/index.tsx

Close #3420
This PR supports creating `KernelChaos` in the `<AutoForm />` component, which is introduced in the next generation `New Workflow`. Below is a demo:
https://user-images.githubusercontent.com/15034155/178754930-c0d82f83-2bc7-4531-9435-cfff04df8f39.mp4
CHANGELOG
Tests
Side effects
```shell
```

chore: support `KernelChaos` in `AutoForm`

---

CHANGELOG.md
ui/app/src/components/AutoForm/index.tsx

this PR manually cherrypick #3449 into release-2.3

cherry pick #3449 to release-2.3

---

.github/workflows/e2e_test.yml
env-images.yaml

This PR update the env tag for branch release-2.3

update env image tag for branch release-2.3

---

helm/chaos-mesh/values.yaml

Update image tag for release 2.3.0

update image tags as v2.3.0 

---

CHANGELOG.md
pkg/dashboard/apiserver/common/common.go

* Protect chaos available namespace and filter namespaces if needed
Signed-off-by: brnck <a.berneckas@gmail.com>
* Update Changelog
Signed-off-by: brnck <a.berneckas@gmail.com>
CHANGELOG
Tests
Side effects
```shell
```

Protect chaos available namespace and filter namespaces if needed (#3473)

---

CHANGELOG.md
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
install.sh
pkg/config/dashboard/dashboard.go
pkg/dashboard/apiserver/server.go
pkg/dashboard/swaggerdocs/docs.go
pkg/dashboard/swaggerdocs/swagger.json
pkg/dashboard/swaggerdocs/swagger.yaml

* Respect flag enableProfiling and do not register profiler endpoints when it's false
Signed-off-by: brnck <a.berneckas@gmail.com>
* Update swaggerdocs, install.sh script
Signed-off-by: brnck <a.berneckas@gmail.com>
Co-authored-by: Yue Yang <g1enyy0ung@gmail.com>
CHANGELOG
Tests
Side effects
```shell
```

Respect flag enableProfiling in chaos-dashboard (#3474)

---

.github/pull_request_template.md

Except updates the cherry-pick versions, this PR also updates:
1. Recommend using https://www.conventionalcommits.org/en/v1.0.0/ as the format for PR titles.
2. Clarify the description of related changes.
3. Use bolded symbols to identify breaking changes.
CHANGELOG
Tests
Side effects
```shell
```

chore: update PR template due to v2.3 released

---

CHANGELOG.md
ui/app/src/components/NewExperimentNext/Step2.tsx
ui/app/src/components/NewExperimentNext/data/types.ts
ui/app/src/components/NewExperimentNext/form/Kernel.tsx
ui/app/src/components/NewExperimentNext/form/Stress.tsx
ui/app/src/i18n/en.json
ui/app/src/i18n/zh.json

* fix(ui): IOChaos `containerNames` field
* chore: update CHANGELOG
Cherry-pick #3533.
CHANGELOG
Tests
Side effects
```shell
```

fix(ui): IOChaos `containerNames` field (#3533)

---

CHANGELOG.md
pkg/dashboard/apiserver/event/event.go

Close #2874
Moved package level variable log into struct Service as a field. 
CHANGELOG
Tests
Side effects

Refine logging in pkg/dashboard/apiserver/event

---

CHANGELOG.md
Makefile
e2e-test/config.go
e2e-test/e2e/chaos/podchaos/pod_failure.go
e2e-test/e2e/config/config.go
e2e-test/e2e/e2econst/const.go

Signed-off-by: zhengbingxian <zhengbingxian@archeros.com>
https://github.com/chaos-mesh/chaos-mesh/issues/3560
Q: What's changed?
A: Add pause-image arg in e2e config file. And also add arg in Makefile to accept the custom pause image.
Q:how it works?
A:
Now we can run e2e like this:
```shell
make e2e PAUSE_IMAGE=<my custom pause image>
```
Inside of the commad, it works like :
```shell
./e2e-test/image/e2e/bin/ginkgo  \
./e2e-test/image/e2e/bin/e2e.test \
-- --e2e-image ghcr.io/pingcap/e2e-helper:latest \
--pause-image <my custom pause image>   
```
CHANGELOG
Tests
Side effects …

Add "pause image" settings for e2e config

---

CHANGELOG.md
controllers/common/finalizers/controller.go
controllers/common/finalizers/step.go
controllers/common/step.go
controllers/common/suit_test.go

Fix recover bug when setting force recover to true
CHANGELOG
Tests
Side effects
```shell
```

Add cleanFinalizer controller

---

CHANGELOG.md
helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml
install.sh

CHANGELOG
Tests
Side effects
```shell
```

Bump version to v2.1.8

---

CHANGELOG.md
ui/app/src/components/FormField/LabelField.tsx
ui/app/src/components/NewExperimentNext/data/types.ts
ui/app/src/components/NewExperimentNext/form/Kernel.tsx
ui/app/src/components/NewExperimentNext/form/Stress.tsx
ui/app/src/i18n/en.json
ui/app/src/i18n/zh.json
ui/yarn.lock

Same as #3533, but for the `v2.1` branch.
CHANGELOG
Tests
Side effects
```shell
```

fix: uniformly use Enter to add item in LabelField

---

pkg/time/time_linux_arm64.go

CHANGELOG
Tests
Side effects
```shell
```

fix time pkg on arm platform

---

CHANGELOG.md
controllers/common/finalizers/README.md
controllers/common/finalizers/controller.go
controllers/common/finalizers/step.go
controllers/common/step.go
controllers/common/suit_test.go

Cherry-pick #3578
CHANGELOG
Tests
Side effects
```shell
```

Add cleanFinzlizer controller (cherry-pick #3578)

---

CHANGELOG.md
pkg/dashboard/apiserver/common/common.go

`chaos-available-namespaces` API will be used before entering Token. If we add this checker will make generating token action fail.  Caused by https://github.com/chaos-mesh/chaos-mesh/pull/3473
Remove token checker when listing namespaces. 
CHANGELOG
Tests
Side effects
```shell
```

Remove token checker when listing namespaces

---

CHANGELOG.md
pkg/dashboard/apiserver/common/common.go

cherry-pick #3595
CHANGELOG
Tests
Side effects
```shell
```

Remove token checker when listing namespaces (cherry-pick #3595)

---

MAINTAINERS.md

CHANGELOG
Tests
Side effects
```shell
```

chore: update infomation about zhiqiang

---

README.md

CHANGELOG
Tests
Side effects
```shell
```

Update dev meeting info

---

CHANGELOG.md
api/v1alpha1/physical_machine_chaos_webhook.go
api/v1alpha1/physical_machine_chaos_webhook_test.go

fix https://github.com/chaos-mesh/chaos-mesh/issues/3481
CHANGELOG
Tests
* Build chaos-controller-manager and deployed into k8s cluster
* Test physicalmachinechaos with below yaml and verify that the experiment is really injected to the target node.
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
name: physical-network-corrupt
namespace: testing
spec:
action: network-corrupt
mode: one
selector:
fieldSelectors:
'metadata.name': ip-10-180-155-66.eu-central-1.compute.internal
network-corrupt:
device: ens5
percent: '5'
duration: '10m'
```
* Test other network hack types like `delay`, `loss` and `duplicate`
Side effects
If you find the DCO check fails, please run commands like below (Depends on the actual …

delete ip/hostname check in validation webhook

---

CHANGELOG.md
api/v1alpha1/physical_machine_chaos_webhook.go
api/v1alpha1/physical_machine_chaos_webhook_test.go

Signed-off-by: Jerry Jia <jerry.jia@sap.com>
cherrypick ##3483 to branch release-2.2

cherrypick: delete ip/hostname check in validation webhook (#3483)

---

MAINTAINERS.md

CHANGELOG
Tests
Side effects
```shell
```

chore: update info about Glen Yang

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

CHANGELOG
Tests
Side effects
```shell
```

Update tag to v2.3.2

---

CHANGELOG.md
ui/app/src/components/NewExperimentNext/data/types.ts

CHANGELOG
Tests
Side effects
```shell
```

fix: remove limit action from BlockChaos (#3655)

---

tools/schedule-migration/migrate.sh

Follow #3243.
CHANGELOG
Tests
Side effects
```shell
```

chore: remove unused var

---

CHANGELOG.md

CHANGELOG
Tests
Side effects
```shell
```

chore: update v2.4.0 changelog

---

CHANGELOG.md
helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml

- a part of https://github.com/chaos-mesh/chaos-mesh/issues/3678
- mark not as pre-release
- bump version to 2.4.1
CHANGELOG
Tests
Side effects
```shell
```

chore: update helm chart and bump version

---

README.md

Refer to https://clomonitor.io/docs/topics/checks/#artifact-hub-badge.
CHANGELOG
Tests
Side effects
```shell
```

chore: add Artifact Hub badge

---

.github/workflows/checklink.yaml
.github/workflows/ci.yml
.github/workflows/ci_skip.yml
.github/workflows/codecov_unittest.yaml
.github/workflows/e2e_test.yml
.github/workflows/e2e_test_upload_cache.yml
.github/workflows/integration_test.yml
.github/workflows/license_checker.yml
.github/workflows/must_update_changelog.yml
.github/workflows/release_helm_chart.yml
.github/workflows/stale.yml
.github/workflows/upload_env_image.yml
.github/workflows/upload_image.yml
.github/workflows/upload_image_pr.yml
.github/workflows/upload_latest_files.yml
.github/workflows/upload_release_files.yml
ui/app/src/api/http.ts

Close #3699
Refer to #3696, this PR is a subtask that tries to bring CLOMonitor Score to 100%.
CHANGELOG
Tests
Side effects
```shell
```

chore: set actions permissions to write on demand

---

.github/workflows/e2e_test.yml
.github/workflows/e2e_test_skip.yml
.github/workflows/e2e_test_upload_cache.yml
.github/workflows/integration_test.yml

As the title. Refer to #3721.
CHANGELOG
Tests
Side effects
```shell
```

fix: ignore more unnecessary workflows

---

CHANGELOG.md
pkg/dashboard/apiserver/event/event.go
pkg/dashboard/swaggerdocs/docs.go
pkg/dashboard/swaggerdocs/swagger.json
pkg/dashboard/swaggerdocs/swagger.yaml

As the title.
CHANGELOG
Tests
Side effects
```shell
```

fix(swagger): update `is mandatory` to true

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

CHANGELOG
Tests
Side effects
```shell
```

chore: ready for 2.3.3

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

CHANGELOG
Tests
Side effects
```shell
```

chore: ready for release 2.4.2

---

.github/workflows/upload_image.yml

Fixes problems introduced in #3766.
CHANGELOG
Tests
Side effects
```shell
```

fix: replace env variables with contexts

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

ready for release patch version 2.4.3

chore: ready for 2.4.3

---

CHANGELOG.md
env-images.yaml
helm/chaos-mesh/Chart.yaml
helm/chaos-mesh/values.yaml

We are going  to release 2.5.0, 🥳

chore: ready for 2.5.0

---

env-images.yaml

As the title.
CHANGELOG
Tests
Side effects
```shell
```

fix: update tags to release-2.4

---

.github/pull_request_template.md

CHANGELOG
Tests
Side effects
```shell
```

chore: update pr tempalte for 2.5

---

CHANGELOG.md

CHANGELOG
Tests
Side effects
```shell
```

chore: update v2.5 changelog

---

ui/app/src/components/NewWorkflowNext/__snapshots__/BareNode.test.tsx.snap
ui/app/src/components/Scope/index.test.tsx

CHANGELOG
Tests
Side effects
```shell
```

test(ui): fix <Scope /> tests

---

ui/packages/mui-extends/test/__snapshots__/storyshots.test.js.snap

CHANGELOG
Tests
Side effects
```shell
```

test(ui): update mui-extends snapshots

---

ui/packages/mui-extends/test/__snapshots__/storyshots.test.js.snap

I forgot to pull the latest changes to the master branch in #3841, resulting in an incomplete snapshot update.
CHANGELOG
Tests
Side effects
```shell
```

test(ui): fix a mistake introduced in #3841

---

ui/app/src/components/NewExperimentNext/data/types.ts

CHANGELOG
Tests
Side effects
```shell
```

fix: container kill desc

---

.github/workflows/stale.yml
.github/workflows/upload_env_image.yml
.github/workflows/upload_image.yml
.github/workflows/upload_latest_files.yml
CHANGELOG.md

#3818 merged with conflicts, this pr try to resolve these conflicts and push #3820 to get merged
CHANGELOG
Tests
Side effects
```shell
```

fix: resolve conflict from #3818

---

CHANGELOG.md
images/chaos-daemon/Dockerfile

Update byteman to v4.0.20-0.12 and build byteman-helper using JDK8  https://github.com/chaos-mesh/byteman-helper/pull/15
CHANGELOG
Tests
Side effects
```shell
```

Update byteman-helper to v4.0.20-0.12

---

.github/workflows/merge_conflict_finder.yaml
CHANGELOG.md

close https://github.com/chaos-mesh/chaos-mesh/issues/3806
- using https://github.com/marketplace/actions/merge-conflict-finder
- because merge conflicts could easily funded by searching `<<<<<` , so I do not let this certain action need necessary on  the dev machine.
CHANGELOG
Tests
Side effects
```shell
```

ci: setup new CI for finding merge conflicts

---

CHANGELOG.md
images/chaos-mesh/Dockerfile

Signed-off-by: q7r <qsevenr@protonmail.com>
Close #3891
CHANGELOG
Tests
Side effects
```shell
```

Upgrade base image for chaos-mesh to alpine:3.17

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

Release `v2.5.1` for recent new changes.
CHANGELOG
Tests
Side effects
```shell
```

chore: ready for v2.5.1

---

CHANGELOG.md
images/chaos-daemon/Dockerfile
images/chaos-dashboard/Dockerfile

Eliminate as many vulnerabilities as possible and bring the OS up to date. 
Only the software packages in the images that it really needs.
the latest Debian version is used and the security repo is attached. The chaos-daemon image is a multi-stage image, so curl is no longer in the image.
CHANGELOG
Tests
Side effects
```shell
```

Update chaos mesh images

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

Release `v2.5.2` for recent new changes.
CHANGELOG
Tests
Side effects
```shell
```

chore: ready for v2.5.2

---

CHANGELOG.md
hack/pause.c

CHANGELOG
Tests
Side effects
```shell
```

improve pause

---

.github/.licenserc.yaml
CHANGELOG.md
OWNERS
OWNERS_ALIASES

CHANGELOG
Tests
Side effects
```shell
```

feat: setup OWNERS for chaos-mesh

---

CHANGELOG.md
env-images.yaml
helm/chaos-mesh/values.yaml

Release `v2.6.0` for the last half-year changes. This release has no significant changes but many enhancements and bug fixes that we've already merged into `v2.5`. In short, this version of Chaos Mesh has become more stable.
We will further listen to users' opinions to add essential features, thank you for your support and use!

release: ready for v2.6.0

---

CHANGELOG.md
pkg/dashboard/store/experiment/experiment.go
pkg/dashboard/store/schedule/schedule.go
pkg/dashboard/store/workflow/workflow.go

fix dashboard panic when exec delete action by finish_time (#4100)

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

chore: ready for v2.6.1

---

CHANGELOG.md
helm/chaos-mesh/README.md
helm/chaos-mesh/templates/chaos-daemon-rbac.yaml
helm/chaos-mesh/templates/controller-manager-rbac.yaml
helm/chaos-mesh/values.yaml

Currently there is no way to add AWS IAM roles to the service accounts of chaos-daemon and chaos-controller-manager.
This change adds the ability to add annotations, and therefore IAM roles, to the service accounts.
Close #4092
Two new configuration options have been introduced in the helm chart to provide annotations to the service accounts of chaos-daemon and chaos-controller-manager.
As a reference, here is the official AWS guide describing how a service account can assume an IAM role.
- https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html
If you find the DCO check fails, please run commands like below (Depends on …

Allow annotations on chaos-controller-manager and chaos-daemon ServiceAccount

---

CHANGELOG.md

fix: section order of changelog

---

CHANGELOG.md
pkg/dashboard/core/event.go
pkg/dashboard/core/experiment.go
pkg/dashboard/core/schedule.go

Cherry-pick #4151.
```shell
```

Set the database column type to text for 'Workflow/Experiment/Schedule'

---

.github/workflows/upload_env_image.yml
.github/workflows/upload_image.yml
CHANGELOG.md

chore: upgrade docker/login-action to v2 (#4167)

---

.github/workflows/ci.yml
.github/workflows/e2e_test.yml
.github/workflows/e2e_test_upload_cache.yml
.github/workflows/license_checker.yml
.github/workflows/merge_conflict_finder.yaml
.github/workflows/release_helm_chart.yml

chore: upgrade actions/checkout to v3

---

CHANGELOG.md
ui/app/src/App.tsx
ui/app/src/api/http.ts
ui/app/src/components/TopContainer/Auth.tsx
ui/app/src/components/TopContainer/index.tsx
ui/app/src/pages/Settings/Token.tsx
ui/app/src/pages/Settings/index.tsx
ui/app/src/reactQueryClient.ts
ui/app/src/slices/globalStatus.ts

Manually cherry-pick #4193.
```shell
```

feat: remove token when get Unauthorized (#4193)

---

CHANGELOG.md
pkg/portforward/portforward.go

fix: goroutine leak (#4229)

---

CHANGELOG.md
controllers/common/condition/condition_suite_test.go
controllers/common/condition/controller.go
controllers/common/condition/controller_test.go

refactor: optimize `allInjected` and `allRecovered` states (#4199)

---

CHANGELOG.md
controllers/common/records/controller.go

Adds log fields to record experiment `name`, `namespace` and `kind` for the common chaos events "apply chaos" and "recover chaos".  This helps us with monitoring our chaos experiments and configuring alert notifications.
Small refactor of logging code surrounding the "apply chaos" and "recover chaos" events in `controllers/common/records/controller.go`
Creates a local `logger` object decorated using `WithValues()` in order to reuse the values for surrounding info and error logs. …

chore: Add log fields for apply chaos and surrounding code

---

CHANGELOG.md
controllers/multicluster/remotechaosmonitor/controller.go

close #4108
watch remotechaos exeriments status in `remotechaosmonitor` and update it locally
```shell
```

sync remote chaos experiements status

---

helm/chaos-mesh/values.schema.json
helm/chaos-mesh/values.yaml

After we cherry-pick #4205 into the `v2.6` branch, Helm validation will fail during installation because the dns-server image value is different from the latest version (#4091).
Use https://github.com/losisin/helm-values-schema-json to re-generate schema.
```shell
```

fix: helm values schema

---

CHANGELOG.md
images/chaos-daemon/Dockerfile

Cherry-pick #4299.
```shell
```

Update byteman-helper to v4.0.22-0.12

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

chore: ready for 2.6.3

---

CHANGELOG.md
helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml

feat(helm): allow templating of dashboard rootUrl (#4370)

---

CHANGELOG.md
pkg/dashboard/apiserver/event/event.go
pkg/dashboard/apiserver/experiment/experiment.go
pkg/dashboard/apiserver/schedule/schedule.go
pkg/dashboard/apiserver/template/template.go
pkg/dashboard/apiserver/utils/auth.go

fix: dashboard panic while replacing query namespace with target namespace in namespace scoped mode

---

cmd/generate-makefile/doc.go
cmd/generate-makefile/funcmaps.go

As the title. An intuitive optimization.
```shell
```

perf: simplify join func

---

.github/workflows/ci.yml
CHANGELOG.md
Makefile
build/get_env_shell.py
helm/chaos-mesh/README.md
helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
helm/chaos-mesh/templates/chaos-daemon-rbac.yaml
helm/chaos-mesh/templates/controller-manager-deployment.yaml
helm/chaos-mesh/templates/controller-manager-rbac.yaml
helm/chaos-mesh/values.schema.json
helm/chaos-mesh/values.yaml
images/dev-env/Dockerfile
install.sh

Cherry-pick #4106, #4390, #4435

---

.github/workflows/ci.yml
.github/workflows/ci_skip.yml
.github/workflows/must_update_changelog.yml

chore: upgrade paths-filter

---

CHANGELOG.md
images/chaos-daemon/Dockerfile

cherrypick release-2.6: Bump version to toda to v0.2.4 (#4449)

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

chore: ready for v2.6.4

---

.github/workflows/release_helm_chart.yml

ci: update release helm chart

---

CHANGELOG.md
helm/chaos-mesh/templates/_certs.tpl
helm/chaos-mesh/templates/cert-manager-certs.yaml

Minor fixes in certificates to make them ArgoCD friendly

---

CHANGELOG.md
helm/chaos-mesh/templates/_certs.tpl
helm/chaos-mesh/templates/cert-manager-certs.yaml

Manually cherry-pick #4482.
```shell
```

Minor fixes in certificates to make them ArgoCD friendly (#4482)

---

CHANGELOG.md
env-images.yaml
helm/chaos-mesh/values.yaml

This is a regular minor version upgrade, mainly for feature enhancements and bug fixes. Some of these changes have been cherry-picked into `2.6.x` versions. So we recommend that you use or upgrade to `2.7.0` without making any special changes (except for updating the CRDs). Thank you for your use. If you encounter any problems during the upgrade or use, please report them as an issue.

release: ready for v2.7.0

---

CHANGELOG.md
pkg/dashboard/apiserver/archive/archive.go
pkg/dashboard/store/workflow/workflow.go
ui/app/src/components/YAMLEditor/index.tsx
ui/app/src/pages/Archives/Single.tsx

Manually cherry-pick #4521 into `release-2.7`.

[release-2.7] fix: get a single archive by kind

---

.github/.licenserc.yaml
.well-known/funding-manifest-urls

This PR makes endorsements for our maintainers @STRRL and @g1eny0ung for their contribution, supports them accept funding as individuals.

chore: support endorsemnet for maintainers

---

CHANGELOG.md
helm/chaos-mesh/templates/prometheus-deployment.yaml
helm/chaos-mesh/values.schema.json
helm/chaos-mesh/values.yaml

> [!IMPORTANT]
>
>
> [!TIP]
> [!TIP] …

fix: wrong references of helm values in the prometheus template

---

CHANGELOG.md
pkg/dashboard/apiserver/archive/archive.go
pkg/dashboard/apiserver/archive/archive_test.go

> [!IMPORTANT]
>
>
> [!TIP]
> [!TIP] …

dashboard: return 404 when the archive schedule was not found (#4553)

---

CHANGELOG.md
pkg/metrics/chaos-controller-manager.go
pkg/metrics/chaos-daemon.go

> [!IMPORTANT]
>
>
> [!TIP]
> [!TIP]
Use gauge subsystem in controller/daemon metrics.
> This PR should be cherry-picked to the …

feat(metrics): use gauge subsystem in controller/daemon metrics

---

.github/workflows/e2e_test.yml
.github/workflows/integration_test.yml
test/integration_test/auth-rbac-webhook/run.sh
test/integration_test/dashboard_authority/run.sh
test/integration_test/physical_machine/chaos.yaml
test/integration_test/physical_machine/run.sh

Referring to #4589, I naively thought that removing the arm64 key-value pair would disable the arm64 arch, but it still requires some additional modifications...
> [!TIP]
```shell
```

fix: syntax of integration test

---

CHANGELOG.md
ui/app/src/components/NewExperimentNext/Step3.tsx
ui/app/src/components/NewWorkflowNext/utils/convert.ts
ui/app/src/components/Scope/TargetsTable/index.tsx
ui/app/src/lib/formikhelpers.ts

> [!TIP]
> [!TIP]
> [!TIP]
```shell
```

[release-2.7] fix: parse physical machines (#4580)

---

CHANGELOG.md
ui/app/src/components/NewExperimentNext/Step3.tsx
ui/app/src/components/NewWorkflowNext/utils/convert.ts
ui/app/src/components/Scope/TargetsTable/index.tsx
ui/app/src/lib/formikhelpers.ts

> [!IMPORTANT]
>
>
> [!TIP]
> [!TIP] …

[release-2.6] fix: parse physical machines (#4580)

---

CHANGELOG.md
pkg/metrics/chaos-controller-manager.go
pkg/metrics/chaos-daemon.go

Ref: #4554
> [!TIP]
> [!TIP]
```shell
```

[release-2.7] feat(metrics): use gauge subsystem in controller/daemon metrics (#4554)

---

.github/workflows/e2e_test.yml
.github/workflows/integration_test.yml
test/integration_test/auth-rbac-webhook/run.sh
test/integration_test/dashboard_authority/run.sh
test/integration_test/physical_machine/chaos.yaml
test/integration_test/physical_machine/run.sh

> [!TIP]
> [!TIP]
> [!TIP]
```shell
```

[release-2.7] fix: syntax of integration test (#4590)

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

chore: ready for v2.7.1

---

CHANGELOG.md
helm/chaos-mesh/values.yaml

chore: ready for v2.6.6

---

CHANGELOG.md
images/build-env/Dockerfile
images/chaos-daemon/Dockerfile
images/chaos-dashboard/Dockerfile
images/chaos-dlv/Dockerfile
images/chaos-mesh/Dockerfile

> [!IMPORTANT]
>
>
> [!TIP]
> [!TIP] …

fix: upgrade all base images to bookworm (#4676)

---

CHANGELOG.md
images/chaos-daemon/Dockerfile

> [!IMPORTANT]
>
>
> [!TIP]
> [!TIP] …

chore: update byteman-helper to v4.0.24

---

CHANGELOG.md
images/chaos-daemon/Dockerfile

> [!IMPORTANT]
>
>
> [!TIP]
> [!TIP] …

chore: update byteman-helper to v4.0.24 (#4681)

---

.github/workflows/ci.yml

> [!IMPORTANT]
>
>
> [!TIP]
> [!TIP] …

ci: upgrade node and pnpm

---

pkg/dashboard/swaggerdocs/docs.go
pkg/dashboard/swaggerdocs/swagger.json
pkg/dashboard/swaggerdocs/swagger.yaml

> [!IMPORTANT]
>
>
> [!TIP]
> You can also close #issue_number if this PR solves the issue.  
Run `Make check` and to regenerate chaosdashboard swaggerdocs. 
> [!TIP]
> This PR should be …

chore: update chaosdashboard swaggerdocs
