- README.md
Signed-off-by: mahjonp <junpeng.man@gmail.com>
PR #101 has bumped deployment api version to apps/v1, chaos-mesh could be deployed in K8s v1.16 and v1.17.
So we should widen chaos-mesh's Kubernetes deployment version, remove the upper bound now.
> README: widen k8s deployment version

- api/v1alpha1/common_types.go
- examples/chaosfs-configmap/etcd-configmap.yaml
- examples/chaosfs-configmap/pd-configmap.yaml
- examples/chaosfs-configmap/tikv-configmap.yaml
- pkg/utils/selector.go
- pkg/utils/selector_test.go
Signed-off-by: cwen0 <cwenyin0@gmail.com> 
In this pr, we add the namespace in ConfigMaps and ignore the phase of the pod when to check if it meets the selector
> selector: ignore the phase of the pod when to check if it meets the selector

- README.md
Fix the install command and some comments.
Until helm2 reached EOL,we would use the both helm version via 2.x and 3.x.
fixes #165 
Add the install command with helm 3.x.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Adapt the install command to the helm 3.x version.

- MAINTAINERS.md
Add maintainers to Chaos Mesh. The maintainers may be change overtime
Tests 
- No code
Code changes
- No code changes
Side effects
- None
- None
> Add maintainers to Chaos Mesh

- controllers/networkchaos/netem/types.go
- controllers/networkchaos/partition/types.go
fix controller-manager panic 
panic log:  
```
2020-02-08T10:17:58.144Z        INFO    controllers.NetworkChaos        Try to apply netem on pod       {"reconciler": "networkchaos", "action": "netem", "namespace": "nginx-ns
", "name": "nginx-deployment-5c689d88bb-425zp"}
2020-02-08T10:17:58.144Z        INFO    util    Creating client to chaos-daemon {"node": "kind-worker5"}
E0208 10:17:58.274823       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer derefe$
ence)
goroutine 258 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14cc560, 0x239f1d0)
/home/jenkins/agent/workspace/build_chaos_mesh_master/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/runtime/runtime.go …
```
> Fix networkchaos panic caused by duration being nil

- hack/kind-cluster-build.sh
Errors when helm3 is installed
```
Error: unknown flag: --service-account
```
Check helm version and by pass init for v3
Tests
- Manual test by running the script
Code changes
- Has hack code change
```release-note
NONE
```
> Fix errors in `hack/kind-cluster-build.sh` with helm3

- helm/chaos-mesh/templates/chaos-daemon-deployment.yaml
- helm/chaos-mesh/templates/collector-mysql.yaml
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/dashboard-deployment.yaml
- helm/chaos-mesh/templates/post-install-create-cert-job.yaml
- helm/chaos-mesh/templates/post-install-mutatingwebhook-job.yaml
- helm/chaos-mesh/templates/pre-delete-job.yaml
- helm/chaos-mesh/values.yaml
Fixes #200 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Add annotations in helm chart

- cmd/chaos-daemon/main.go
- go.mod
- go.sum
- helm/chaos-mesh/templates/chaos-daemon-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/values.yaml
- pkg/chaosdaemon/http.go
- pkg/chaosdaemon/ipset_server.go
- pkg/chaosdaemon/iptables_server.go
- pkg/chaosdaemon/netem_server.go
- pkg/chaosdaemon/server.go
This PR adds some basic prometheus metrics to chaos-daemon:
1. process metrics
2. go metrics
3. grpc metrics
Since we need to expose `/metrics` http endpoint, so add a `http-port` to chaos-daemon.
Also, refactor a little bit of code in chaos-daemon to make it more readable. This seems make this PR much larger, but I cannot come up with a way to split it. So feel free to review and comment on this PR!
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
The previous `port` parameter in chaos-daemon …
```
> Support prometheus metrics in chaos-daemon

- examples/etcd/etcd-configmap.yaml
- examples/etcd/etcd-iochaos.yaml
- examples/etcd/etcd.yaml
- scripts/wait-fuse.sh
Fixes #216.
Etcd can achieve the same purpose for iochaos testing and it is easier with the help of etcdctl.
Verification:
```
60 / 60 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00% 1m0s
FAIL: Throughput too low: 79 writes/s
Slowest request took too long: 6.761501s
Stddev too high: 1.384703s
FAIL
60 / 60 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00% 1m0s
PASS: Throughput is 150 writes/s
PASS: Slowest request took 0.029531s
PASS: Stddev is 0.001335s
PASS
```
cc @Yisaer 
Tests 
- Unit test
- E2E test
- No code
Code changes
- …
> Add etcd iochaos example

- cmd/controller-manager/main.go
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-service.yaml
- helm/chaos-mesh/values.yaml
This is a prerequisite of adding Prometheus to chaos-mesh. Exposing 8080 in chaos controller-manager enables Prometheus to get metrics from controller-manager.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Change controller-manager default metrics port to 10080
```
> Expose chaos controller metrics in helm chart

- README.md
Signed-off-by: Laura Henning <laura-marie.henning@stud.h-da.de>
The restrictions for minikube are not up to date: netem related chaos can be run in default minikube vm in versions >= 1.6 now
I did a PR to minikube to make a tool called pumba work, which also uses tc netem. I noticed the kernel module was missing, and minikube guys accepted my PR to add it :)
This is just a change to the README of this project, so I ran no additional tests.
> Correct minikube restriction: sch_netem is loaded by default in v1.6.

- Makefile
`Recursive variable 'PATH'` during `make`
Remove first space
Tests 
- Manual test
> Fix `Recursive variable 'PATH'` bug

- cmd/controller-manager/main.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Fix event recorder name

- doc/get_started_on_kind.md
- helm/chaos-mesh/templates/post-install-create-cert-job.yaml
- helm/chaos-mesh/templates/post-install-webhook-job.yaml
- helm/chaos-mesh/templates/pre-delete-job.yaml
- helm/chaos-mesh/values.yaml
- install.sh
use docker mirror to pull the image in install.sh
- Manual test (add detailed scripts or steps below) 
```
./install.sh --local kind --docker-mirror 
``` 
output: 
```
chaos-mesh:chaos-controller-manager  27s
==> v1beta1/MutatingWebhookConfiguration
NAME                         AGE
chaos-mesh-sidecar-injector  27s
==> v1beta1/ValidatingWebhookConfiguration
NAME                   AGE
chaos-mesh-validation  27s
NOTES:
1. Make sure chaos-mesh components are running
kubectl get pods --namespace chaos-testing -l app.kubernetes.io/instance=chaos-mesh
Chaos Mesh chaos-mesh is installed successfully
```
> support docker mirror in install.sh

- examples/web-show/deploy.sh
- install.sh
Kind failed to create a cluster with 
```
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-worker4 cat /kind/version" fa
iled with error: exit status 1
Output:
Error response from daemon: Container 46030848638d5695df3b1184d77fcb8502a1241548d2e9e8108201da6a3e11e7 is not running
Stack Trace:
sigs.k8s.io/kind/pkg/errors.WithStack
/src/pkg/errors/errors.go:51
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
/src/pkg/exec/local.go:116
sigs.k8s.io/kind/pkg/cluster/internal/providers/docker.(*nodeCmd).Run
/src/pkg/cluster/internal/providers/docker/node.go:130
sigs.k8s.io/kind/pkg/exec.CombinedOutputLines
/src/pkg/exec/helpers.go:67 …
```
> Reduce the number of kind nodes to 3

- Makefile
#299 
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
> Fix test with proxy

- helm/chaos-mesh/templates/bpfki-daemonset.yaml
- helm/chaos-mesh/values.yaml
diable bpfki by default
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Disable bpfki by default 

- controllers/podchaos/podfailure/types.go
Fix #189 
The `pause` image will always fail to start. 
Tests 
Code changes
Side effects
- No
```release-note
Use the `pause` image to inject pod-failure chaos
```
> Use the `pause` image to inject pod-failure chaos

- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/values.yaml
In some Kubernetes configuration chaos-daemon DaemonSet default behaviour is not allowed to create pod on each kubernetes node.
Being able to use tolerations for chaos-daemon in chart values.yaml.
```release-note
Allow users to configure tolerations for chaos-daemon.
```
> Edit chaos-daemon DaemonSet to allow Tolerations

- Makefile
- go.sum
Lock tools version in Makefile. Upgrade `controller-gen ` from `0.2.5` to `0.2.6` is destructive! (related [PR](https://github.com/kubernetes-sigs/controller-tools/pull/411))
> lock tools version in Makefile

- examples/chaosfs-configmap/pd-configmap.yaml
The example yaml has a wrong volume name
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Fix a wrong pd iochaos example

- .github/workflows/stale.yml
add [stale](https://github.com/actions/stale) github action to close stale issues/prs 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Add stale github action to close stale issues/prs

- api/v1alpha1/iochaos_webhook_test.go
- api/v1alpha1/kernelchaos_webhook_test.go
- api/v1alpha1/networkchaos_webhook_test.go
- api/v1alpha1/timechaos_webhook_test.go
- doc/deploy.md
- helm/chaos-mesh/README.md
- helm/chaos-mesh/values.yaml
Fix typo for Unit test
Update doc for helm
Tests 
- Unit test
Code changes
Side effects
```release-note
NONE
```
> Fix typo and update doc

- hack/kind-cluster-build.sh
- helm/chaos-mesh/templates/post-install-create-cert-job.yaml
- helm/chaos-mesh/templates/webhook-configuration.yaml
Fix #352  
* Add some debug log when to create certs 
* Add default value for  `caBundle` field, because we add Validator  and this field was marked as a required field in v1.12.8 Kubernetes  
* Update some default value in kind-create-cluster.sh 
Tests 
Code changes
Side effects
```release-note
NONE
```
> Add default value for `caBundle` field

- helm/chaos-mesh/templates/webhook-configuration.yaml
This configuration file for webhooks only plays well with cert-manager. User should use
post-install-webhook-job.yaml in no cert-manager env.
fix #358
Tests 
Manual test detail:
1. Deploy chaos-mesh on kind without cert-manager
1. Create a PodChaos object
1. Update the PodChaos object just created.
1. PodChaos object updated. Invoking admission webhook correctly. No any error log reported.
Code changes
- Has Helm configuration template change
Side effects
- No side effects.
- No related changes.
```release-note
NONE
```
> fix(helm): ignore entire webhook-configuration if certManager not enabled

- Makefile
Errors running `make install` when helm version 3 is installed
Add support for helm 3
Tests
- Manual test
`make install`
```release-note
NONE
```
> Support helm3 in `make install`

- api/v1alpha1/networkchaos_types.go
- config/crd/bases/pingcap.com_networkchaos.yaml
- controllers/networkchaos/netem/types.go
- controllers/networkchaos/netem/types_test.go
- controllers/networkchaos/types.go
- controllers/networkchaos_controller_test.go
- controllers/twophase/types.go
- examples/network-netem-example.yaml
- manifests/crd.yaml
- pkg/chaosdaemon/util.go
- pkg/utils/chaosdaemon.go
- pkg/utils/chaosdaemon_test.go
UCP #345 
Fix #345 
Add a new action called `netem` for networkchaos, when provided, the controller will merge all individual specs (delay, loss etc.) into one `Netem` RPC request.
Tests 
Code changes
Side effects
```release-note
Add netem as new network chaos action. It supports applying delay, loss etc. at same time.
```
> netm: Add Netem as new action for applying delay, loss etc. at same time

- api/v1alpha1/networkchaos_types.go
- api/v1alpha1/networkchaos_webhook.go
- api/v1alpha1/networkchaos_webhook_test.go
- config/crd/bases/pingcap.com_networkchaos.yaml
- doc/network_chaos.md
- manifests/crd.yaml
UCP #292 
#292 
Tests 
- Unit test
Code changes
Side effects
- 
- 
```release-note
NONE
```
> Set default value for correlation and jitter of NetworkChaos

- images/chaos-dashboard/Dockerfile
#376 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Build dashboard-server-frontend in docker

- .dockerignore
- Makefile
failed to exec 'make image-chaos-scripts ' 
```
Step 6/7 : COPY --from=pingcap/binary /src/scripts/wait-fuse.sh /scripts/wait-fuse.sh
COPY failed: stat /var/lib/docker/overlay2/2e42d7a975f8a02143a155d2a6214bf37ae142197651601117ac76668787f917/merged/src/scripts/wait-fuse.sh: no such file or directory
```
remove scripts directory from `.dockerignore` file 
Tests 
Code changes
Side effects
```release-note
NONE
```
> remove scripts directory from `.dockerignore` file

- controllers/timechaos/types.go
Fix warning during the tests 
```
/Users/vincent.huang/Go/bin/revive -formatter friendly -config revive.toml $(go list ./... | grep -vE "pkg/client" | grep -vE "zz_generated" | grep -vE "vendor")
⚠  https://revive.run/r#confusing-results  unnamed results of the same type may be confusing, consider using named results
/Users/vincent.huang/Workspace/pingcap/chaos-mesh/controllers/timechaos/types.go:307:1
⚠ 1 problem (0 errors, 1 warning)
Warnings:
1  confusing-results
```
add named results
Tests 
- Unit test
Code changes
Side effects
n/a
```release-note
NONE
```
> fix test unnamed results of the same type may be confusing warning

- images/grafana/Dockerfile
Set the concrete version of grafana image.
Use 6.7.1 grafana image. The good news is that both Prometheus and MySQL Datasource supports region annotations now.
This will also fix master CI build fail (because of the wrong architecture image) (by pulling a new image).
> Set version of grafana image

- Makefile
- images/chaos-kernel/Dockerfile
Fix #392 
Another change is to use official ubuntu mirror default (rather than aliyun mirror). The source address can be controled by environment variable `UBUNTU_MIRROR`.
Tests 
- Manual test
> Dynamically get kitware asc key

- images/chaos-kernel/Dockerfile
Makefile will pass empty MIRROR into Dockerfile, and this will override the default settings for ARG MIRROR.
Tests 
- Manual test
Code changes
> Set mirrors only if not empty

- pkg/chaosfs/server_test.go
`randomErrno` is  pseudo random function. It could be the same thing both times. Sometimes jenkins may report an error.
Tests 
- Unit test
Code changes
Side effects
- None
- None
```release-note
NONE
```
> Fix: chaosfs pseudo random errno UT

- helm/chaos-mesh/templates/controller-manager-rbac.yaml
Fix #401 
Add 
```
- apiGroups: ["certificates.k8s.io"]
resources:
- "signers"
resourceNames:
- "kubernetes.io/legacy-unknown"
verbs: ["approve"]
```
to clusterRole.
Tests 
- Manual test
Has tested with 1.18 and 1.14.8. `chaos-mesh` can be installed normally now.
> Add permission to approve certificate on kubernetes 1.18

- test/e2e/chaos/basic.go
> Add e2e case pause pod failure

- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/templates/collector-mysql.yaml
- helm/chaos-mesh/templates/collector-rbac.yaml
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- helm/chaos-mesh/templates/controller-manager-service.yaml
- helm/chaos-mesh/templates/dashboard-deployment.yaml
- helm/chaos-mesh/templates/post-install-create-cert-job.yaml
- helm/chaos-mesh/templates/post-install-webhook-job.yaml
- helm/chaos-mesh/templates/pre-delete-job.yaml
- helm/chaos-mesh/templates/prometheus-configmap.yaml
- helm/chaos-mesh/templates/prometheus-deployment.yaml
- helm/chaos-mesh/templates/prometheus-rbac.yaml
- helm/chaos-mesh/templates/prometheus-service.yaml
Some (not all) helm charts were missing namespace values. These are
essential for applying templates after rendering them.
https://github.com/helm/helm/issues/5465#issuecomment-541358344
Signed-off-by: Robert Collins <robert.collins@cognite.com>
(Some) rendered (helm template) templates don't have namespaces.
Added the namespace to namespace objects where missing.
Tests 
- E2E test
Code changes
Side effects
```release-note
NONE
```
> Add missing namespaces to helm templates

- controllers/common/config.go
- controllers/kernelchaos/types.go
- controllers/networkchaos/ipset/ipset.go
- controllers/networkchaos/iptable/iptable.go
- controllers/networkchaos/netem/types.go
- controllers/networkchaos/tbf/types.go
- controllers/networkchaos/tc/tc.go
- controllers/podchaos/containerkill/types.go
- controllers/stresschaos/types.go
- controllers/timechaos/types.go
Use a global var to keep the ports we need, so don't need to call `os.GetEnv` too many times
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Use a global config to keep daemon ports

- controllers/kernelchaos/types.go
- controllers/networkchaos/partition/types.go
- controllers/networkchaos/tbf/types.go
- controllers/podchaos/podfailure/types.go
- controllers/stresschaos/types.go
- controllers/timechaos/types.go
#227 
Force clean finalizer
Tests
- Manual test (see `examples/clean-finalizer`)
Code changes
```release-note
Add support to force clean finalizer with annotation in various chaos types
```
> Support force clean finalizer in various chaos types

- Makefile
- hack/update_install_script.sh
- install.sh
Use `helm template` instead of  `--dry-run` to update `install.sh`, So we can run `make update-install-script`  without the Kubernetes cluster environment.
> use `helm template` instead of `--dry-run`

- test/e2e/e2e_test.go
This flag is used for cleanup all namespaces expect the system ns such as `kube-system`, `kube-public`, etc.
Though this is useful, it is quite dangerous and error-prone. Especially in the case that you need to use different context to switch between the local e2e k8s and other k8s clusters...
> Remove set clean start to true

- Makefile
- hack/genproto.sh
Add a script to generate go code from proto files.
We can easily run it via `make proto`
> Add a script to generate go code from proto files

- pkg/apiserver/common/common.go
- pkg/apiserver/experiment/experiment.go
- pkg/apivalidator/base_validator.go
- pkg/apivalidator/scope_validator.go
- pkg/utils/selector.go
- pkg/utils/selector_test.go
This PR updates the list pods interface to `POST` in order to keep the Selector field.
> Support pods filtering by selectors

- pkg/apiserver/experiment/experiment.go
fix: 
```
12:20:27  2020/05/30 04:20:26 Generate general API Info, search dir:./
12:20:27  [0m[91m2020/05/30 04:20:27 ParseComment error in file pkg/apiserver/experiment/experiment.go :can not parse response comment "200 ExperimentInfo"
```
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> fix swagger api

- pkg/apiserver/experiment/experiment.go
Inject a network delay by API, an error was returned:
set spec.Bandwidth and spec.Direction only when the action is bandwidth
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> set spec.Bandwidth and spec.Direction only when the action is bandwidth

- Makefile
- go.mod
- go.sum
- hack/embed_ui_assets.sh
- pkg/apiserver/server.go
- pkg/uiserver/empty_asserts_handler.go
- pkg/uiserver/server.go
- tools/assets_generate/main.go
We use single page applications and the URL will be modified by front-end, so some url can't be accessed, such as: 
* Migrate from go-bindata to vfsgen
* Add `ServeError` function to redirect `index.html`
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> fix ui not found

- pkg/apiserver/experiment/experiment.go
- pkg/utils/selector.go
Support to set pods directly, so we can don't need to fill other selectors and just select the specific pods by clicking on the front-end. 
This pr can meet some cases, such as some pods don't have any labels for selectors. 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Support to select pods directly when to create a new experiment

- controllers/metrics/metrics.go
- pkg/webhook/config/watcher/watcher.go
Fix #589 
The root cause of #589 is that when the template is wrong, like the `conf.template` is not set, then the code below will cause a panic
```
c.metrics.TemplateLoadError.WithLabelValues(conf.Namespace, conf.Template, conf.Name).Inc()
```
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Fix panic when incrementing metric

- .github/workflows/ci.yml
- Dockerfile
Bump golang to 1.14, which contains many improvements compared to 1.13.
Highlights: https://blog.golang.org/go1.14
> chore: Bump golang version to latest

- pkg/apiserver/common/common.go
add common/labels
add common/labels
Tests
- No code
Code changes
Side effects
- NO
- NO
```release-note
NONE
```
> [add] common/labels

- website/docs/installation/get_started_on_kind.md
- website/docs/installation/get_started_on_minikube.md
- website/docs/installation/installation.md
- website/src/pages/index.js
When I try to install chaos mesh with kind by https://chaos-mesh.org/docs/installation/get_started_on_kind#install-chaos-mesh, then I run into this error:
```
sh: 381: Syntax error: Bad for loop variable
```
After rechecking the `install.sh`, I think this command should use `bash`.
> docs: should use bash

- go.mod
- go.sum
- pkg/uiserver/server.go
- tools/assets_generate/main.go
* use `index.html` as the fallback page
> api-server: add the fallback page

- go.mod
- pkg/apiserver/common/common.go
add api/common/annotations and update api/common/labels
add api/common/annotations and update api/common/labels
Tests
- No code
Code changes
Side effects
- NO
- NO
```release-note
NONE
```
> [add] add api/common/annotations and update api/common/labels

- pkg/store/event/event.go
Fix #649  
```
E0624 16:21:19.119160       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 181 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1880780, 0x2afd530)
/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1880780, 0x2afd530)
/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/pingcap/chaos-mesh/pkg/store/event.(*eventStore).DeleteByFinishTime(0xc00019c908, 0x1e73fc0, 0xc000046028, 0x2260ff9290000, 0x0, 0x0) …
```
> fix chaos-dashboard panic

- website/docs/user_guides/sidecar_configmap.md
In user_guides/sidecar_configmap.md, change `IOCChaos` to `IOChaos`.
In user_guides/sidecar_configmap.md, change `IOCChaos` to `IOChaos`.
> Document: modify IOCChaos to IOChaos

- CONTRIBUTING.md
- README.md
- Update descriptions and Slack channel link in`README.md`
- Fix the list format that causes a display error (step number and indentation) in `CONTRIBUTING.md`
- Make wording style consistent
Update wording and format
Tests
- No code
```release-note
NONE
```
> Update description, link, and fix format

- helm/chaos-mesh/values.yaml
- images/chaos-daemon/Dockerfile
- pkg/chaosdaemon/ipset_server.go
- pkg/chaosdaemon/iptables_server.go
- pkg/chaosdaemon/netlink_linux.go
- pkg/chaosdaemon/stress_server_linux.go
- pkg/chaosdaemon/tc_linux.go
- pkg/chaosdaemon/util.go
With this PR, users can see stress-ng process in corresponding pod. This PR also uses a util-linux version of nsenter rather than busybox's one. The util-linux's nsenter is more stable and seems to have less bugs.
Tests
- Manual test
Code changes
```release-note
NONE
```
> Add stress-ng to target pid namespace

- controllers/networkchaos/netutils/cidr.go
Fix #692 
Return all results from dns lookup in `ResolveCidr`
Tests
- Manual test
Code changes
> NetworkChaos on all address of DNS lookup result

- website/docs/user_guides/io_chaos.md
fix documents - user_guides/io_chaos.md
link has change to https://chaos-mesh.org/docs/user_guides/sidecar_template/#tips
but not https://github.com/chaos-mesh/chaos-mesh/blob/master/doc/sidecar_configmap.md#tips, this link has no longer accessable.
> fix io_chaos.md doc link url

- pkg/chaosdaemon/server.go
It's a bug that lead to goroutine leak if an error return before `g.Wait()`
Move the `g.Go()` code to right postion.
Tests
- No code
Code changes
```release-note
NONE
```
> chaosdaemon: fix the bug of goroutine leak.

- hack/version.sh
- pkg/version/types.go
- pkg/version/version.go
At present, we use `chart-*` tag to release chart file, so we remove the `semver.org` checker and `GitTreeState`
> Fix version script

- ui/src/components/EventsTable/index.tsx
- ui/src/lib/search.ts
- ui/src/pages/ExperimentDetail/index.tsx
As the title. This PR supports filter events by pod name.
> chore: support filter events by pod name

- ui/src/components/NewExperiment/Stepper/Target/Stress.tsx
- ui/src/components/NewExperiment/types.ts
- ui/src/lib/hooks.ts
This PR will remove another unused stressor(CPU or Memory) when the user selects a single action(not Mixed).
If without this operation, the create `StressChaos` API will always complain that another stressor is empty.
> fix: remove unused stressor in StressChaos

- api/v1alpha1/stresschaos_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/chaos-mesh.org_stresschaos.yaml
- controllers/stresschaos/types.go
- manifests/crd.yaml
Fix #755 
Support container wise injection and run stress-ng in container's cgroup in default. 
Tests
- Manual test
Code changes
> Support container-wise StressChaos injection

- ui/src/api/events.type.ts
- ui/src/components/AffectedPods/index.tsx
- ui/src/components/EventsTable/index.tsx
- ui/src/components/ExperimentPaper/index.tsx
- ui/src/lib/d3/eventsChart.ts
- ui/src/pages/ArchiveReport/index.tsx
- ui/src/pages/Events/index.tsx
- ui/src/pages/ExperimentDetail/index.tsx
- ui/src/pages/Experiments/index.tsx
This PR fixes some minor problems, includes:
- Unique affected pods in the archives page
- Remove limit param in `EventsPreview` to prevent the latest event not found
- Add relative time in the archive item list
Patch fe425c2:
Refactor the `EventDetail` to let all `EventsTable` parents can be access the `onSelectEvent` function.
> fix: some minor problems

- ui/src/components/FormField/AutocompleteMultipleField.tsx
- ui/src/components/NewExperiment/Stepper/Scope.tsx
- ui/src/components/NewExperiment/Stepper/ScopePodsTable.tsx
- ui/src/lib/utils.ts
- ui/src/slices/experiments.ts
This PR changes the pods' table in `NewExperiment Scope`. From now it will not override selectors arbitrarily.
We want it to act as a preview area. As **Namespaces**, **Label Selectors**... change, it will also be updated synchronously. In default, all pods will be selected if you only change the selectors. Uncheck some pods will limit the scope to specified pods.
Also, the **Pods Preview** will limit you to select at least one pod. If not, the experiment scope will be meaningless.
> fix: correct the usage of pods preview

- controllers/podchaos/containerkill/types.go
- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/values.yaml
- install.sh
- pkg/utils/grpc.go
grpc client timeout was set to a very large value, so that it impossible to get a timeout. For example, the rpc call has hung above 8 minutes:
```
goroutine 611 [select, 8 minutes]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc001e02f00)
/go/pkg/mod/google.golang.org/grpc@v1.26.0/internal/transport/transport.go:318 +0xcc
google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
/go/pkg/mod/google.golang.org/grpc@v1.26.0/internal/transport/transport.go:333
google.golang.org/grpc.(*csAttempt).recvMsg(0xc001b7d000, 0x15efc00, 0xc001e29620, 0x0, 0x5, 0xc0005ff1d0)
/go/pkg/mod/google.golang.org/grpc@v1.26.0/stream.go:871 +0x753
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc001b7d000, 0x4d, 0x4d) …
```
> fix grpc timeout

- pkg/apiserver/experiment/experiment.go
- pkg/core/archive_experiment.go
- ui/src/components/NewExperiment/Stepper/Target/Stress.tsx
- ui/src/components/NewExperiment/constants.ts
- ui/src/components/NewExperiment/types.ts
After #759 merged, the container name was added to the StressChaos.
This PR adds container name to the dashboard
add container-wise StressChaos in dashboard
Tests
- No code
Code changes
Side effects
- NO
- NO
```release-note
NONE
```
> [update] add container-wise StressChaos in dashboard

- website/blog/2020-08-14-building_automated_testing_framework.md
Signed-off-by: Calvin Weng <wenghao@pingcap.com>
Tests
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add truncate

- .editorconfig
When I view the `*.go` files, due to I have to switch between multiple languages(.go, .js, .ts), it's hard to change the indention automatically.
But the `editorconfig` can solve my problem, so I open this PR. It can connect with `gofmt` seamlessly and the two sides do n't affect each other.
Add `.editorconfig` to make `*.go` with tab width `8`.
Tests
Side effects
```release-note
NONE
```
> style: add .editorconfig for *.go

- install.sh
`"$(kubectl get pods -n "${namespace}" ${labels} -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}')" != "True"` only check one pod. When we use this way to check `chaos-daemon`, this script didn't work.
Tests
Side effects
```release-note
NONE
```
> Fix: ensure pods ready when installing Chaos Mesh by `install.sh`

- pkg/chaosdaemon/tc_server.go
- pkg/chaosdaemon/tc_server_test.go
```
2020-09-02T03:47:24.659Z        INFO    chaos-daemon-server     build command   {"command": "nsenter -n/proc/20669/ns/net -- tc qdisc add dev eth0 parent 1: handle 2: netem  duplicate 80.000000 25.000000"}
2020-09-02T03:47:24.685Z        ERROR   chaos-daemon-server     error while adding tc   {"error": "error code: exit status 1, msg: Illegal \"limit\"\n"}
```
There is an extra space between "netem" and "duplicate" (which will lead to an "" in args).
BTW: What is the best practice of concating command line arguments? Directly working on a `[]string` seems too complicated (as I will need to convert integer/float to string everywhere).
Tests
> Fix the error in building tc commands

- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/values.yaml
In our helm chart, the controller-manager didn't support `hostNetwork=true`, and for me, it's quite need, so I proposed this PR.
Updated the `controller-manager-deployment.yaml` and add hostNetwork option support, by default, it's false, so there is nothing changed if we're keep using the original values.
```release-note
NONE
```
> feat: add hostNetwork option for controller-manager and update doc accordingly

- ui/src/components/NewExperiment/Stepper/Scope.tsx
This PR fixes the selectors problem in `new experiments scope`. Now the select fields will pass correct selectors in request params.
Tests
Side effects
```release-note
NONE
```
> fix: scope selectors

- website/src/components/PickVersion.jsx
As the title.
Tests
Side effects
```release-note
NONE
```
> fix: doc versions

- pkg/ptrace/ptrace_linux.go
Run timechaos with `GODEBUG=cgocheck=2` will give you the detail of the error (and will actually cause GC error in the runtime). In this PR, I minimize the cgo related codes and use `syscall.Syscall6` as a wrapper to call system call.
> Fix invalid usage of cgo/unsafe pointer in TimeChaos

- cmd/controller-manager/main.go
- pkg/webhook/config/watcher/watcher.go
Fixed #910 
Changed the restart watcher log level, so we don't see such duplicate logs inside controller-manager anymore..
Tests
Side effects
```release-note
NONE
```
> fix: make restart watcher log level down to info.

- controllers/networkchaos/partition/types.go
- controllers/networkchaos/podnetworkmanager/podnetworkmanager.go
- controllers/networkchaos/trafficcontrol/types.go
- controllers/twophase/types.go
Fixed #944 , addressed by [the issue comment](https://github.com/chaos-mesh/chaos-mesh/issues/944#issuecomment-697242197).
If networkchaos is Failed phase, it may need retry apply, and this PR help it come true!
Tests
Side effects
No
```release-note
NONE
```
> fix: pod deletion caused twophase phase=Failed chaos.

- controllers/iochaos/types.go
Add pod status to iochaos event, so that we can see the detail in the dashboard
Tests
> add pod status to iochaos event

- hack/update_install_script.sh
- install.sh
Add a flag `-v` to control the version of Chaos Mesh in `install.sh`. 
```bash
install.sh -v v0.9.1
```
Tests
Side effects
```release-note
NONE
```
> Add a flag to control the version of Chaos Mesh in install.sh

- website/docs/installation/get_started_on_kind.md
- website/docs/installation/get_started_on_minikube.md
- website/docs/installation/installation.md
- website/versioned_docs/version-0.9.0/installation/get_started_on_kind.md
- website/versioned_docs/version-0.9.0/installation/get_started_on_minikube.md
- website/versioned_docs/version-0.9.0/installation/installation.md
- website/versioned_docs/version-0.9.1/installation/get_started_on_kind.md
- website/versioned_docs/version-0.9.1/installation/get_started_on_minikube.md
- website/versioned_docs/version-0.9.1/installation/installation.md
- website/versioned_docs/version-1.0.0/installation/get_started_on_kind.md
- website/versioned_docs/version-1.0.0/installation/get_started_on_minikube.md
- website/versioned_docs/version-1.0.0/installation/installation.md
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
fix #980 
On the website, three daemons are shown running, while actually there is only one.
Make test on v1.0.0 and v0.9.1, both the same. Since the change from v0.9.0 to v0.9.1 is not related to the duplication of chaos-daemons, I also modify doc of v0.9.0, plz correct me if I'm wrong.
Tests
```release-note
NONE
```
> fix website: only one daemon is created by default

- hack/update_install_script.sh
- install.sh
Fix #831
Adds timezone variable in install.sh
Tests
```
hack/update_install_script.sh
./install.sh --timezone "IST"
```
Side effects
```
Users can now add timezone for chaos-dashboard, chaos-daemon, and chaos-controller.
```
> add timezone variable in install.sh

- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- helm/chaos-mesh/templates/prometheus-rbac.yaml
- install.sh
- manifests/tiller-rbac.yaml
Signed-off-by: vincent178 <vh7157@gmail.com>
https://github.com/chaos-mesh/chaos-mesh/issues/993
replace deprecated rbac api group `rbac.authorization.k8s.io/v1alpha1` and `rbac.authorization.k8s.io/v1beta1` with `rbac.authorization.k8s.io/v1`
Tests
Side effects
```release-note
NONE
```
> fix: remove rbac deprecation

- helm/chaos-mesh/templates/ingress.yaml
Fixes #992 
The ingress of the helm-chart is now referring to the correct service
Tests
1. install the helm chart with ingress & dashboard support (`--set dashboard.create=true --set dashboard.ingress.enabled=true`)
3. access the ingress via browser
4. the dashboard shall show up
> ingress uses correct serviceName now

- .github/workflows/checklink_config.json
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
fix #998 
It seems both new filters in #999 failed.
I'm thinking to use this to filter out what we don't need:
```
{
"ignorePatterns": [
{
"pattern": ["^/img/"]
},
{
"pattern": ["^http://localhost"]
},
{
"pattern": ["^https://github.com"]
}
]
}
```
The first two are acceptable, but with the third one we'll definitely over-filter some broken links of github to avoid 429 error.
The good news is I made tests that most of github links work well, but still I don't know if that would be acceptable.
_Originally posted by @Yiyiyimu in https://github.com/chaos-mesh/chaos-mesh/issues/998#issuecomment-701154563_
Tests
```release-note
NONE
```
> bugfix: [link-checker] ignore all links of github and some others

- README.md
The current Codecov Badge is showing Unknown instead of the Code coverage Percentage. The Link below shows invalid Github API.
https://codecov.io/gh/pingcap/chaos-mesh/branch/master
I have updated the link to https://codecov.io/gh/chaos-mesh/chaos-mesh/branch/master to show the real-time code coverage percentage in the badge in Readme.
Tests
Side effects
```release-note
NONE
```
> Codecov Badge Updated

- website/docusaurus.config.js
fix: footer get started link target issue
Invalid footer link.
It changed the docusaurus.config.js footer section of links, which correct the link.
Tests
```release-note
NONE
```
> fix: footer get started link address

- .github/workflows/checklink.yaml
- .github/workflows/checklink_config.json
- website/docs/use_cases/multi_data_centers.md
- website/versioned_docs/version-0.9.1/use_cases/multi_data_centers.md
- website/versioned_docs/version-0.9.1/user_guides/sidecar_configmap.md
- website/versioned_docs/version-0.9.1/user_guides/sidecar_template.md
- website/versioned_docs/version-1.0.0/use_cases/multi_data_centers.md
the complement of #1013 
Need to use absolute path of config file.. 
Since the feature `retryon429` is [still not released](https://github.com/tcort/markdown-link-check/issues/114#issuecomment-705516265), currently ignore all github links.
Tests
Passed the test in [personal repo](https://github.com/Yiyiyimu/CheckLinkTmp/runs/1240937823?check_suite_focus=true)
```release-note
NONE
```
> bugfix: fix config path of check-link & fix broken links

- README.md
Signed-off-by: colstuwjx <colstuwjx@gmail.com>
Fixed #1067 .
I've been checked the PR history, this issue was introduced by PR #1010 , and the docs has been reconstituted since PR #924 . I wonder the root cause should be #885 , since we're **NOT** showing the latest document in our website, our users may misunderstand the content.
As a result, I suggest we push for fixing #885, make it "I could see what has changed in website immediately". A good example should be [k/website](https://github.com/kubernetes/website), see its [netlify config](https://github.com/kubernetes/website/blob/master/netlify.toml), and it always show the latest content on [its website](https://kubernetes.io/), just "I could see what has changed in website immediately".
Tests
Side effects …
> fix: correct the broken links for get started doc.

- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- install.sh
- pkg/apiserver/common/common.go
- pkg/apiserver/experiment/experiment.go
- pkg/collector/server.go
- pkg/config/dashboard.go
- ui/src/api/common.ts
- ui/src/slices/experiments.ts
- ui/src/store.ts
Fix  https://github.com/chaos-mesh/chaos-mesh/issues/1107, chaos-dashboard is uncompliable  with namespace scoped mode.
- Add ENV to chaos-dashboard in helm deployment yaml.
- Adding new options while creating `Manager`, only watching ONE specific namespace.
- Change some `List` action while user query something from k8s api(detail in Side effects).
> appending at 2020-10-29
- change `/api/common/namespace` to `/api/common/chaos-available-namespaces`, means only return namespaces which could inject chaos (chaos experiment explosion scope)
- remove permission about `list` on `namespaces` with namespace scoped mode
Tests
Side effects
It changes `/api/experiments` behavior under namespace scoped mode: origin parameter `namespace` will be replaced by `targetNamespace`. …
> make chaos dashboard be compliable with namespace scoped mode

- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- install.sh
- pkg/apiserver/common/common.go
- pkg/apiserver/experiment/experiment.go
- pkg/collector/server.go
- pkg/config/dashboard.go
- ui/src/api/common.ts
- ui/src/slices/experiments.ts
- ui/src/store.ts
Since #1127  has conflict, manually cherry-pick  https://github.com/chaos-mesh/chaos-mesh/pull/1110 to release-1.0.
Here are duplicated code in `pkg/apiserver/experiment/experiment.go` like:
```golang
type Service struct {
conf    *config.ChaosDashboardConfig
kubeCli client.Client
archive core.ExperimentStore
event   core.EventStore
conf    *config.ChaosDashboardConfig
}
```
`conf    *config.ChaosDashboardConfig` is duplicated.
Already cleanup manually.
> (Manually cherry-pick) make chaos dashboard be compliable with namespace scoped mode (#1110) 

- pkg/fusedev/fusedev_linux.go
Existing `scanner.Err()` won't be called and this will cause errors to be missed.
> Scan advances the Scanner to the next token, which will then be available through the Bytes or Text method. It returns false when the scan stops, either by reaching the end of the input or an error. **After Scan returns false, the Err method will return any error that occurred during scanning, except that if it was io.EOF, Err will return nil**. Scan panics if the split function returns too many empty tokens without advancing the input. This is a common error mode for scanners.
Move `scanner.Err()` after for loop block.
Before
```go
for scanner.Scan() {
...
scanner.Err()
...
}
```
After
```go
for scanner.Scan() {
...
}
scanner.Err()
```
Tests
> The standard library has instructions that adding anomaly path …
> pkg/fusedev: fix the call order.

- pkg/apiserver/experiment/experiment.go
Now the "total" field is useless (and the front end can get "total" from other fields).
However, the existence of the "total" field will affect the front-end type detection, so remove it.
remove "total" field in experiments/state
Tests
Side effects
```release-note
NONE
```
> [update] remove "total" field in experiments/state

- cmd/controller-manager/main.go
```go
import (
"github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
chaosmeshv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
)
```
The import of `v1alpha1` is duplicated.
Just keep one.
Tests
Side effects
```release-note
NONE
```
> cmd/controller-manager: Fix duplicate package names.

- pkg/apiserver/experiment/experiment.go
- pkg/core/experiment.go
- ui/src/components/NewExperimentNext/data/target.tsx
- ui/src/components/NewExperimentNext/form/TargetGenerated.tsx
As the title.
Also, fix some bugs related to `direction` and `bandwidth`, PTAL.
Tests
Side effects
```release-note
NONE
```
> chore: add networkchaos external targets in dashboard

- ui/src/components/NewExperimentNext/form/Scope.tsx
As the title. Now can fetch pods after namespaces selector changed.
Tests
Side effects
```release-note
NONE
```
> fix: fetch pods after namespaces changed

- pkg/chaosdaemon/stress_server_linux.go
- pkg/chaosdaemon/util.go
- pkg/fusedev/fusedev_linux.go
- test/pkg/timer/timer.go
There are two types of bugs, both about io
* Close `os.File` after use.
* `bufio.Scanner` Error Location
* call `f.Close()`
* move the `Scanner.Err()` after for loop block.
Tests
Side effects
```release-note
NONE
```
> Fix some bugs about io.

- ci/pingcap_chaos_mesh_build_kind.groovy
Modify the e2e test base image to bypass the docker pull limit.
However, we should enable cache for e2e test 😿 , which is the correct way to solve it.
This image was built with:
```
FROM gcr.io/k8s-testimages/kubekins-e2e:v20200311-1e25827-master
RUN echo "DOCKER_OPTS=\"\${DOCKER_OPTS} --registry-mirror=\"https://registry-mirror.pingcap.net\"\"" | \
tee --append /etc/default/docker
```
> Use a modified image to run e2e test

- ui/src/components/NewExperiment/constants.ts
- ui/src/lib/formikhelpers.ts
In v1.0.x dashboard, because creating experiments use the entire experiment schema as a request body, it's necessary to parse the `attr` property even creating `io latency` or `io fault`.
Now can create `io latency` and `io fault` normally.
Tests
Side effects
```release-note
NONE
```
> fix: always parse attr when creating IOChaos

- cmd/controller-manager/main.go
- controllers/podnetworkchaos/types.go
- controllers/podnetworkchaos/types_test.go
- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/values.yaml
- install.sh
- pkg/config/controller.go
Signed-off-by: svanellewee <stephan.van.ellewee@gmail.com>
This brings back the ability to optionally run chaos testing on pods with `hostNetwork` set to `true`. I realize this is a dangerous option, but our tests depend on this functionality 
We migrated our chaos tests to `v1.0.0` that allowed this, but it seems after v1.0.1 this is no longer allowed.  This is not intended for use on production clusters.
This adds an environment variable `ALLOW_HOST_NETWORK_TESTING` to the chaos controller manager. 
When this is enabled (set to "true") it will allow testing of networkchaos on weave-pods or whatever has `hostNetwork: true`
Tests
No unit tests have been created yet, but I will add them if you are happy with me re-adding this behaviour.
Manual test:
- Install a new kind cluster as per the …
> Option to run networkchaos tests on hostNetwork pods

- controllers/networkchaos/partition/types.go
- controllers/networkchaos/trafficcontrol/types.go
When I used networkchaos to test, the pod could not be filtered out due to wrong fields.
But at this time, I found an error message saying "failed to select and filter pods". I can't know whether the "source" or the "target" is wrong, so I think it is necessary to modify the error message.
Modify the error message about NetworkChaos.
Tests
Side effects
```release-note
NONE
```
> [update] Modify the error message about NetworkChaos

- ci/pingcap_chaos_mesh_build_kind.groovy
e2e tests failed by "docker pull rate limit" for release-1.0, so cherry-pick this PR to release-1.0
> Use a modified image to run e2e test (#1205)

- hack/run-e2e.sh
Bypass docker hub pull request rate limit.
Loading nginx:latest before installing chaos-mesh in e2e-tests, for avoiding docker pull rate limit. Similar to https://github.com/chaos-mesh/chaos-mesh/pull/1244
Tests
It passed manually e2e-test on my local machine.
Side effects
```release-note
NONE
```
> loading image nginx:latest while e2e tests

- pkg/utils/selector.go
As the title.
Missing the `append` operation in the foreach, add it to avoid only pods under last namespace was added.
Tests
Side effects
```release-note
NONE
```
> fix: missing append pods in foreach

- controllers/networkchaos/trafficcontrol/types_test.go
- controllers/podchaos/containerkill/containerkill_suite_test.go
- controllers/podchaos/podfailure/podfailure_suite_test.go
- controllers/podchaos/podkill/podkill_suite_test.go
- controllers/podnetworkchaos/types_test.go
- controllers/test/types.go
- controllers/timechaos/timechaos_suite_test.go
- pkg/utils/generate.go
- pkg/utils/selector_test.go
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
There are two `GenerateNPods` exists with little difference, so merge them together
https://github.com/chaos-mesh/chaos-mesh/blob/26fe5523a8ff9fdc3d934c43e5a0cd8ec50aec48/pkg/utils/selector_test.go#L592
https://github.com/chaos-mesh/chaos-mesh/blob/6afb841b02df35a03bbca84419e70cb95eb8c8e1/controllers/test/types.go#L128
Add a struct so don't need to type in the arguments not used in certain test.
Tests
Side effects
```release-note
NONE
```
> chore: remove duplicate 'GenerateNPods'

- hack/install.sh
- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/dns-deployment.yaml
- helm/chaos-mesh/templates/prometheus-deployment.yaml
- helm/chaos-mesh/values.yaml
- install.sh
Currently you cannot pass priorityClassName to set a pod priority on deployed pods/daemonsets. This allows you to specify a custom priorityClassName if desired.
added the field priorityClassName to the template spec for deployments/daemonset to allow custom values.
Tests
Side effects
```release-note
NONE
```
> HELM : Support priorityClassName

- controllers/twophase/twophase_suite_test.go
- controllers/twophase/types.go
- pkg/utils/scheduler.go
- test/e2e/chaos/basic.go
fix issue https://github.com/chaos-mesh/chaos-mesh/issues/1207
it is easy to meet this error when create a chaos test with "scheduler": {"cron":"*/1 * * * * "}, "duration": "50s"
https://github.com/chaos-mesh/chaos-mesh/pull/1221 is done a similar thing, but it is hard to cherry pick to release-1.0
when the chaos is the first time run, set the NextStart for it
Tests
Side effects
```release-note
NONE
```
> scheduler: fix error `nextRecover shouldn't be later than nextStart`

- helm/chaos-mesh/templates/chaos-daemon-rbac.yaml
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- helm/chaos-mesh/templates/dns-rbac.yaml
- helm/chaos-mesh/templates/prometheus-rbac.yaml
- install.sh
Upgrade helm to v3.4.2 and run `helm lint` 
```
helm lint helm/chaos-mesh
==> Linting helm/chaos-mesh
[ERROR] templates/controller-manager-rbac.yaml: object name does not conform to Kubernetes naming requirements: "test-release:chaos-controller-manager-target-namespace": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
[ERROR] templates/controller-manager-rbac.yaml: object name does not conform to Kubernetes naming requirements: "test-release:chaos-controller-manager-cluster-level": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
[ERROR] …
```
> fix invalid metadata name in helm chart files

- hack/version.sh
At present, we don't create git tags on the master branch, which makes gitVersion based on tags confuse users. 
```
-X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitVersion=v0.9.0-201+8d8dce88ff5371'
```
If the current git commit don't have any git tags, we use `branch+gitcommit` to generate `gitVersion`
```
-X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitVersion=master-ga7abd818a7b2d6
```
Tests
Side effects
```release-note
NONE
```
> improve gitVersion format

- hack/run-e2e.sh
```
Error: error initializing local helm home: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```
Modify stable repo to https://charts.helm.sh/stable
> modify stable repo for e2e helm

- cmd/controller-manager/main.go
```
// QPS indicates the maximum QPS to the master from this client.
// If it's zero, the created RESTClient will use DefaultQPS: 5
QPS float32
// Maximum burst for throttle.
// If it's zero, the created RESTClient will use DefaultBurst: 10.
Burst int
```
The default QPS and Burst values of client-go are relatively small, which is easy to trigger the current limiting situation
Tests
Side effects
```release-note
NONE
```
> add qps and burst flag for rest.Config

- hack/run-e2e.sh
Try to fix e2e test failed, which belongs to "type/1.0-cherry-pick", like #1346.
Tests
Side effects
```release-note
NONE
```
> cherry-pick-to-release-1.0: modify stable repo (#1315)

- images/chaos-daemon/Dockerfile
Fix the bug on [old version of kernel](https://github.com/chaos-mesh/chaos-mesh/issues/1357#issuecomment-755888909) . Now it gets stabler on CentOS, and the retry count is limited.
> upgrade toda to v0.1.11

- Dockerfile
cherry pick pr #1367 
Fix the bug on [old version of kernel](https://github.com/chaos-mesh/chaos-mesh/issues/1357#issuecomment-755888909) . Now it gets stabler on CentOS, and the retry count is limited.
> upgrade toda to v0.1.11 (#1367)

- pkg/apiserver/experiment/experiment.go
- pkg/collector/server.go
`Client.Get` gets empty GVK(Group/APIVersion/Kind). 
Use `schema` and object to get GVK
Tests
> Fix: client.Get gets empty GVK(Group/APIVersion/Kind)

- Makefile
```
/usr/local/bin # ./chaos-controller-manager -version
Controller manager Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", BuildDate:"2021-01-08T11:06:52Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```
Set `IMG_LDFLAGS` environment 
Tests
> Fix: fail to get gitVersion and gitCommit 

- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/values.yaml
Need to set nodeSelector to define which nodes can install chaos-daemon
Update helm charts 
Tests
set nodeSelector and helm upgrade:
> chaos-daemon: support setting node selector

- pkg/apiserver/experiment/experiment.go
Resolve #1380.
This PR prevents unexpected behaviors when creating `StressChaos`.
After changes, the `CPU` or `Memory` workers must be at least one bigger than zero.
Tests
Side effects
```release-note
NONE
```
> fix: missing stressors checking

- ui/src/components/NewExperimentNext/data/target.ts
- ui/src/components/NewExperimentNext/form/Scope.tsx
- ui/src/components/NewExperimentNext/form/TargetGenerated.tsx
- ui/src/slices/experiments.ts
This PR solves the pods' isolation problem between `normal scope pods` and `network target scope pods`.
Before these changes, when you get any scope pods, the others will sync at the same time. This is unexpected behavior.
Pods will not sync between scopes.
Tests
Side effects
```release-note
NONE
```
> fix: scope pods' isolation problem

- images/chaos-daemon/Dockerfile
Fix tons of the bugs. And [fstest](https://www.google.com.hk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi6meKgpZvuAhXkyYsBHU6gDGQQFjAAegQIARAC&url=https%3A%2F%2Fgithub.com%2Fzfsonlinux%2Ffstest&usg=AOvVaw2c4smykd_yJqm95V1t5Cj4) has been run on my host, and got the same test result with zfs (except support for the long path).
* Fix `rmdir` and `mknod` https://github.com/chaos-mesh/toda/commit/159174fd53c7f42bb6ffe0e6b25611464814153d .
* Fix wrong permission with `setuid` and `setgid` tag https://github.com/chaos-mesh/toda/commit/9778ea7aaac43f87f6d7b5aae4b3d447fed5ca6e .
* Fix error handling by running `Error::last` on the same thread of the system call.
> upgrade toda to v0.1.12

- helm/chaos-mesh/README.md
- helm/chaos-mesh/values.yaml
None
* Fix hierarchy of `nameOverride` and `fullnameOverride` parameters
* e.g. The reference to `nameOverride` value is here
https://github.com/chaos-mesh/chaos-mesh/blob/e8bc5db9b76cfdc4f5ee47c3f1fe20de7fa85557/helm/chaos-mesh/templates/_helpers.tpl#L5-L7
* Delete unused `kubectlImage` parameter
Tests
Side effects
```release-note
NONE
```
> Cleanup parameters in helm values file

- pkg/chaosctl/cmd/completion.go
- pkg/chaosctl/cmd/debug.go
- pkg/chaosctl/cmd/logs.go
- pkg/chaosctl/cmd/root.go
It's a part of #1397.
- cleanup unnecessary `func init(){}` from codes;
- initial kubernetes client only when context need it 
Tests
Side effects
```release-note
NONE
```
> chaosctl: cleanup init functions, avoid load kubernetes client before operate anything

- pkg/apiserver/archive/archive.go
- pkg/apiserver/event/event_test.go
- pkg/core/event.go
- pkg/store/event/event.go
- test/integration_test/dashboard_authority/run.sh
cherry-pick #1372 to release-1.1
When deleting archived experiments, delete the corresponding events and pod records.
Delete the corresponding events and pod records by experiment UID.
Tests
Side effects
```release-note
NONE
```
> [update] delete events by experiment UID (cherry-pick #1372)

- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/values.yaml
Signed-off-by: toVersus <toversus2357@gmail.com>
We would love to add some cloud provider specific annotations to helm templated manifests
e.g. https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#create_service
Adding helm parameter to annotate dashboard service:
Define no service annotations:
```bash
$ helm template chaos-mesh -n chaos-mesh --set dashboard.create=true .
---
apiVersion: v1
kind: Service
metadata:
namespace: chaos-mesh
name: chaos-dashboard
labels:
app.kubernetes.io/name: chaos-mesh
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/instance: chaos-mesh
app.kubernetes.io/component: chaos-dashboard
helm.sh/chart: chaos-mesh-v0.2.0
spec:
```
Define service annotations:
```bash
$ helm template chaos-mesh -n chaos-mesh --set …
```
> Add helm parameter to annotate dashboard service

- pkg/chaosdaemon/util.go
(I have forgotten to fix this bug for a long time :crying_cat_face:, sorry )
If the pid of a docker container is 0 (when the container is not running), an error will be returned.
> docker client return error if the pid is zero

- Makefile
As the `api/v1alpha1` is a standalone module now, it won't be detected and codes will not be generated until we `cd` into it :angry: 
Now `make yaml` and `make generate` would work well.
> fix yaml generate

- pkg/apiserver/common/common.go
users can choose the namespace/cluster and role(manager/viewer) in the dashboard, and then dashboard generates the rbac config.
```bash
curl -X GET "127.0.0.1:2333/api/common/rbac-config?role=viewer&namespace=busybox"  
```
`
{"account-busybox-viewer-ekjzo":"kind: ServiceAccount\napiVersion: v1\nmetadata:\n  namespace: busybox\n  name: account-busybox-viewer-ekjzo\n\n---\nkind: Role\napiVersion: rbac.authorization.k8s.io/v1\nmetadata:\n  namespace: busybox\n  name: role-busybox-viewer-ekjzo\nrules:\n- apiGroups: [\"\"]\n  resources: [\"pods\", \"namespaces\"]\n  verbs: [\"get\", \"watch\", \"list\"]\n- apiGroups:\n  - chaos-mesh.org\n  resources: [ \"*\" ]\n  verbs: [\"get\", \"list\", \"watch\"]\n\n---\napiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n  name: …
> dashboard: add HTTP API for getting rbac config

- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/templates/chaos-daemon-rbac.yaml
- helm/chaos-mesh/templates/chaos-daemon-service.yaml
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/templates/chaos-dashboard-pvc.yaml
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- helm/chaos-mesh/templates/controller-manager-service.yaml
- helm/chaos-mesh/templates/dns-configmap.yaml
- helm/chaos-mesh/templates/dns-deployment.yaml
- helm/chaos-mesh/templates/dns-rbac.yaml
- helm/chaos-mesh/templates/dns-service.yaml
- helm/chaos-mesh/templates/ingress.yaml
- helm/chaos-mesh/templates/prometheus-configmap.yaml
- helm/chaos-mesh/templates/prometheus-deployment.yaml
- helm/chaos-mesh/templates/prometheus-rbac.yaml
- helm/chaos-mesh/templates/prometheus-service.yaml
- helm/chaos-mesh/templates/webhook-configuration.yaml
- install.sh
fixes #1493
All used namespace vars are quoted to allow use number in namespace only
Tests
```release-note
NONE
```
> chore(helm): allow install to namespace with numbers only

- pkg/core/experiment.go
- ui/src/components/NewExperimentNext/data/target.ts
As the title.
Previous: #1454.
Tests
Side effects
```release-note
NONE
```
> chore: support dns patterns in UI

- test/e2e/chaos/basic.go
- test/e2e/chaos/networkchaos/network_peers_crossover.go
Appending e2e test cases for https://github.com/chaos-mesh/chaos-mesh/issues/1450
This test cases startup 4 pods which divided into 2 partition:
- partition 0: pods 0, 2
- partition 1: pods 1, 3
Then inject network delay between 2 partitions.
Then make assert about network delay **ONLY exists** in `{0, 1}, {0, 3}, {1, 2}, {2, 3}`.
Tests
Side effects
```release-note
NONE
```
> Appending e2e test cases for issue 1450

- api/v1alpha1/common_validation.go
- api/v1alpha1/iochaos_webhook_test.go
- controllers/twophase/types.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
- test/e2e/chaos/basic.go
- test/e2e/chaos/timechaos/time_skew.go
cherry-pick #286 to release-1.1
---
fix #1270
Add function `Last` to get the last start time of standard cron, so we could know the current phase that chaos should go into when start.
Tests
Side effects
```release-note
NONE
```
> Bugfix: Use `Last` to get current phase at start time of standard cron (#1286)

- config/webhook/manifests.yaml
- helm/chaos-mesh/templates/webhook-configuration.yaml
- helm/chaos-mesh/values.yaml
- install.sh
Allowing setting `timeoutSeconds` for webhooks. Right now we are using the default timeout which is quite high.
Default timeout for a webhook call is 30 seconds for webhooks created using admissionregistration.k8s.io/v1beta1. It is recommended that admission webhooks should evaluate as quickly as possible (typically in milliseconds), since they add to API request latency. It is encouraged to use a small timeout for webhooks.
If the webhook call times out, the request is handled according to the webhook's failure policy.
Refer: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts for more details.
Tests
Side effects
```release-note
NONE
```
> Adding parameterized timeoutSeconds for webhooks

- pkg/apiserver/handler.go
- pkg/apiserver/workflow/workflow.go
- pkg/core/workflow.go
Reference: #1521
This PR appends the models and controller for workflow HTTP API which communicates with the frontend.
Tests
It could generate the expected swagger file.
Side effects
```release-note
NONE
```
> models and controller of workflow http api

- api/v1alpha1/common_types.go
- api/v1alpha1/zz_generated.chaosmesh.go
- api/v1alpha1/zz_generated.chaosmesh_test.go
- cmd/chaos-builder/impl.go
- cmd/chaos-builder/test.go
- controllers/reconciler/types.go
- controllers/twophase/state_machine.go
- controllers/twophase/twophase_suite_test.go
- controllers/twophase/types.go
- pkg/router/reconciler.go
cherry-pick #1533 
Use `WithEventFilter` to filter update events and ignore updates to CRD object status.
To compare the spec and meta fields of the CRD object, we add a `GetSpecAndMetaString` function for each chaos CRD. If we update the CRD version to v1, we can delete `GetSpecAndMetaString` function, because we can use `unstructured.Unstructured` struct to parse CRD object directly.
Tests
Side effects
```release-note
NONE
```
> Fix meaningless retry operations caused by the updates of status field 

- .github/workflows/integration_test.yml
- .github/workflows/script_test.yml
- api/v1alpha1/common_types.go
- api/v1alpha1/common_webhook.go
- api/v1alpha1/dnschaos_webhook.go
- api/v1alpha1/httpchaos_webhook.go
- api/v1alpha1/iochaos_webhook.go
- api/v1alpha1/jvmchaos_types.go
- api/v1alpha1/jvmchaos_webhook.go
- api/v1alpha1/networkchaos_webhook.go
- api/v1alpha1/podchaos_webhook.go
- api/v1alpha1/podiochaos_types.go
- api/v1alpha1/podnetworkchaos_webhook.go
- api/v1alpha1/stresschaos_webhook.go
- api/v1alpha1/timechaos_webhook.go
- api/v1alpha1/zz_generated.chaosmesh.go
- api/webhook/validate_auth.go
- cmd/chaos-builder/main.go
- cmd/chaos-builder/validator.go
- cmd/chaos-controller-manager/main.go
- config/webhook/manifests.yaml
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- helm/chaos-mesh/templates/webhook-configuration.yaml
- install.sh
- pkg/config/controller.go
- pkg/selector/selector.go
- test/integration_test/dashboard_authority/run.sh
cherry-pick from https://github.com/chaos-mesh/chaos-mesh/pull/1535
Fix #1509.
add an admission webhook to validate the privileges, the user must have the privileges of all selected namespaces.
Tests
Side effects
```release-note
NONE
```
> validate the authority of selector in admission webhook

- ui/src/components/FormField/LabelField.tsx
As the title.
Now the `LabelField` will submit a label automatically when losing the focus on the text field. This prevents users from forgetting to submit labels by pressing space.
Tests
Side effects
```release-note
NONE
```
> chore: add the label after blur

- .github/workflows/integration_test.yml
The latest helm chart of localstack with version 0.1.3 has some issue, it breaks the integration test.😰
Install localstack with helm chart 0.1.2.
Tests
Side effects
```release-note
NONE
```
> fix localstack installation in integration tests

- controllers/twophase/twophase_suite_test.go
- controllers/twophase/types.go
I think this PR could fix the unstable e2e test cases `TimeSkew/StartAtWaiting`
Previous code: 
https://github.com/chaos-mesh/chaos-mesh/blob/2ce9bbcffb40aea384bf0ec592cb5a5a54370db0/controllers/twophase/types.go#L81-L90
It does not set `NextRecover`, that affects `calcRequeueAfterTime` always return 0 as `requeueAfter`.
https://github.com/chaos-mesh/chaos-mesh/blob/2ce9bbcffb40aea384bf0ec592cb5a5a54370db0/controllers/twophase/types.go#L145-L173
Tests
Side effects
```release-note
NONE
```
> fix: also set NextRecover with cron expression

- controllers/twophase/state_machine.go
- install.sh
resume chaos that has been paused for a long time.
solve https://github.com/chaos-mesh/chaos-mesh/issues/1556
If chaos is suspended for a long time, which may result in "counter> iterMax", then the experiment cannot be restarted. When this happens, start the experiment directly.
Tests
Side effects
```release-note
NONE
```
> [update] resume chaos that has been paused for a long time

- .github/workflows/integration_test.yml
- .github/workflows/script_test.yml
The same job name of different tests blocks the integration with ti-chi bot.
Change the job name to be different.
Tests
Side effects
```release-note
NONE
```
> chore: specify the different test name on github action

- test/e2e/chaos/stresschaos/cpu.go
- test/e2e/chaos/stresschaos/memory.go
use `ginkgo.By` instead of `framework.log`, the former could make better view in e2e tests with parallel nodes
Tests
Side effects
```release-note
NONE
```
> more better logs in e2e tests

- api/webhook/validate_auth.go
- test/integration_test/auth-rbac-webhook/podchaos-example.yaml
- test/integration_test/auth-rbac-webhook/rbac.yaml
- test/integration_test/auth-rbac-webhook/run.sh
fix #1684 
fix #1613
Using Resource instead of Kind. The elegant way is using `schema` and `RestMapper` converting the kind to resource, but it needs more things in the AuthValidator.
And here is a convention that the CamelCase Kind and lowercase resource, so we just use `strings.toLowerCase()`.
I put a TODO here, we will finish with `RestMapper` in another PR.
Tests
Side effects
```release-note
NONE
```
> fix vauth.kb.io webhook, use the lowercase resource name

- controllers/twophase/twophase_suite_test.go
- controllers/twophase/types.go
- test/e2e/chaos/podchaos/pod_kill.go
Without this patch, `controller-manager` will panic if the `Duration` field is `nil`.
> add check for whether duration is nil

- test/e2e/chaos/basic.go
This e2e test is unstable. In order to reduce time on rerunning the e2e test, this pr disable it temporarily. 
Tests
Side effects
```release-note
NONE
```
> e2e: disable unstable test

- controllers/twophase/state_machine.go
- controllers/twophase/state_machine_test.go
https://github.com/chaos-mesh/chaos-mesh/issues/1506
If the injection experiment fails, it will not enter the "recover" func, so the experiment cannot be deleted.
This pr wants to merge these changes into master and release 1.2.
Tests
Side effects
```release-note
NONE
```
> fix failed recover

- pkg/chaosdaemon/dns_server.go
- pkg/chaosdaemon/ipset_server.go
create an attack by Chaosd and failed, the error message doesn't contain any useful information.
```bash
./bin/chaosd attack network loss -d eth0 -i 172.16.4.4 --percent 50
exit status 1
Error: exit status 1
```
contain output in error when executing command 
Tests
Side effects
```release-note
NONE
```
> daemon: contain output in error when executing command 

- pkg/chaosdaemon/stress_server_linux.go
This PR removes the unused log from the file: https://github.com/chaos-mesh/chaos-mesh/blob/f1c817e07ea339d41ded06055998c9a1e9f135e9/pkg/grpc/utils.go#L36
> Remove unused log

- pkg/chaosdaemon/tc_server.go
Signed-off-by: arcolife <archit.py@gmail.com>
removes unused func in `pkg/chaosdaemon/tc_server.go` -> func `(*tcClient).addFilter`
> remove unused tc_server.go:addfilter()

- README.md
At present, the Markdown checker can't check the images from https://app.fossa.com
detail: https://github.com/chaos-mesh/chaos-mesh/runs/2527786009 
```
ERROR: 2 dead links found!
[✖] https://app.fossa.com/api/projects/git%2Bgithub.com%2Fchaos-mesh%2Fchaos-mesh.svg?type=shield → Status: 404
[✖] https://app.fossa.com/api/projects/git%2Bgithub.com%2Fchaos-mesh%2Fchaos-mesh.svg?type=large → Status: 404
```
Disable markdown check for these two links
Tests
Side effects
```release-note
NONE
```
> ci: disable markdown check for some links

- helm/chaos-mesh/templates/chaos-dashboard-pvc.yaml
In helm, persistent volume claim for chaos mesh dashboard is not creating due to the issue in PVC storage class variable name.
Used the correct storage class variable name in PVC template.
> fix storage class var name in helm

- hack/lib.sh
This PR bump the kind version to 0.11.0, for compatibility with cgroupv2.
I have tried kind 0.11.0 for several days, it works well with fedora 34 and cgourpv2. I do not have to raise another VM for e2e test anymore. :tada:
But the e2e test of stresschaos still not work fine with cgroupv2, I will try to fix it in next PR
just changing `KIND_VERSION`
Tests
Side effects
```release-note
NONE
```
> chore: bump kind to 0.11.0 for cgroupv2

- pkg/workflow/controllers/chaos_node_reconciler.go
Thanks to @fewdan , he notices me that I forget this thing.
Appending another label `chaos-mesh.org/workflow: <workflow-name>` for chaos objects which controlled by workflow.
Tests
Side effects
```release-note
NONE
```
> feat: also append workflow name for controlled chaos object

- e2e-test/e2e/chaos/stresschaos/memory.go
Once I occurred this thing: I have to rerun the unstable e2e test 7 times, with non-code PR https://github.com/chaos-mesh/chaos-mesh/pull/1843. :cry: 
I increase the allowed jitter range when making approximate equality as assertation about memory chaos. I think 5MB is acceptable, 10% of injected 50M memory Chaos, it might be more stable now.
Tests
Side effects
```release-note
NONE
```
> test: make memory e2e test more stable

- api/v1alpha1/awschaos_webhook.go
- api/v1alpha1/dnschaos_webhook.go
- api/v1alpha1/gcpchaos_webhook.go
- api/v1alpha1/httpchaos_webhook.go
- api/v1alpha1/iochaos_webhook.go
- api/v1alpha1/jvmchaos_webhook.go
- api/v1alpha1/kernelchaos_webhook.go
- api/v1alpha1/networkchaos_webhook.go
- api/v1alpha1/podchaos_webhook.go
- api/v1alpha1/stresschaos_webhook.go
- api/v1alpha1/timechaos_webhook.go
- pkg/apiserver/event/event.go
Signed-off-by: AsterNighT <klxjt99@outlook.com>
fix #1905
Add webhook for updating chaos
I wonder what to do with chaos and workflow
Tests
Side effects
```release-note
NONE
```
> Add webhook to reject updating chaos spec

- api/v1alpha1/zz_generated.schedule.chaosmesh.go
- api/v1alpha1/zz_generated.workflow.chaosmesh.go
- cmd/chaos-builder/workflow.go
- cmd/chaos-builder/workflow_test.go
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd.yaml
Thanks @AsterNighT, there are some weird fields names in our generated definition,like:
https://github.com/chaos-mesh/chaos-mesh/blob/46ce60e620f2f4758ed9b25c8b93a460afa7d8b1/api/v1alpha1/zz_generated.schedule.chaosmesh.go#L56-82
take a look on hTTP, jVM, dNS.
more logic on `lowercaseCamelCase()`, resolve these ALLCAP name with prefix `Chaos`.
Tests
Side effects
```release-note
NONE
```
> fix: the bad camelCase conversion method

- pkg/apiserver/schedule/schedule.go
add pause/start schedule api
Tests
Side effects
```release-note
NONE
```
> add pause/start schedule api

- pkg/apiserver/archive/archive.go
Change `/schedules/` to `/schedules` to correct the route matching. Before change, route `DELETE /archives/schedules` will jump into `DELETE /archives/:uid`. This is unexpected behavior.
Tests
Side effects
```release-note
NONE
```
> fix(route): batch delete schedule archives

- controllers/schedule/cron/controller.go
If a "schedule" has been suspended for a long time, there may be many errors during the suspension.
Check schedule.IsPaused() before getRecentUnmetScheduleTime() . 
After the modification, there will not be many errors during the suspension.
* None
Tests
Side effects
```release-note
```
> [update] check schedule.IsPaused() before getRecentUnmetScheduleTime()

- cmd/chaos-controller-manager/main.go
- helm/chaos-mesh/templates/secrets-configuration.yaml
- install.sh
Though we have developed webhook for `Schedule`. It doesn't work as the resources in the validation webhook haven't be configured properly. In this PR, I hard coded a plural form for the `schedule` resource in the webhook definition. 
If you have any better idea on how to generate a plural form of a word in helm, please tell me.
> enable schedule webhook

- pkg/core/workflow.go
- change values of `WorkflowMeta#WorkflowStatus`, keep the same with chaos' status
- ignore unused value `WorkflowMeta#Archived`
- change string const value of `WorkflowStatus`
- change the struct tag `json` of field `WorkflowStatus#Archived`
* Need to update Chaos Dashboard component, related issue: Yes.
Tests
Side effects
```release-note
```
> chore: change the status of workflow, keep same with chaos

- controllers/chaosimpl/podchaos/podfailure/impl.go
- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/values.yaml
- install.sh
- pkg/config/controller.go
Issue Number: close #1925
Proposal: This PR allows users to specify a pod failure pause image via helm values. This is useful for for organizations who can only pull images from internal registries and also where organizations have policy applied where images can only come from xyz.com
* Added a new environmental variable (controller deployment) for the pause image to the chaos controller
* Add this new environment variable to the controller config. Defaults to gcr.io pause image
* Add this controller config to the pod failure impl and set the pause image from this config
Tests
Manual Tests
Test 1
- Config Controller Mesh Deployment env to 
```
- name: POD_FAILURE_PAUSE_IMAGE
value: test.io/google-containers/pause:latest
```
- Install chaos mesh on kind …
> Custom pause image for Pod Failure Chaos

- api/v1alpha1/workflownode_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- manifests/crd-v1beta1.yaml
- manifests/crd.yaml
- pkg/core/workflow.go
- pkg/core/workflow_test.go
- pkg/workflow/controllers/new_node.go
- pkg/workflow/controllers/parallel_node_reconciler.go
- pkg/workflow/controllers/serial_node_reconciler.go
The reset part of #1984.
- rename field `WorkflowNodeSpec#Tasks` -> `WorkflowNodeSpec#Children`
- rename `Tasks` to `Children` in `pkg/core/workflow.go`
* Need to update Chaos Dashboard component, related issue: Yes.
Tests
Side effects
```release-note
```
> chore: rename Tasks to Children

- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-service.yaml
- install.sh
- pkg/config/controller.go
According to the [environment variable](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables) section in kubernetes docs, these environment variables are set like:
```
REDIS_MASTER_SERVICE_HOST=10.0.0.11
REDIS_MASTER_SERVICE_PORT=6379
REDIS_MASTER_PORT=tcp://10.0.0.11:6379
REDIS_MASTER_PORT_6379_TCP=tcp://10.0.0.11:6379
REDIS_MASTER_PORT_6379_TCP_PROTO=tcp
REDIS_MASTER_PORT_6379_TCP_PORT=6379
REDIS_MASTER_PORT_6379_TCP_ADDR=10.0.0.11
```
Therefore, the `CHAOS_DAEMON_PORT` would be `tcp://xxx.xxx.xxx.xxx:xxxx` but not the direct port number. 
Change the name of environment variable from `CHAOS_DAEMON_PORT` to `CHAOS_DAEMON_SERVICE_PORT`.
> helm: fix environment variable name

- hack/version.sh
close https://github.com/chaos-mesh/chaos-mesh/issues/2003
Replace the way to determine current commit is on a certain tag or not.
* Need to cheery-pick to the release branch: Yes.
Tests
Side effects
```release-note
```
> fix gitVersion in `<binary> version`

- controllers/common/fx.go
- controllers/desiredphase/fx.go
- controllers/finalizers/fx.go
- controllers/fx.go
- controllers/podnetworkchaos/fx.go
- controllers/schedule/active/controller.go
- controllers/schedule/cron/controller.go
- controllers/schedule/gc/controller.go
- controllers/schedule/pause/controller.go
- controllers/schedule/suit_test.go
- controllers/utils/recorder/recorder.go
- controllers/utils/test/provider.go
- pkg/workflow/controllers/bootstrap.go
No events will be aggregated now.
Submit every events manually, without the handling of kubernetes client event recorder.
> chaosRecorder: submit events without kubernetes event recorder

- api/v1alpha1/stresschaos_types.go
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_stresschaos.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_stresschaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd-v1beta1.yaml
- manifests/crd.yaml
Issue Number: close #1931
Problem Summary: stress-ng can launch at max 8192 workers, so StressChaos will fail silently in the case where workers is outside this range.
Added a kubebuilder validation to force a maximum limit of 8192 for `spec.stressors.cpu.workers`.
Tests
Side effects
```release-note
validation for number of cpu workers in stress chaos
```
> fix: add max validation to workers in stress chaos

- .github/workflows/ci.yml
- the output of github actions is toooo large, we need a lot of time to load the full log, only because of the extra `-x` in `go mod download`
- remove `-x` in `go mod download`
Tests
Side effects
```release-note
```
> chore: remove the detail output of go download

- controllers/chaosimpl/podchaos/podfailure/impl.go
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- install.sh
Issue Number: 
fix #2018 
currently, we are using kubernetes v1.17 as the dependency. But the `SeccompProfile` is introduced in v1.19, which causes the problem if we directly update the pod definition: the missing `SeccompProfile` is treated as deleted when we update the Pod.
And this PR should be "cherry-pick" to release 1.x, but it seems hard to do that automatically, I will manually create a PR.
- use patch instead of update within pod-failure
Tests
Side effects
```release-note
```
> fix: use patch instead of update within podfailure

- cmd/chaos-controller-manager/provider/controller.go
- cmd/chaos-controller-manager/provider/suit_test.go
- cmd/chaos-controller-manager/provider/updated_client.go
- cmd/chaos-controller-manager/provider/updated_client_test.go
- controllers/common/controller.go
- controllers/schedule/active/controller.go
- controllers/schedule/cron/controller.go
- controllers/utils/test/manager/test_manager.go
- controllers/utils/test/provider.go
There are some mechanism to avoid outdated fields in chaos resource. However, the following codes may actually timeout:
```go
// TODO: make the interval and total time configurable
// The following codes ensure the Schedule in cache has the latest lastScheduleTime
ensureLatestError := wait.Poll(100*time.Millisecond, 2*time.Second, func() (bool, error) {
schedule = schedule.DeepCopyObject().(*v1alpha1.Schedule)
if err := r.Client.Get(ctx, req.NamespacedName, schedule); err != nil {
r.Log.Error(err, "unable to get schedule")
return false, err
}
return schedule.Status.LastScheduleTime.Time == lastScheduleTime, nil
})
```
I developed a new client, which includes another cache. So that we could store the newest resource in the cache temporarily. …
> setup another cache which would be updated if "Update" function is called

- .github/workflows/integration_test.yml
- .github/workflows/script_test.yml
- pkg/workflow/controllers/serial_node_reconciler_test.go
- test/integration_test/aws/run.sh
trying to fix the broken Github action in #2066 #2062 #2036
What I see is the pod of chaos-controller-manager stuck in `Pending`, then timeout:
```
...
chaos-controller-manager-5974547cd9-gfbsm   0/1   Pending   0     14m
Waiting for pod running
chaos-controller-manager-5974547cd9-gfbsm   0/1   Pending   0     15m
Waiting for pod running
chaos-controller-manager-5974547cd9-gfbsm   0/1   Pending   0     15m
Waiting for pod running
chaos-controller-manager-5974547cd9-gfbsm   0/1   Pending   0     15m
Waiting for pod running
chaos-controller-manager-5974547cd9-gfbsm   0/1   Pending   0     15m
Waiting for pod running
chaos-controller-manager-5974547cd9-gfbsm   0/1   Pending   0     15m
Waiting for pod running …
```
> fix: fix broken CI "Script Test" and "Intergration Test"

- Makefile
- cmd/chaos-dashboard/main.go
- pkg/apiserver/archive/archive_test.go
- pkg/apiserver/server.go
- pkg/config/dashboard/dashboard.go
- pkg/core/experiment.go
- pkg/core/schedule.go
- pkg/core/workflow.go
- pkg/store/event/event.go
- pkg/store/experiment/experiment.go
- pkg/store/schedule/schedule.go
- pkg/store/workflow/workflow.go
- ui/package.json
- ui/src/App.tsx
Close #1500.
Since the https://github.com/gin-gonic/gin/pull/2706 be merged. Now gin allows param and exact paths to existing on the same route level.
So all of the UI assets can be safely routed by `/` and `/:foo/*bar`. This is almost the same as the `/*any`.
Except for all descriptions above, this PR also introduces some bug fixes and so on:
- Fix the problem of duplicate `uid` indices in SQLite
- Use `gorm.Model` to replace dummy fields
- Bump API server and UI versions
- Some code formats
Tests
Side effects
```release-note
```
> chore(api): use direct routes

- pkg/apiserver/archive/archive.go
- pkg/apiserver/workflow/workflow.go
- pkg/core/workflow.go
Issue Number: close #2077
A duplicated field `CreatedAt` already exists in `gorm.Model`, remove the outer one. 
- remove field `CreatedAt`
Tests
Side effects
```release-note
```
> fix: duplicated field created_at with which in gorm.Model

- ui/src/api/workflows.type.ts
- ui/src/lib/cytoscape.ts
Issue Number: close #2051
- change the way to generate workflow nodes of the graph
- use the same way which draws the PrallelNode to draw TaskNode
* Need to cheery-pick to the release branch: Yes, release-2.0.
Tests
Side effects
```release-note
```
> chore: show children of task node

- helm/chaos-mesh/templates/chaos-daemon-rbac.yaml
Currently, this value is hardcoded, which means that deploying with a
PSP to any namespace other than 'chaos-testing' will cause the daemonset
pods to fail to be admitted, because there is no valid PSP that matches
them.
Signed-off-by: Nikolas Skoufis <nskoufis@seek.com.au>
Issue Number: close #2095 
Problem Summary: Hardcoded namespace in PSP RoleBinding
What's Changed: Set the namespace of this RoleBinding to the same as the overall release namespace
Tests
Side effects
```release-note
Fixes the namespace of the PSP RoleBinding so that it matches the release namespace
```
> Update PSP RoleBinding to respect release namespace

- pkg/apiserver/server.go
As the title. This PR complements the missing handler since gin treats routes with and without a slash as two different routes.
Tests
Side effects
```release-note
```
> fix: handle routes without slash

- controllers/common/controller.go
In `PodSelector`, when no pod is selected, an error will be returned. However, in `ContainerSelector`, if no container is selected, there will be no error.
A zero-length check is added under the selection, so that when no records are selected, it will always submit an error event, even if there is no error returned.
> alert when no record has been selected

- controllers/kernelchaos/types.go
Problem Summary: 
- chaos-controller-manager could not connect to bpkfi because the bpkfi is not configured with tls
- use Insecure with client which connects to bpkfi, just like https://github.com/chaos-mesh/chaos-mesh/pull/1901/commits/e63c7d711473a0e602cf7a834dcb065b3b94071f
Tests
Side effects
```release-note
```
> fix: do not use tls while connet to bpkfi

- cmd/chaos-controller-manager/provider/updated_client.go
- cmd/chaos-controller-manager/provider/updated_client_test.go
- go.mod
- pkg/bpm/buffer.go
- pkg/bpm/buffer_test.go
Fix two possible data race and add an `UpdatedStatusClient`:
1. The `blockingBuffer` is full of data race while reading and writing at the same time.
2. The object returned from the `cache` could be the same one, and the reference stored in it will be simply copied out. Run `DeepCopy` before assigning it to the new one.
> fix data race in client and daemon

- ci/pingcap_chaos_mesh_build_kind.groovy
- e2e-test/e2e/e2e_test.go
It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/1587.
- I am trying to add the junit style output of all the e2e testcases.
- just add a new ginkgo reporter
- contributors could see which and why the e2e tests cases failed more easily.
* Need to cheery-pick to the release branch: Yes. release-2.0
Preview:
All tests passed:
test failed:
Tests
Side effects
```release-note
```
> feat: add junit report xml output

- README.md
Fix development guide broken link
Fix the broken link to the development guide.
Problem Summary: The link to the development guide from README.md wasn't working.
What's Changed: Added the correct [link](https://chaos-mesh.org/docs/developer-guide-overview) 
* PR to update `chaos-mesh/chaos-mesh`/`README.md`.
Tests
Side effects- N/A
```release-note
```
> Fix development guide broken link

- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/dns-deployment.yaml
- helm/chaos-mesh/templates/prometheus-deployment.yaml
- helm/chaos-mesh/values.yaml
Issue Number: close #2199
When your chaos mesh images reside in a private registry, one may need the ability to configure a docker secret via imagePullSecrets in the helm values file which can be enabled and overridden as required.
Proposal/What's Changed:
Specify an imagePullSecrets parameter in the values file, which can be overridden with a docker secret. If this imagePullSecrets value is present, it can be used in the 4 deployment files and 1 daemonset file to pull images from a private registry
N/A
Tests
* Create a new private azure container registry i.e. chaosmeshtest.azurecr.io
* Publish chaos mesh images to chaosmeshtest.azurecr.io
* * pingcap/chaos-daemon
* * pingcap/chaos-dashboard
* * pingcap/chaos-kernel
* * pingcap/chaos-mesh
* * pingcap/coredns
* * …
> Imagepullsecrets feature

- api/v1alpha1/httpchaos_types.go
- api/v1alpha1/httpchaos_webhook.go
- api/v1alpha1/httpchaos_webhook_test.go
- e2e-test/cmd/e2e_helper/main.go
- e2e-test/e2e/chaos/basic.go
- e2e-test/e2e/chaos/httpchaos/http_patch.go
- e2e-test/e2e/chaos/httpchaos/http_replace.go
- e2e-test/e2e/chaos/httpchaos/misc.go
- helm/chaos-mesh/values.yaml
- images/chaos-daemon/Dockerfile
- install.sh
Signed-off-by: hexilee <i@hexilee.me>
Issue Number: close #2152 
HTTPChaos patch or replace response not worked as expected, HTTP Header content-length is not updated.
Upgrade rs-tproxy to v0.2.3
Tests
Side effects
```release-note
```
> HTTPChaos: fix bugs in replace or patch body; add validators and (e2e) tests

- helm/chaos-mesh/values.yaml
Update helm coredns version from 0.2.0 to 0.2.1
bug of codns chaos serve rpc retrun nil 
from  image: pingcap/coredns:v0.2.0
to   image: pingcap/coredns:v0.2.1
according to https://github.com/chaos-mesh/chaos-mesh/issues/2163#issuecomment-899354774
Tests
Side effects
```release-note
```
update coredns image to 0.2.1
> Update the coredns image version for helm value

- api/v1alpha1/common_webhook.go
- api/v1alpha1/workflow_webhook.go
- api/v1alpha1/workflow_webhook_test.go
Issue Number:
Thanks to @g1eny0ung for noticing me about this issue.
As #2122 merged, some of the generated methods (`Validate() field.ErrorList` and `Default()`) for interface `CommonSpec` has been purged ``:
```golang
type CommonSpec interface {
GetDuration() (*time.Duration, error)
Validate() field.ErrorList
Default()
}
```
but `GetDuration()` is required for validation in workflow by `shouldNotSetupDurationInTheChaos()`.
So I rename and slim the unimplemented methods of `CommonSpec`.
- delete `Validate() field.ErrorList` and `Default` in interface `CommonSpec`
- rename interface `CommonSpec` to `ContainsDuration`
- add some unit test for this validation webhook
* PR to update …
> fix: the broken webhook for workflow

- Makefile
- images/chaos-dlv/README.md
I faced some issues when I use `chaos-dlv`:
- `make DEBUGGER=1 image` will not build `image-chaos-dlv`
- `make DEBUGGER=1 image` will build images with prefix `localhost:5000` in the tag
this PR is trying to fix these issues.
- add conditional `image-chaos-dlv` dependency for makefile recipe `image`, when `DEBUGGER=1` 
- appending `DOCKER_REGISTRY=""` in the document
* Need to cheery-pick to the release branch:  No.
Tests
Side effects
```release-note
```
> minon improvement for chaos-dlv

- pkg/fusedev/fusedev_linux.go
As the `chaos-daemon` tried to write `device.allow` in cgroup, but used the `/sys/fs/cgroup` as the root path, it will give an error. The root path of host cgroup should be `/host-sys/fs/cgroup`.
Modify `sys` to `host-sys`.
> use `host-sys` in fusedev device priviledge granting

- hack/lib.sh
Issue Number: close https://github.com/chaos-mesh/chaos-mesh/issues/2248
- URL for downloading kubebuilder broken
- use github release instead of go.kubebuilder.io/dl
Tests
Side effects
```release-note
```
> fix: the download url of kubebuilder

- pkg/apiserver/experiment/experiment.go
- pkg/apiserver/schedule/schedule.go
- pkg/core/experiment.go
- ui/src/components/NewExperimentNext/data/target.ts
- ui/src/components/NewExperimentNext/form/Stress.tsx
Unify the `containerNames` field on front-end and back-end.
Tests
Side effects
```release-note
```
> fix(StressChaos): containerNames problem

- ci/pingcap_chaos_mesh_build_kind.groovy
The base e2e image has been deleted. We should use `hub.pingcap.net/chaos-mesh/chaos-mesh-e2e-base-image`.
> e2e: fix e2e base image

- api/v1alpha1/kinds.go
- api/v1alpha1/schedule_types.go
- api/webhook/validate_auth.go
Issue Number: close #2278 
Problem Summary: The original `AllKinds()` map doesn't include `Schedule` and `Workflow`. However, we cannot simply add these two kinds to the `AllKinds()` because some codes expect all of them are `*Chaos`.
Add a new function to record all types containing `Schedule` and `Workflow`. The function is implemented by cloning the original map and add two new resources into it.
> add schedule and workflow to a special kinds map

- Makefile
I should use `space` but not `,` in the arguments of dependency. Some dependencies of `generate` hasn't been added successfully.
This PR is also related to https://github.com/chaos-mesh/chaos-mesh/pull/2274.
> fix the dependency of `generate`

- config/webhook/manifests.yaml
- helm/chaos-mesh/templates/secrets-configuration.yaml
- install.sh
As per k8s release `1.16` notes (Refer: https://v1-16.docs.kubernetes.io/docs/setup/release/notes/ ):
The `admissionregistration.k8s.io/v1beta1` versions of `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration` are deprecated and will no longer be served in v1.19. Use admissionregistration.k8s.io/v1 instead.
There is no change from functionality point of view with new apiVersion.
Tests
Side effects
```release-note
NONE
```
> Use v1 rather than v1beta1 for admissionregistration.k8s.io apiVersion in webhooks

- .github/workflows/script_test.yml
Some modifications on CRD or deployment will cause the script test failed, but the PR should also get merged. Therefore, a `skip-script-test` label is added to skip the test.
> add label to skip script test

- MAINTAINERS.md
As per the [governance doc](https://github.com/chaos-mesh/chaos-mesh/blob/master/GOVERNANCE.md#maintainer), I create this PR on behalf of Chaos Mesh maintainers to move @siddontang, @zhouqiang-cl, and @Yisaer to emeritus maintainers as they haven't been able to stay active in the project for a while due to shift of focus. And they all agree to become emeritus maintainers.  
Thanks for their awesome work on Chaos Mesh! We very much appreciate their contributions but moving their status to emeritus (and thus revoking PR approval privileges) is in the interest of an orderly and sustained project. 
/cc @chaos-mesh/maintainers
> Move @siddontang, @zhouqiang-cl, and @Yisaer to emeritus maintainers

- MAINTAINERS.md
This PR reverts chaos-mesh/chaos-mesh#2293 due to unintentional merge. 
As per the governance doc, I create this PR on behalf of Chaos Mesh maintainers to move @siddontang, @zhouqiang-cl, and @Yisaer to emeritus maintainers as they haven't been able to stay active in the project for a while due to a shift of focus. After communications, they all understand and agree to become emeritus maintainers (and thus revoking PR approval privileges) is in the interest of an orderly and sustained project.
Thanks for their awesome work on Chaos Mesh! We very much appreciate their contributions! Wish them all the best with their new adventures. 
/cc @chaos-mesh/maintainers
> Revert "Move @siddontang, @zhouqiang-cl, and @Yisaer to emeritus maintainers"

- .github/workflows/upload_build_env_image.yml
- .github/workflows/upload_dev_env_image.yml
The `dev-env` and `build-env` is modified too frequently! We should only upload them when the `Dockerfile` is modified.
> build only when dockerfile is modified

- pkg/dashboard/apiserver/event/event.go
- pkg/dashboard/collector/event_collector.go
- pkg/dashboard/core/common.go
- pkg/dashboard/store/event/event.go
- ui/src/components/NewExperimentNext/Step2.tsx
This PR persists event with UTC time (`CreatedAt` field). Using UTC time helps us to better filter data by time range without considering the time zone.
- before persist and query events, parse time to UTC
- fix a condition typo in `ConstructQueryArgs`
- remove unused imports
Tests
Side effects
```release-note
```
> fix: persist event with UTC Time

- api/v1alpha1/common_types.go
- controllers/schedule/cron/controller.go
- controllers/schedule/utils/list.go
- pkg/dashboard/apiserver/schedule/schedule.go
- pkg/dashboard/collector/collector.go
Signed-off-by: iawia002 <z2d@jifangcheng.com>
Issue Number: close #1930
the `managed-by` label has been used in several places, so this PR turns it into a constant value.
Make the managed-by label a const value
Tests
Side effects
```release-note
None
```
NOTE: this PR is similar to #2204, but that PR has not been updated for a long time, so I submitted this PR.
/cc @STRRL
> Make the managed-by label a const value

- api/v1alpha1/common_types.go
- controllers/chaosimpl/httpchaos/impl.go
- controllers/chaosimpl/iochaos/impl.go
- controllers/chaosimpl/networkchaos/trafficcontrol/impl.go
- controllers/common/fx.go
- controllers/desiredphase/controller.go
- controllers/finalizers/controller.go
- controllers/schedule/cron/controller.go
- controllers/schedule/pause/controller.go
Problem Summary: 
Since `GenericChaos` interface implements the `metav1.Object` interface, there is no need to  add the `GetObjectMeta` method.
Remove the duplicated `GetObjectMeta` method in the `StatefulObject` interface.
Tests
Side effects
```release-note
None
```
/assign @STRRL for review since you add the duplicated note.
> Remove the duplicated GetObjectMeta method

- .github/workflows/upload_env_image.yml
Add image tag to the action. The CI: https://github.com/chaos-mesh/chaos-mesh/runs/3674089450?check_suite_focus=true has failed, because I didn't set the `IMAGE_TAG` environment variable.
> ci: add image tag to action

- controllers/podnetworkchaos/types_test.go
- pkg/chaosctl/common/common_test.go
- pkg/chaosctl/debug/stresschaos/stresschaos.go
- pkg/selector/pod/selector_test.go
Signed-off-by: iawia002 <z2d@jifangcheng.com>
Both `NewFakeClient` and `NewFakeClientWithScheme` has been deprecated:
```go
// NewFakeClient creates a new fake client for testing.
// You can choose to initialize it with a slice of runtime.Object.
//
// Deprecated: Please use NewClientBuilder instead.
func NewFakeClient(initObjs ...runtime.Object) client.WithWatch
// NewFakeClientWithScheme creates a new fake client with the given scheme
// for testing.
// You can choose to initialize it with a slice of runtime.Object.
//
// Deprecated: Please use NewClientBuilder instead.
func NewFakeClientWithScheme(clientScheme *runtime.Scheme, initObjs ...runtime.Object) client.WithWatch
```
* Replace deprecated methods with the new `NewClientBuilder` method.
* Fixed a …
> Replace fake.NewFakeClient with NewClientBuilder since the NewFakeClient method is already deprecated

- pkg/collector/collector.go
support aws/gcp chaos in dashboard archive
Tests
Side effects
```release-note
```
> fix: support aws/gcp chaos in dashboard archive

- ci/pingcap_chaos_mesh_build_kind.groovy
- hack/e2e.sh
- hack/kind-cluster-build.sh
kind starts to support arm64 images in version `1.20.7`, but now we use the version `1.20.2` which is not support to run on arm64 arch.
* kind version on e2e tests
* kind version in `kind-cluster-build.sh`
Tests
Side effects
```release-note
```
> Upgrade kind versions on e2e tests

- controllers/chaosimpl/physicalmachinechaos/impl.go
The `process` field has a `process` key :full_moon_with_face: . The original logic will remove `process` key from the request.
> physicalmachinechaos: remove key before set kv

- helm/chaos-mesh/templates/secrets-configuration.yaml
- install.sh
Issue Number: 
- close #2421, let next 2.0.x release support kuberentes 1.22+
- close https://github.com/chaos-mesh/website/issues/140
- helm charts on `release-2.0` still using admissionregistartion v1beat1, which has been removed from kubernetes 1.22, so 2.0.x could not play well with k8s 1.22+
- update helm charts
Tests
Side effects
```release-note
```
> chore: update admissionregistration with v1

- .github/workflows/upload_image.yaml
- Makefile
- We have migrated image build from public self-hosted Jenkins to  GitHub Action on `master` branch, but not cherry-pick  into `release-2.0` branch.
- new GitHub Action Workflow for building images with release
Tests
I have tested it on my forked repo: 
see https://github.com/STRRL/chaos-mesh/actions
and https://github.com/STRRL/chaos-mesh/actions/runs/1424638417
Side effects
```text
```
> building images for realease-2.0 with GitHub Action

- .github/workflows/upload_image.yml
It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2475;
change artifact image name, from `ghcr.io/chaos-mesh/chaos-mesh/<component>` to  `ghcr.io/chaos-mesh/<component>`
Tests
Side effects
```text
```
> chore: short the project name for image

- pkg/dashboard/core/workflow.go
Close #2464
Added gorm argument in dashboard core workflow for the WorkflowEntity struct. This will define the type as a TEXT, allowing the column length to be bigger than MySQL allows via defaults.
Related error shown when starting dashboard with brand new / blank database:
```
[2021-11-03 17:06:15]  Error 1074: Column length too big for column 'workflow' (max = 16383); use BLOB or TEXT instead 
panic: Error 1146: Table 'chaos-mesh.workflow_entities' doesn't exist
```
Tests
I have not had time to get local complete e2e testing environment working to run unit tests, however have tried basic test of starting the dashboard and running an experiment.
Manually tested with sqlite and mysql 8.0 ( Complete MySQL usage still blocked by bug outlined in #1659 ) …
> Fix dashboard mysql bug

- Makefile
The nightly build failed because `--load` is not supported.
> Makefile: remove buildx and load argument

- pkg/dashboard/collector/collector.go
- pkg/dashboard/collector/schedule_collector.go
- ui/src/components/NewExperimentNext/Step1.tsx
- ui/src/components/NewExperimentNext/data/types.ts
support JVMChaos in Dashboard 
Tests
Side effects
```text
```
> support JVMChaos in Dashboard

- ui/package.json
- ui/src/App.tsx
- ui/src/components/NewExperimentNext/LoadFrom/index.test.tsx
- ui/src/components/NewExperimentNext/LoadFrom/index.tsx
- ui/src/lib/idb.ts
- ui/src/test-utils.tsx
Close #2508, #1458.
When creating a new schedule, the schedule archives can't be displayed.
#1458 is a legacy way to perform the components testing, I replace it with [@testing-library/react](https://testing-library.com/docs/react-testing-library/intro/).
Get the corresponding loadable objects according to the different creation methods.
Tests
Side effects
```text
```
> fix: can't load schedule archives

- cmd/chaos-controller-manager/main.go
- pkg/router/reconciler.go
- pkg/router/route_table.go
- pkg/updatedclient/updated_client.go
After #2509 , the cache in client breaks the twophase controller:
1. The controller updates the chaos into Running.
2. The controller reconciles the chaos, gets a cache and think it's waiting
3. Step into the finished state, merge the conflict, remove the finalizer and step out.
In this PR, I backported the `UpdatedClient` in `release-2.0` to make the cache at least updated to the latest successfully `Update`d object.
> client: use updatedClient to fix cache problem

- pkg/chaosdaemon/crclients/docker/client.go
Close #2413
This PR makes the docker client can receive env variables to set the version of the API to reach.
Add `client.FromEnv` to ops.
Tests
> steps:
1. Downgrade docker to `18.09` and build the local images.
2. Install: `helm install chaos-mesh helm/chaos-mesh -n=chaos-testing --set images.registry=localhost:5000,dashboard.securityMode=false,dashboard.image.repository=g1eny0ung/chaos-dashboard,chaosDaemon.image.repository=g1eny0ung/chaos-daemon,controllerManager.image.repository=g1eny0ung/chaos-mesh,chaosDaemon.env.DOCKER_API_VERSION=1.39`
3. Test with a `network-delay` experiment
4. Successfully injected.
Side effects
```text …
```
> fix(daemon): allow docker client use low version API

- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/values.yaml
- images/chaos-dashboard/Dockerfile
- install.sh
- pkg/config/dashboard/dashboard.go
- pkg/dashboard/apiserver/auth/gcp/service.go
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
Try to get the scheme and host from the request is not realistic. If the dashboard is deployed behind a load balancer, it will have no way to guess the scheme. In this PR, I added a config field, so that the users can set the root url manually. The dashboard will append `/api/auth/gcp/callback` to the path.
BTW, it also installs the `ca-certificates` to the `chaos-dashboard` container, which is required to avoid x509 error.
> auth: add rooturl configuration in gcp authentication

- pkg/chaosdaemon/server.go
The default minimum version of `TLS` is 1.0. This PR will set it to TLS 1.3
It doesn't have any compatibility problem because Chaos Mesh is using TLS 1.3 now.
> daemon: avoid tls downgrade attack by setting min version of tls

- helm/chaos-mesh/README.md
- helm/chaos-mesh/templates/secrets-configuration.yaml
Updates the current usage of cert-manager resources to the stable `v1` API.
Tests
Side effects
```release-note
Helm: Update cert-manager resources to v1
```
> Helm: Update manifests for cert-manager/v1 API

- cmd/chaos-controller-manager/provider/controller.go
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
- helm/chaos-mesh/templates/controller-manager-service.yaml
- helm/chaos-mesh/values.yaml
- install.sh
- pkg/config/controller.go
Signed-off-by: TangliziGit <tanglizimail@foxmail.com>
Close #2569
> Problem Summary: #2569
1. expose webhook and metrics ports in helm `values.yaml`.
2.  add `WebhookHost` and `WebhookPort` in `ChaosControllerConfig`.
3. disassemble `MetricsAddr` in `ChaosControllerConfig` into `MetricsHost` and `MetricsPort`.
Tests
Side effects
> fix: remove hardcoded ports and expose them on helm level

- Makefile
It should always use the latest version for `build-env` and `dev-env`.
Specify the certain image tag for `build-env` and `dev-env`
Tests
Side effects
```text
```
> fix: always use latest for build-env and dev-env

- ui/src/components/NewExperimentNext/Step2.tsx
- ui/src/components/NewExperimentNext/index.tsx
This PR fixes two problems:
- Use `kind` to detect `PhysicalMachineChaos` or others
- Due to we sanitize the object before creating, we also need to add default fields before we load them
Tests
Side effects
```text
```
> fix(ui): unable to load from objects

- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- helm/chaos-mesh/values.yaml
- install.sh
- pkg/config/dashboard/dashboard.go
- pkg/dashboard/collector/server.go
- pkg/dashboard/store/metrics/metrics.go
- pkg/dashboard/store/store.go
Signed-off-by: TangliziGit <tanglizimail@foxmail.com>
> Problem Summary: a part of #2397
1. add archived objects metrics for `/pkg/dashboard/store`.
2. expose metric host and port for `chaos-dashboard` in `/helm/chaos-mesh/values.yaml`.
Tests
Side effects
In previous versions, the metric endpoint was exposed by manually adding the environment variable `METRIC_ADDRESS: "0.0.0.0:8080"` to the deployment configuration of 'chaos-dashboard'. But the port can not be exposed in the helm template, because `spec.template.spec.containers.ports.containerPort` in deployment configurations and service configurations should be an integer.
In order to expose metric port from the helm template, `ChaosDashboardConfig.MetricAdress` in `/pkg/config/dashboard/dashboard.go` is modified for …
> feat(metrics): add archived objects metrics for chaos-dashboard

- test/integration_test/physical_machine/run.sh
Chaosd [v1.1.0](https://github.com/chaos-mesh/chaosd/releases/tag/v1.1.0) is released, so use it in the integration test.
Tests
Side effects
```text
```
> use chaosd v1.1.0 in integration test

- helm/chaos-mesh/templates/ingress.yaml
Close #2603 
Fixed condition in helm template that caused the apiVersion to be commented out
Tests
render chart with helm template to validate that the apiVersion is not commented
Side effects
```text
Fixed helm chart ingress apiVersion missing
```
```shell
```
> helm: fix ingress condition

- pkg/time/asset.go
- pkg/time/fakeclock.go
- pkg/time/time_linux_amd64.go
- pkg/time/time_linux_amd64_test.go
- pkg/time/time_skew_amd64.go
No. It does not relate to any problem. 
This PR aims to make it easier to extend TimeChaos Injection.
This PR introducer new interface called `FakeClockInjector` to present a component that could modify the time of the target process. 
```go
type FakeClockInjector interface {
Inject(pid int) error
Recover(pid int) error
}
```
Currently, one implementation of `FakeClockInjector` has its corresponding "fake image" as the data which would be poked into the target process. 
For each different `FakeImage`, I suggest building different `FakeClockInjector` based on it. And use the composite pattern if we need to inject more than one fake image into the target process.
We have only one implementation `TimeSkew` for `FakeClockInjector` now.
And it uses full filename(not trim `.o`) as the name of …
> refactor pkg/time

- pkg/chaosdaemon/server.go
- pkg/dashboard/apiserver/server.go
- pkg/dashboard/collector/collector.go
- pkg/metrics/chaos-daemon.go
- pkg/metrics/chaos-dashboard.go
Signed-off-by: TangliziGit <tanglizimail@foxmail.com>
Issue Number: a part of #2397
1. add new option `WithGrpcMetricsCollection` for `grpc.GrpcBuilder` to provide `grpc_prometheus.UnaryClientInterceptor` and `grpc_prometheus.StreamClientInterceptor`.
2. use the option `WithGrpcMetricsCollection` in `chaosdaemon.ChaosDaemonClientBuilder.Build()` to build gRPC client with prometheus gRPC metics collector, see more: https://github.com/grpc-ecosystem/go-grpc-prometheus#client-side.
3. register `grpc_prometheus.DefaultClientMetrics` and enable gRPC request duration histogram.
* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: No
* Need to update Chaos Dashboard component, related issue: No
* Need to cheery-pick to the release …
> feat(metrics): add gRPC client request duration histogram metric

- Makefile
The `registry` field does not exist anymore in `values.yaml`.
Replace `registry` with `images.registry`
Tests
Side effects
```text
```
```shell
```
> fix make install; set images.registry

- pkg/apiserver/experiment/experiment.go
close #2654
Tests
Side effects
```text
```
```shell
```
> chore: nil check when creating stressor

- ci/pingcap_chaos_mesh_build_kind.groovy
Download build cache from file server, and use `ghprbTargetBranch` to get the target branch.
> e2e: Download build cache from file server (#2617, #2702)

- codecov.yml
Currently, we do not restrict the test coverage for each commit and PR, so I prefer to disable `codecov/patch` feature.
Tests
Side effects
```text
```
```shell
```
> chore: disable codecov/patch

- Makefile
Revert "fix: always use latest for build-env and dev-env (#2582)"
This reverts commit 802bf850e3e852b2aecc88400f9b5c66cfab9e9c.
It's a part of #2710.
What we need is just dispatch the GitHub Action "Upload Env Image" for branch master  and release-2.1 .
Tests
Side effects
```text
```
```shell
```
> revert #2582

- Makefile
As this [blog](https://go.dev/blog/cover) says, the default `covermode` is `set`, which would only record the statement runs or not. 
It's better to use `-covermode atomic` for more accurate code coverage and which is suggested by codecov: https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
Tests
Side effects
```text
```
```shell
```
> chore: use `-covermode atomic` for accuracy hits with parallel

- .github/workflows/upload_image.yml
GitHub Action failed to build images for release: chaos-mesh/chaos-mesh/actions/runs/1633015443
rebuild `dev-env` and `build-env` with released version and daily builds.
Tests
Side effects
```text
```
```shell
```
> chore: rebuild dev-env and build-env when releasing

- build/build_image.py
- build/common.py
- build/get_env_shell.py
1. Don't override environment variable in the build-script
2. Pass environment variable like `HTTP_PROXY` and `HTTPS_PROXY`... to the dev environment.
> build: fix environment variables in build scripts

- .github/workflows/checklink.yaml
- .github/workflows/checklink_config.json
We currently use [gaurav-nelson/github-action-markdown-link-check@v1](https://github.com/gaurav-nelson/github-action-markdown-link-check) to check all markdown links. At first, we only want to check for link errors (usually `404`) due to our reasons. But, for some unknowable reason, such as a server IP being banned or something, it will return a `403` error, which is out of our control.
This PR adds the `"aliveStatusCodes": [200, 403, 500, 502, 503]` to make the action meet our needs.
Tests
Side effects
```text
```
If you find the DCO check fails, please run commands like below (Depends …
> chore: update checklink config

- .github/workflows/integration_test.yml
- .github/workflows/upload_latest_files.yml
- .github/workflows/upload_release_files.yml
It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2783.
setup go 1.15 for github actions
Tests
Side effects
```text
```
```shell
```
> chore: setup go 1.15 for github actions

- api/v1alpha1/gcpchaos_types.go
- config/crd/bases/chaos-mesh.org_gcpchaos.yaml
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_gcpchaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd-v1beta1.yaml
- manifests/crd.yaml
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
- ui/app/src/components/NewExperimentNext/data/types.ts
Tests
Side effects
```text
```
```shell
```
> docs: fix the description of GCPChaos

- cmd/chaos-builder/main.go
human unreadable time in chaos-builder's log.
use the default development configuration for zap.
Tests
Side effects
```text
```
```shell
```
> chore: use development logger for chaos-builder

- examples/burn-cpu.yaml
- examples/container-kill-example.yaml
- examples/dns-chaos-example.yaml
- examples/io-attr-example.yaml
- examples/io-delay-example.yaml
- examples/io-errno-example.yaml
- examples/jvm/app.yaml
- examples/jvm/jvm-exception-example.yaml
- examples/jvm/jvm-return-example.yaml
- examples/jvm/jvm-rule-data-example.yaml
- examples/network-bandwidth-example.yaml
- examples/network-corrupt-example.yaml
- examples/network-delay-example.yaml
- examples/network-delay-with-external-target-example.yaml
- examples/network-delay-with-target-example.yaml
- examples/network-duplicate-example.yaml
- examples/network-loss-example.yaml
- examples/network-netem-example.yaml
- examples/network-netem-with-target-example.yaml
- examples/network-partition-example.yaml
- examples/network-partition-with-external-targets-example.yaml
- examples/nginx/http-patch-response.yaml
- examples/pod-failure-example.yaml
- examples/pod-kill-example.yaml
- examples/time-chaos-example.yaml
The namespace in the YAML files in the example folder can now be overwritten through Kubernetes Command Line.
close https://github.com/chaos-mesh/chaos-mesh/issues/2819
Removed Namespace in YAML Files.
Tests
> removed namespace field

- pkg/chaosdaemon/jvm_server.go
Signed-off-by: imlonghao <git@imlonghao.com>
https://github.com/chaos-mesh/chaos-mesh/issues/2751
Read all the CommName from container, if the pid's CommName
is `java\n` then it is the correct pid to be injected.
It is a bug fix so I think it need to be backported.
Tests
1. Build the chaos-daemon
2. Deploy a java Pod which java pid is not 1
3. Create a JVMChaos and see whether the inject is work
Side effects
```text
```
```shell
git push …
```
> fix(JVMChaos): find the correct pid by CommName

- pkg/dashboard/apiserver/workflow/workflow.go
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
the comment of `createWorkflow` is wrong
Tests
Side effects
```text
```
```shell
```
> fix wrong comment on workflow Dashboard HTTP API

- .github/workflows/upload_image.yml
- hack/version.sh
close #2659 
- with step `action/checkout@master`, setup `fetch-depth: 0` to fetch all the tags and branches
- setup `--always` with `git describe`, it would give the commit hash as fallback instead of fatal then nothing be set with `GIT_VERSION`. 
Tests
I manually tested it at https://github.com/STRRL/chaos-mesh/actions/workflows/fix_git_version.yml.
Side effects
```text
```
```shell
```
Signed-off-by: STRRL …
> fix gitVersion while compling in GithubAction

- cmd/chaos-controller-manager/main.go
- cmd/chaos-controller-manager/provider/controller.go
- cmd/chaos-controller-manager/provider/suit_test.go
- controllers/common/suit_test.go
- controllers/schedule/suit_test.go
- pkg/log/doc.go
- pkg/log/fx_logger.go
- pkg/log/global_logger.go
- pkg/log/zap.go
- pkg/workflow/controllers/suite_test.go
it is a part of https://github.com/chaos-mesh/chaos-mesh/issues/2969
- cherry pick #2808 into release-2.1
Tests
Side effects
```text
```
```shell
```
> cherry-pick logging updates into release-2.1

- e2e-test/e2e/chaos/basic.go
- e2e-test/e2e/chaos/httpchaos/http_replace.go
- pkg/chaosdaemon/tproxyconfig/config.go
Close #2988
Replace field [Body](https://github.com/chaos-mesh/chaos-mesh/blob/5005201fdab583f46bef71c2e9e536f6766cc7b6/pkg/chaosdaemon/tproxyconfig/config.go#L179) of PodHttpChaosReplaceActions with a pointer.
Tests
Side effects
```text
```
```shell
```
> fix wrong zero value of httpchaos replace body action

- pkg/bpm/build_darwin.go
It's a small mistake I have found (I use mac vscode and the static checker always complains that many errors occurred).
Add the missing `context.Context` param in `Build()`.
Tests
Side effects
```text
```
```shell
```
> fix: add the missing `context.Context` param in bpm/build_darwin

- controllers/chaosimpl/dnschaos/types.go
- pkg/selector/pod/selector.go
Refactoring `pkg/selector/pod`, move `GetService` near to DNSChaos implementation, make it unexported, and remove the unused parameter
Tests
It could be compiled with no error.
Side effects
```text
```
```shell
```
> refactor: move GetService out of package pod selector

- pkg/time/time_linux_arm64.go
Fix build chaos mesh in arm64: https://github.com/chaos-mesh/chaos-mesh/runs/5500395233?check_suite_focus=true 
```
pkg/chaosdaemon/time_server.go:46:24: too many arguments in call to "github.com/chaos-mesh/chaos-mesh/pkg/time".ModifyTime
have (int, int64, int64, uint64, logr.Logger)
want (int, int64, int64, uint64)
pkg/chaosdaemon/time_server.go:75:24: too many arguments in call to "github.com/chaos-mesh/chaos-mesh/pkg/time".ModifyTime
have (int, int64, int64, number, logr.Logger)
want (int, int64, int64, uint64)
make: *** [Makefile:165: images/chaos-daemon/bin/chaos-daemon] Error 2
```
Tests
Side effects
```text
You can safely ignore this section if you don't think this …
```
> Fix `ModifyTime` function in arm64

- CHANGELOG.md
- cmd/chaos-dashboard/main.go
This PR is ready for review
It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2969;
- use pkg/log instead of controller-runtime zap to initialize the root logger in chaos-dashboard
Tests
Side effects
```text
```
```shell
```
> chaos-dashboard: use pkg log instead of controller-runtime log (#2973)

- CHANGELOG.md
- api/v1alpha1/iochaos_types.go
- config/crd/bases/chaos-mesh.org_iochaos.yaml
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_iochaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd.yaml
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
Cherry-pick #3018
Tests
Side effects
```text
```
```shell
```
> cherry-pick: fix default percent field in iochaos (#3018)

- .github/workflows/e2e_test.yml
Avoiding failure caused by GitHub API Rate Limiting like https://github.com/chaos-mesh/chaos-mesh/runs/5781739841?check_suite_focus=true
`actions-setup-minikube` provides parameter `github token`: https://github.com/manusa/actions-setup-minikube#optional-input-parameters
- append one more parameter `github token`
Tests
Side effects
```text
```
```shell
```
> chore: use github token to avoid GitHub API Rate Limiting with e2e tests

- .github/workflows/upload_env_image.yml
- Makefile
- env-images.yaml
- hack/env-image-tag.sh
cherry-pick https://github.com/chaos-mesh/chaos-mesh/pull/3071 into release-2.1
specify certain env images for release-2.1
Tests
Side effects
```text
```
```shell
```
> chore: specify env tags for each branches (#3071)

- cmd/chaos-daemon/main.go
- hack/update_install_script.sh
- helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml
- helm/chaos-mesh/values.yaml
- install.sh
- pkg/chaosdaemon/container_test.go
- pkg/chaosdaemon/crclients/client.go
- pkg/chaosdaemon/crclients/client_test.go
- pkg/chaosdaemon/ipset_server_test.go
- pkg/chaosdaemon/iptables_server_test.go
- pkg/chaosdaemon/server.go
- pkg/chaosdaemon/server_test.go
- pkg/chaosdaemon/time_server_test.go
close #3072 
Tests
Side effects
```text
Make container runtime socket path and containerd ns configurable, and change the socket volume path in pod
```
```shell
```
Signed-off-by: xianglingao <xianglingao@tencent.com>
> make container runtime socket path and containerd ns configurable and change the socket volume path in pod

- api/v1alpha1/podiochaos_types.go
- config/crd/bases/chaos-mesh.org_iochaos.yaml
- config/crd/bases/chaos-mesh.org_podiochaos.yaml
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_iochaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_podiochaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd-v1beta1.yaml
- manifests/crd.yaml
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
Signed-off-by: xianglingao <xianglingao@tencent.com>
Tests
Side effects
```text
```
```shell
```
> fix some typos

- api/v1alpha1/stresschaos_types.go
- config/crd/bases/chaos-mesh.org_schedules.yaml
- config/crd/bases/chaos-mesh.org_stresschaos.yaml
- config/crd/bases/chaos-mesh.org_workflownodes.yaml
- config/crd/bases/chaos-mesh.org_workflows.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_schedules.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_stresschaos.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflownodes.yaml
- helm/chaos-mesh/crds/chaos-mesh.org_workflows.yaml
- manifests/crd-v1beta1.yaml
- manifests/crd.yaml
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
Close #3064
Tests
set cpu stress load 150
then I get 
```
error.api.internal_server_error: admission webhook "vstresschaos.kb.io" denied the request: Spec.Stressors.CPUStressor.Load: Invalid value: 150: valid cpu load is from 0 to 100
Side effects
```
```text
```
```shell
```
> validate cpu load

- cmd/chaos-dashboard/main.go
- pkg/dashboard/collector/fx.go
- pkg/dashboard/collector/server.go
Signed-off-by: z1cheng <imchench@gmail.com>
Close #2879
Tests
Side effects
```text
```
```shell
```
> Refine logging in pkg/dashboard/collector/server.go

- helm/chaos-mesh/templates/secrets-configuration.yaml
Signed-off-by: Marco Orovecchia <marco.orovecchia@ecosio.com>
Close #3099
Tests
Side effects
```text
```
```shell
```
> fix: set certmanager ca duration

- CHANGELOG.md
- images/chaos-daemon/Dockerfile
close https://github.com/chaos-mesh/chaos-mesh/issues/2927
upgrade `toda` to 0.2.3, which introduce the bugfix: https://github.com/chaos-mesh/toda/pull/31 
Tests
Side effects
```text
```
```shell
```
> chore: bump the verison of toda to 0.2.3

- CHANGELOG.md
- images/chaos-daemon/Dockerfile
Manually cherry-pick https://github.com/chaos-mesh/chaos-mesh/pull/3131 into release-2.0
Tests
Side effects
```text
```
```shell
```
> chore: bump the verison of toda to 0.2.3 (#3131)

- .github/workflows/e2e_test.yml
- CHANGELOG.md
Close #3144 
- bootstrap environment always with images with the tag `latest` because `make image` would always build images with `latest` 
Tests
Side effects
```text
```
```shell
```
> Specify image tag in e2e tests

- hack/env-image-tag.sh
- it did not cleanup completed contained within `./hack/env-image-tag.sh`
- use the `yq` docker image with certain tag , for avoiding outdated images on docker registry mirror 
Tests
Side effects
```text
```
```shell
```
> chore: use docker with --rm and certain yq image

- .github/workflows/checklink_config.json
- fix  https://github.com/chaos-mesh/chaos-mesh/issues/3161
- update ignore patterns, ignore links (anchor) start with `#`
as https://github.com/gaurav-nelson/github-action-markdown-link-check/pull/129#issuecomment-1103317932 says, a available solution is to disable checks on anchors. So I set a ignore pattern for that
Tests
I tested it with `act` on my local machine. :)
Side effects
```text
```
```shell …
```
> ci: ignore internal link/anchor

- CHANGELOG.md
- ui/app/src/components/NewExperimentNext/form/Stress.tsx
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
Because we use `memStress` to implement memory stressors now, this field has to be updated.
> update description of memory stressors

- .github/workflows/e2e_test.yml
- CHANGELOG.md
close https://github.com/chaos-mesh/chaos-mesh/issues/3209
- build dev-env/build-env container image if label rebuild-dev-env-image/rebuild-build-env-image exists
CHANGELOG
Tests
Side effects
```text
```
```shell
```
> ci: build dev-env and build-env for e2e tests if required

- .github/workflows/e2e_test.yml
- .github/workflows/e2e_test_upload_cache.yml
- CHANGELOG.md
Cherry Pick #3097 
1. Upload the build cache for every commit in the master/release branch.
2. Automatically download the cache from the github to accelerate the build.
3. `minikube image load` from the archive directly.
The build time can be shrunken to 1min25s
> e2e: upload build image cache to the github (#3097)

- .github/workflows/e2e_test.yml
- .github/workflows/must_update_changelog.yml
The result of CI `must_update_changelog` depends on the label "no-need-update-changelog", but it won't re-run when labels change. This PR resolved a part of #3301.
CHANGELOG
Tests
Side effects
```text
```
```shell
```
> re-trigger ci 'must_update_changelog' when labels change

- CHANGELOG.md
The changelog of #3272 is appended in the wrong position.
CHANGELOG
Tests
Side effects
```text
```
```shell
```
> fix wrong changelog about bump chaos-tproxy

- .github/workflows/must_update_changelog.yml
cherry-pick(#3300)
--------------------
* re-trigger ci 'must_update_changelog' and 'e2e_test' when labels change
* update skip check for e2e_test
* delete unused steps
* fix e2e_test
* fix e2e_test again
* revoke e2e_test
* trigger ci
Co-authored-by: YangKeao <yangkeao@chunibyo.icu>
CHANGELOG
Tests
Side effects
```text …
```
> cherry-pick(#3300): re-trigger ci 'must_update_changelog' when labels change

- CHANGELOG.md
- helm/chaos-mesh/templates/cert-manager-certs.yaml
As of cert-manager version 1.8, the field spec.privateKey.rotationPolicy on Certificate objects is validated. Valid values are 'Always' or 'Never'.
See the cert-manager release notes for more information: https://cert-manager.io/docs/release-notes/release-notes-1.8#breaking-changes-you-must-read-this-before-you-upgrade
This will close #3324 
This adds the following to the four Certificates created by chaos-mesh:
```
privateKey:
rotationPolicy: Never
```
CHANGELOG
Tests
1. Set webhook.certManager.enabled: true in values.yaml
2. Run `helm template chaos-mesh .`
3. Look at the created Certificates
The created Certificates should have a value set for spec.privateKey.rotationPolicy, like this:
```
apiVersion: cert-manager.io/v1alpha2
kind: …
```
> Set certificate.spec.privateKey.rotationPolicy on Certificates

- ui/app/src/i18n/en.json
- ui/app/src/i18n/zh.json
As the title.
CHANGELOG
Tests
Side effects
```text
```
```shell
```
> fix(ui): `space` to `enter` in helper texts

- CHANGELOG.md
- cmd/chaos-controller-manager/main.go
Signed-off-by: z1cheng <imchench@gmail.com>
Close #3331 
CHANGELOG
Tests
Side effects
```text
```
```shell
```
> Remove not used Clientset in cmd/chaos-controller-manager/main.go

- CHANGELOG.md
- ui/app/src/components/NewExperimentNext/form/Stress.tsx
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
Add a comment to the flag `size` of memory stress in the dashboard, so that users can easily know they can set the `size` to a percentage. 
A sigle comment at the front end.
CHANGELOG
Tests
Side effects
```text
```
```shell
```
> Add a comment to the flag size of memory stress in the dashboard

- .github/workflows/checklink_config.json
"markdown-link-check" usually failed because of `https://www.microsoft.com/` in the last several weeks, I  think it might relate to the robot access policy of MS.
But we have no other way except ignore that error.
- try to fix CI "markdown-link-check" failed with `https://www.microsoft.com/`
I have created an issue https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/140 on upstream.
- ignore `https://www.microsoft.com/` with CI markdown-link-check
CHANGELOG
Tests
Side effects
```text
```
If you find the DCO check fails, please run commands like below (Depends on the actual …
> ci: ignore microsoft within markdown link check

- .github/pull_request_template.md
As the title. After we have to choose to update `CHANGELOG.md`, this section is useless.
CHANGELOG
Tests
Side effects
```shell
```
> chore: remove release note in pr template

- CHANGELOG.md
- pkg/bpm/build_linux.go
- pkg/chaosdaemon/stress_server_linux.go
To modify the `oom_score_adj`, we used the `choom` program. Then the whole process would be: `choom pause nsexec memStress`. However, if the `choom` runs not that fast, when the chaos-daemon is sending SIGCONT to the subprocess, it may find the comm is `choom` and thought this process has resumed.
```go
comm, err := util.ReadCommName(cmd.Process.Pid)
if err != nil {
return nil, err
}
if comm != "pause\n" {
log.Info("pause has been resumed", "comm", comm)
break
}
```
So, the `pause` should always be the first command to execute.
Reorder the command executed by bpm.
> stresschaos: run pause before choom

- CHANGELOG.md
- helm/chaos-mesh/Chart.yaml
- helm/chaos-mesh/values.yaml
- install.sh
Bump version to 2.2.1
Here is the draft of release note:
This release introduces several new features, enhancements, bug fixes for Chaos Mesh.
- JVMChaos: support inject fault into MySQL client [#3189](https://github.com/chaos-mesh/chaos-mesh/pull/3189)
- PhysicalMachineChaos: update stress options type [#3354](https://github.com/chaos-mesh/chaos-mesh/pull/3354)
- StressChaos: run `pause` before `choom` [#3405](https://github.com/chaos-mesh/chaos-mesh/pull/3405)
> bump version to 2.2.1

- CHANGELOG.md
- api/v1alpha1/workflow_webhook.go
- api/v1alpha1/workflow_webhook_test.go
When using a malformed Workflow that would contain no EmbedChaos,
the validating webhook was having a panic because the
shouldNotSetupDurationInTheChaos function was not returning early
and access a nil value afterwards.
`shouldNotSetupDurationInTheChaos` returns early when EmbedChaos is nil, avoiding the line
`	spec := reflect.ValueOf(template.EmbedChaos).Elem().FieldByName(string(template.Type))
`
to be reached, thus removing a panic.
This problem was happening to me when applying a misconfigured Workflow:
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
name: workflow-fail
namespace: kube-system
spec:
entry: entry
templates:
- name: entry
templateType: Serial
deadline: 5m
children:
- kill-coredns
- name: kill-coredns
templateType: PodChaos
schedule:
schedule: …
```
> Fix Workflow Validating Webhook Panic

- CHANGELOG.md
- controllers/chaosimpl/dnschaos/types.go
- helm/chaos-mesh/templates/dns-deployment.yaml
- helm/chaos-mesh/values.yaml
This PR enables to have more than one dns chaos servers running inside a k8s cluster (which might help to have dns chaos in a production environment with high load).
Close #2409 
Basically, the patch's logic is to retrieve all the dns pods fulfilling the label selector returned by the dns chaos service. Once the pods list filled, we iterate over it and we apply/recover the given dnschaos.
CHANGELOG
Tests
steps:
Tried to increase/decrease `replicas` field in `dnsServer` helm value to check if dnschaos were applied/recovered correctly ✅.
> dnschaos: Make possible to have more than one dns chaos server

- .github/workflows/upload_image.yml
- CHANGELOG.md
Run build image ci on self-hosted arm machine
> ci: run build image on self-hosted arm machine

- CHANGELOG.md
- helm/chaos-mesh/Chart.yaml
- helm/chaos-mesh/values.yaml
- install.sh
Bump version to 2.2.1
Here is the draft of release note:
This release introduces one bug fix for Chaos Mesh.
- Bump chaos-tproxy to v0.5.1 [#3426](https://github.com/chaos-mesh/chaos-mesh/pull/3426)
- Run build image ci on self-hosted machine [#3429](https://github.com/chaos-mesh/chaos-mesh/pull/3429)
> bump version to 2.2.2

- CHANGELOG.md
- pkg/chaosdaemon/tc_server.go
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
Close #3458 
Add a judgement of `enterNS` in `getAllInterfaces()`
CHANGELOG
> Add a judgement of `enterNS` in `getAllInterfaces()`

- CHANGELOG.md
- pkg/config/dashboard/dashboard.go
- pkg/dashboard/collector/server.go
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
close #3475
- append `QPS` and `Burst` to `ChaosDashboardConfig`
- when initializing kubernetes client, respect these configurations.
CHANGELOG
Tests
Side effects
```shell
```
> chore: configure QPS and Burst for chaos dashboard

- CHANGELOG.md
- pkg/ctrl/server/schema.resolvers.go
Some methods in ctrl server are unimplemented, they may panic when you use chaosctl.
CHANGELOG
Tests
Side effects
```shell
```
> cherry-pick(3462): implement some missing methods in ctrl server

- CHANGELOG.md
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- install.sh
- pkg/config/dashboard/dashboard.go
- pkg/dashboard/apiserver/server.go
- pkg/dashboard/swaggerdocs/docs.go
- pkg/dashboard/swaggerdocs/swagger.json
- pkg/dashboard/swaggerdocs/swagger.yaml
Signed-off-by: brnck <a.berneckas@gmail.com>
Close #3456
CHANGELOG
Tests
* Deploy chaos-mesh
* `curl <domain>:<port>/debug/pprof/` - will return HTML with profiler endpoints
* Check chaos-dashboard logs - you will see that it registers endpoints
* set `enableProfiling` parameter to `false` and redeploy
* Check chaos-dashboard logs - you will see that it does not register endpoints
* `curl <domain>:<port>/debug/pprof/` - won't return HTML with profiler endpoints. WIll return homepage instead
Side effects
```shell
```
> Respect flag enableProfiling in chaos-dashboard

- .github/pull_request_template.md
- 
- append `release-2.3` into cherry-pick options in PR template
CHANGELOG
Tests
Side effects
```shell
```
> chore: append release-2.3 into cherrypick options

- CHANGELOG.md
- ui/app/src/components/FormField/AutocompleteField.tsx
close https://github.com/chaos-mesh/chaos-mesh/issues/3416
- use empty array `[]` instead of `null` from `getIn()`
CHANGELOG
Tests
Side effects
```shell
```
> chore: use empty array when no value provided

- CHANGELOG.md
- pkg/dashboard/apiserver/common/common.go
Signed-off-by: brnck <a.berneckas@gmail.com>
Close #3452 
This PR fixes endpoint `/api/common/chaos-available-namespaces` when **SecurityMode** and ** enableFilterNamespace** - both set to true.
CHANGELOG
Tests
Steps to test:
* Deploy chaos-mesh
* `curl <domain.tld>:<port>/api/common/chaos-available-namespaces` - will return all namespaces
* Set `enableFilterNamespace` to true and redeploy.
* `curl <domain.tld>:<port>/api/common/chaos-available-namespaces` - will return `[]`
* `kubectl annotate ns chaos-mesh chaos-mesh.org/inject=enabled`
* `curl <domain.tld>:<port>/api/common/chaos-available-namespaces` - will return `["chaos-mesh"]`
* Set `SecurityMode` to true and redeploy.
* `curl <domain.tld>:<port>/api/common/chaos-available-namespaces` …
> Protect chaos available namespace and filter namespaces if needed

- CHANGELOG.md
Some PRs in `CHANGELOG.md` need to move to unreleased.
CHANGELOG
Tests
Side effects
```shell
```
> fix: move recent prs to unreleased

- CHANGELOG.md
- ui/app/src/i18n/zh.json
Signed-off-by: zhengbingxian <zhengbingxian@archeros.com>
https://github.com/chaos-mesh/chaos-mesh/issues/3513
Add the Chinese name of blockchaos in ui/app/src/i18n/zh.json
CHANGELOG
Tests
Side effects
```shell
```
> fix BlockChaos can't show Chinese name

- CHANGELOG.md
- ui/app/src/components/NewExperimentNext/Step2.tsx
- ui/app/src/components/NewExperimentNext/data/types.ts
- ui/app/src/components/NewExperimentNext/form/Kernel.tsx
- ui/app/src/components/NewExperimentNext/form/Stress.tsx
- ui/app/src/i18n/en.json
- ui/app/src/i18n/zh.json
Close #3507.
CHANGELOG
Tests
Side effects
```shell
```
> fix(ui): IOChaos `containerNames` field

- CHANGELOG.md
- pkg/ptrace/ptrace_linux.go
Signed-off-by: 0xff-dev <stevenshuang521@gmail.com>
Deprecated: As of Go 1.16, os.ReadDir is a more efficient and correct choice.
`chaos-mesh` is currently using go 1.18.
CHANGELOG
Tests
Side effects
```shell
```
> replace io/ioutil package with os package

- CHANGELOG.md
- api/v1alpha1/common_types.go
- api/v1alpha1/dnschaos_type.go
- api/v1alpha1/networkchaos_types.go
- api/v1alpha1/physical_machine_chaos_types.go
- api/v1alpha1/podchaos_types.go
- api/v1alpha1/podnetworkchaos_types.go
- api/v1alpha1/schedule_types.go
- api/v1alpha1/statuscheck_types.go
- api/v1alpha1/stresschaos_types.go
- api/v1alpha1/timechaos_types.go
- api/v1alpha1/workflownode_types.go
close #3526 
Add missing `omitempty` JSON tag to optional fields.
CHANGELOG
Tests
Side effects
```shell
```
> fix: Omit optional fields explicitly

- CHANGELOG.md
- e2e-test/e2e/chaos/sidecar/injection_config.go
- e2e-test/e2e/chaos/sidecar/template_config.go
Signed-off-by: zhengbingxian <zhengbingxian@archeros.com>
https://github.com/chaos-mesh/chaos-mesh/issues/3563
Add judgment to check newPod.items' length,  so that it will not cause "runtime error: index out of range [0] with length 0"
CHANGELOG
Tests
Side effects
```shell
```
> fix "sidecar config" e2e test cases run failed in some scenario

- CHANGELOG.md
- pkg/dashboard/apiserver/auth/gcp/middleware.go
- pkg/dashboard/apiserver/auth/gcp/service.go
Close #2873 
Moving package level variable log into struct Service as a field
CHANGELOG
Tests
Side effects
> Refine logging in pkg/dashboard/apiserver/auth/gcp

- .github/workflows/integration_test.yml
- CHANGELOG.md
fix https://github.com/chaos-mesh/chaos-mesh/issues/3587
- update the kubectl version when setting up kubernetes
CHANGELOG
Tests
Side effects
```shell
```
> ci: fix integration test, update kuebctl version

- CHANGELOG.md
- pkg/apiserver/experiment/experiment.go
- pkg/apiserver/schedule/schedule.go
- pkg/core/experiment.go
- ui/src/components/FormField/LabelField.tsx
- ui/src/components/NewExperiment/types.ts
- ui/src/components/NewExperimentNext/data/target.ts
- ui/src/components/NewExperimentNext/form/Kernel.tsx
- ui/src/components/NewExperimentNext/form/Stress.tsx
- ui/src/i18n/en.json
Same as #3533, but for the `v2.0` branch.
CHANGELOG
Tests
Side effects
```shell
```
> fix: uniformly use Enter to add item in LabelField

- .github/workflows/license_checker.yml
Signed-off-by: andrewmatilde <davis6813585853062@outlook.com>
license checker:lastest failed to load .gitignore now. So I rollback it to v0.4.0.
CHANGELOG
Tests
Side effects
```shell
```
> Rollback license checker version

- .github/workflows/checklink_config.json
close https://github.com/chaos-mesh/chaos-mesh/issues/3615
append more domain into ignore patterns
CHANGELOG
Tests
Side effects
```shell
```
> ci: add more ignore domain for check markdown link

- CHANGELOG.md
- ui/app/src/components/Scope/index.tsx
An enhancement for #3621.
Use a parent component (wrapper) to control whether to render the real form in Scope to avoid unnecessary overhead.
CHANGELOG
Tests
Side effects
```shell
```
> perf: make the Scope render conditionally

- CHANGELOG.md
- pkg/dashboard/apiserver/common/common.go
- test/integration_test/dashboard_authority/cluster-manager.yaml
- test/integration_test/dashboard_authority/cluster-viewer.yaml
- ui/app/src/components/Scope/index.tsx
This PR introduces a change to the rbac.yaml file that is shown to user when generating a new token for using chaosmesh dashboard.
Existing yaml is incorrect for apiGroup chaos-mesh.org and does not add the required verbs/resources in rule section.
This results in errors on dashboard "cannot list resource PodChaos" etc.for all types of resources
After fix, the rule is created correctly: `{APIGroups:["[chaos-mesh.org](http://chaos-mesh.org/)"], Resources:["*"], Verbs:["get" "list" "watch" "create" "delete" "patch" "update"]}`
The fix is aligned with https://kubernetes.io/docs/reference/access-authn-authz/rbac/
```Allow reading Pods in the core API group, as well as reading or writing Job resources in the "batch" API group:
rules:
- apiGroups: [""]
#
resources: ["pods"]
verbs: ["get", …
```
> *: Fix dashboard's token generation RBAC YAML

- CHANGELOG.md
- controllers/utils/recorder/recorder.go
refs: https://github.com/chaos-mesh/chaos-mesh/issues/2752
- use existed `logger` for `klog`
CHANGELOG
Tests
Side effects
```shell
```
> refactor: remove the usage of klog in event recorder

- CHANGELOG.md
- ui/app/src/components/NewExperimentNext/data/types.ts
This PR removes the limit action, and run codegen, though I don't know whether these codegen behaves well.
> dashboard: remove limit action from BlockChaos and generate specs

- CHANGELOG.md
- helm/chaos-mesh/values.yaml
Ready for release 2.4.0.
- Update image tag in helm charts
- update CHANGELOG 
CHANGELOG
Tests
Side effects
```shell
```
> chore: update image tag to 2.4.0, update CHANGELOG

- .github/workflows/maually-sign-container-images.yaml
- CHANGELOG.md
relates to https://github.com/chaos-mesh/chaos-mesh/issues/3696
- GitHub Action Workflow to create signed container images
CHANGELOG
Tests
Side effects
```shell
```
> ci(signed release): new github workflow to sign existed images manually

- .github/workflows/maually-sign-container-images.yaml
fix permission issue about https://github.com/chaos-mesh/chaos-mesh/pull/3708
- append `contents: read` for permission
CHANGELOG
Tests
Side effects
```shell
```
> fix(try): permissions of sign images

- .github/workflows/checklink.yaml
- .github/workflows/codecov_unittest.yaml
- .github/workflows/integration_test.yml
- .github/workflows/upload_env_image.yml
- .github/workflows/upload_image.yml
- .github/workflows/upload_image_pr.yml
- .github/workflows/upload_latest_files.yml
- .github/workflows/upload_release_files.yml
Using the master version maybe cause potential problems in the future, so I pin all the master versions to `v3`. The existing `v2` versions have not changed.
CHANGELOG
Tests
Side effects
```shell
```
> fix: replace actions/checkout from master to v3

- .github/.licenserc.yaml
keep consistent style in `.licenserc.yaml` with https://github.com/chaos-mesh/chaos-mesh/pull/3756
CHANGELOG
Tests
Side effects
```shell
```
> chore: update .licenseyc.yaml for consistent style

- .github/.licenserc.yaml
close https://github.com/chaos-mesh/chaos-mesh/issues/3755
CHANGELOG
Tests
Side effects
```shell
```
> chore: fix license-eye

- MAINTAINERS.md
Signed-off-by: Ben Ye <benye@amazon.com>
I have been inactive on the project for 2 years since I left PingCAP. I have other things to focus now and it is hard for me to focus back to the project.
Since we have more and more active maintainers now I feel it is better to move myself to emeritus maintainer state.
CHANGELOG
Tests
Side effects
```shell
```
> Remove yeya24 as current maintainer

- CHANGELOG.md
- ui/app/src/components/AutoForm/data.ts
- ui/app/src/components/AutoForm/index.tsx
- ui/app/src/lib/localStorage.ts
Close #3747
This PR enables mode when creating PhysicalMachineChaos with addresses.
This PR also fixes little problems in `localStorage.ts`.
CHANGELOG
Tests
Side effects
```shell
```
> fix: enable mode when creating PhysicalMachineChaos with addresses

- .github/workflows/checklink.yaml
- .github/workflows/ci.yml
- .github/workflows/ci_skip.yml
- .github/workflows/codecov_unittest.yaml
- .github/workflows/e2e_test.yml
- .github/workflows/e2e_test_upload_cache.yml
- .github/workflows/integration_test.yml
- .github/workflows/license_checker.yml
- .github/workflows/must_update_changelog.yml
- .github/workflows/release_helm_chart.yml
- .github/workflows/stale.yml
- .github/workflows/upload_env_image.yml
- .github/workflows/upload_image.yml
- .github/workflows/upload_image_pr.yml
- .github/workflows/upload_latest_files.yml
- .github/workflows/upload_release_files.yml
- CHANGELOG.md
Signed-off-by: Ningxuan Wang <wanxfinger@gmail.com>
Since Github action has migrated ubuntu-latest from 20.04 to 22.04, our minikube install action which requires ubuntu version to be 18 or 20 will not work. And I think other actions also should use a certain version rather than latest.
Change the version of ubuntu
CHANGELOG
Tests
Side effects
```shell
```
> Change ubuntu version from latest to 20.04

- CHANGELOG.md
- api/v1alpha1/schedule_webhook.go
Signed-off-by: Ningxuan Wang <wanxfinger@gmail.com>
These comments lack  the argument `admisstionReviewVersion`, resulting in error when api is imported in other project. And chaos mesh has explicit statement of webhooks in `helm/chaos-emsh/templates/`, so we should delete them.
Just delete these comments
CHANGELOG
Tests
Side effects
```shell
```
> Remove useless kubebuilder comment in webhook

- CHANGELOG.md
- helm/chaos-mesh/values.yaml
- install.sh
WEBHOOK_PORT is configured the port for chaos-controller-manager provides webhooks. In GKE private clusters, by default kubernetes apiservers are allowed to talk to the cluster nodes only on 443 and 10250. so configuring  WEBHOOK_PORT: 10250, will work out of the box without needing to add firewall rules or requiring NET_BIND_SERVICE capabilities to bind port numbers <1000 
https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules 
CHANGELOG
Tests
Side effects
```shell
git push …
```
> Helm: change default webhook port to 10250

- .github/checklink_config.json
- .github/workflows/e2e_test.yml
- .github/workflows/e2e_test_upload_cache.yml
- .github/workflows/integration_test.yml
- .github/workflows/upload_image.yml
- CHANGELOG.md
- README.md
For our current development speed, updating the latest image daily is unnecessary (not to mention that we can use the `workflow_dispatch` event to trigger it).
Update the schedule of releasing the latest image **from daily to weekly**.
CHANGELOG
Tests
Side effects
```shell
```
> chore: slow down the latest releases

- images/dev-env/Dockerfile
Resolve `dev-env` building failure after https://github.com/chaos-mesh/chaos-mesh/pull/3902.
- `github.com/onsi/ginkgo/ginkgo` -> `github.com/onsi/ginkgo/v2/ginkgo`
CHANGELOG
Tests
Side effects
```shell
```
> chore: bump ginkgo version in dev-env to v2

- CHANGELOG.md
- helm/chaos-mesh/values.yaml
CHANGELOG
Tests
Side effects
```shell
```
> update chaos-coredns version to v0.2.4

- CHANGELOG.md
- helm/chaos-mesh/values.yaml
@xlgao-zju @STRRL Reverts chaos-mesh/chaos-mesh#3947
This PR has not passed the e2e tests, and there has been a pioneer working on this problem in #3488.
> Revert "update chaos-coredns version to v0.2.4"

- .github/workflows/merge_conflict_finder.yaml
Make the score of https://clomonitor.io/projects/cncf/chaos-mesh return to 100.
CHANGELOG
Tests
Side effects
```shell
```
> fix: supplement read-only token

- examples/etcd/etcd.yaml
Kubernetes is migrating its image registry from [[k8s.gcr.io](http://k8s.gcr.io/)](http://k8s.gcr.io/) to [[registry.k8s.io](http://registry.k8s.io/)](http://registry.k8s.io/).
Part of kubernetes/k8s.io#4780.
CHANGELOG
Tests
Side effects
```shell
```
> fix: migrate from k8s.gcr.io to registry.k8s.io

- CHANGELOG.md
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
- install.sh
Close #3876
I have changed the dashboards `updateStrategy`. The PersistentVolumeClaim for the dashboard is created with the accessMode `ReadWriteOnce`, which does not allow the dashboard to do a rolling restart because the blue version of the dashboard won't be shutdown until the green version is up and running.
This lead to problems when doing a `kubectl rollout-restart deployment chaos-dashboard` because the new dashboard Pod could not mount the PVC.
CHANGELOG
Tests
steps:
- Install the ChaosMesh + dashboard using a `helm install` command
- configure the dashboard to be enabled and use a PersistentVolumeClaim of arbitrary size
- Change the update strategy as mentioned in this PR
- Watch the dashboard rollout-restart instead of being stuck …
> Dashboard rwo pvc restart

- CHANGELOG.md
- images/build-env/Dockerfile
Upgrade go version to v1.19.7 to fix CVE-2022-41723, refer to:  https://github.com/golang/go/issues/58355 https://github.com/golang/go/commit/5c3e11bd0b5c0a86e5beffcd4339b86a902b21c3
CHANGELOG
Tests
Side effects
```shell
```
> upgrade go version to 1.19.7 to fix CVE-2022-41723

- .github/workflows/integration_test.yml
- .github/workflows/upload_image.yml
- .github/workflows/upload_latest_files.yml
- .github/workflows/upload_release_files.yml
- CHANGELOG.md
This pr is a part of https://github.com/chaos-mesh/chaos-mesh/pull/3978. In this pr, we upgrade go version in CI environment. 
CHANGELOG
Tests
Side effects
```shell
```
> upgrade go version to v1.19.7 in CI environment

- .github/workflows/e2e_test.yml
- .github/workflows/integration_test.yml
Remove warnings when running the `helm` command in CI:
> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/runner/.kube/config
> WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/runner/.kube/config
A screenshot:
CHANGELOG
Tests
Side effects
```shell
```
> fix(ci): restrict access to kubeconfig

- CHANGELOG.md
- helm/chaos-mesh/templates/dns-configmap.yaml
- helm/chaos-mesh/templates/dns-deployment.yaml
- helm/chaos-mesh/templates/dns-service.yaml
- install.sh
Fixes `Listen: listen tcp :53: bind: permission denied` in chaos-dns-server pod deployed on OpenShift 4.11.
Changed CoreDNS listen port from 53 to 5353 to obtain Chaos DNS Server compability with OpenShift.
Files:
- dns-service.yaml
- dns-deployment.yaml
- dns-configmap.yaml
CHANGELOG
Tests
steps:
Manual deployment on OpenShift 4.11.
Side effects
```shell
```
> Changed CoreDNS listen port from 53 to 5353

- .github/workflows/e2e_test.yml
- CHANGELOG.md
CHANGELOG
Tests
Side effects
```shell
```
> ci: use kubectl cluster-info dump to enhance e2e profiling

- .github/workflows/ci.yml
- images/build-env/Dockerfile
- ui/pnpm-lock.yaml
This PR fixes the recently failed builds, the reason is the latest pnpm has already been up to `v8` and we need to re-generate the lockfile.
CHANGELOG
Tests
Side effects
```shell
```
> fix: upgrade pnpm to v8

- .github/pull_request_template.md
- CHANGELOG.md
Some templates are outdated.
Update the changelog and the pr template to fit `v2.6`.
```shell
```
> chore: update templates to fit v2.6

- CHANGELOG.md
- helm/chaos-mesh/templates/controller-manager-deployment.yaml
Close #4078
Update `helm/chaos-mesh/templates/controller-manager-deployment.yaml` to control `replicas`.
```shell
```
> fix: set `replicas: 1` automatically when HA is not enabled

- CHANGELOG.md
- pkg/dashboard/store/experiment/experiment.go
- pkg/dashboard/store/schedule/schedule.go
- pkg/dashboard/store/workflow/workflow.go
Fix #4099 
* Set finish_time when to mark it archived.  In workflow definition, end_time represents the time when the workflow completed all steps and finish time represents the time when the workflow was deleted from Kubernetes. So we should set finish_time when to mark it archived instead of end_time. 
* Add nill check on `DeleteByFinishTime" function. 
```shell
```
> fix dashboard panic when exec delete action by finish_time

- .github/checklink_config.json
- .github/workflows/checklink.yaml
Ref: https://github.com/chaos-mesh/website/pull/394.
> Over time, some of the links in our blogs (mostly blogs, but also documents) have broken (another reason is some domains are blocked by GitHub, like Twitter). This causes some contributors to open a PR every time and find this check failed, and then they get stuck in a dead-end loop of fixing the CI.
> So I update the action to check only the modified files by setting `check-modified-files-only` to `yes`. This avoids checking all the legacy files.
If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most …
> chore: check links only in modified files

- CHANGELOG.md
- ui/app/src/components/FormField/TextField.test.tsx
- ui/app/src/components/FormField/TextField.tsx
- ui/app/src/components/NewExperimentNext/form/TargetGenerated.tsx
Currently when entering numeric fields like `Port` into new Experiments, scrolling can change the number in the input box, while the intent is typically to move down the page.
This change adds an onWheel handler to all `InputField` components with type `number`. The handler simply calls `.blur()` on the input element to prevent the value changing.
For instance, this will apply to:
- Port in numerous experiment types
- Workers in Stress Experiment 
- Probability and "max times of failures" in Kernel Experiment
- historyLimit and startingDeadlineSeconds in Schedule
- Node number in New Workflow
(Manually tested in Chrome 114.0.5735.198)
If you find …
> Prevent scroll from changing experiment number fields

- CHANGELOG.md
- pkg/dashboard/core/event.go
- pkg/dashboard/core/experiment.go
- pkg/dashboard/core/schedule.go
The DB of chaos dashboard restricts the length of these three fields to normal varchar. This can easily lead to storage failure due to data being too long, logs show:
```text
2023-08-09T07:59:54.584Z	ERROR	collector.NetworkChaos	collector/collector.go:114	failed to update experiment	{"archive": {"ID":16,"CreatedAt":"2023-08-05T11:15:45Z","UpdatedAt":"2023-08-09T07:59:54.583499664Z","DeletedAt":null,"uid":"d97a7ec5-8b9d-4acf-8ee4-a997b42648fb","kind":"NetworkChaos","name":"net-loss-100","namespace":"default","action":"loss","start_time":"2023-08-05T11:15:44Z","finish_time":null,"archived":false,"Experiment":"{\"kind\":\"NetworkChaos\",\"apiVersion\":\"chaos-mesh.org/v1alpha1\",\"metadata\":{\"name\":\"net-loss-100\",\"namespace\":\"default\",\"uid\":\"d97a7ec5-8b9d-4acf-8ee4-a997b42648fb\", …
```
> Set the database column type to text for 'Workflow/Experiment/Schedule'

- CHANGELOG.md
- helm/chaos-mesh/values.yaml
Get ready for version 2.6.2.
This updated version alters the routing mechanism of the dashboard to ensure compatibility with deployment on any subpath, typically with an ingress.
> chore: ready for v2.6.2

- CHANGELOG.md
- cmd/chaos-controller-manager/provider/controller.go
- cmd/chaos-controller-manager/provider/updated_client.go
- go.mod
- go.sum
- pkg/clientpool/client.go
`github.com/hashicorp/golang-lru` has been updated some time ago to v2 with support for generics and thereby increased type safety.
Update dependency and code using it
```shell
```
> Update lru to v2

- .github/workflows/e2e_test.yml
- .github/workflows/integration_test.yml
- .github/workflows/upload_image_pr.yml
> chore: upgrade actions/upload-artifact to v3

- Makefile
Instead of calling controller-gen again, copy the generated crds into the chart.
```shell
```
> chore: do not call controller-gen repeatedly

- .github/workflows/ci.yml
- .github/workflows/codecov_unittest.yaml
- CHANGELOG.md
Currently, we run two unit tests (`make test`) when we open a PR.
Let `codecov_unittest.yaml` only run on `push` and append code coverage action in `ci.yml`.
```shell
```
> ci: remove the duplicate `make test`

- CHANGELOG.md
- images/chaos-daemon/Dockerfile
Remove `-k` flag to `curl` that was introduced previously. This flag disables all TLS verification and could allow for downloading the components from an untrusted source during the build.
This removes a source of potential insecurity during the build of chaos-daemon.
```shell
```
> build: don't use disable TLS verification in build

- controllers/test/types.go
> fix: remove the duplicate pkg import

- CHANGELOG.md
- pkg/chaosdaemon/dns_server.go
- pkg/chaosdaemon/dns_server_test.go
Ensures that the IP address set as the `nameserver` in `/etc/resolv.conf` is a valid IP address.
The `chaos-daemon` gRPC endpoint `SetDNSServer` now validates that `req.DNSServer` before using that value.
```shell
```
> fix: validate DNS server IP in SetDNSServer

- Makefile
- hack/env-image-tag.sh
In https://github.com/chaos-mesh/chaos-mesh/actions/runs/6851229373/job/18627073546?pr=4246, I found that the `make test` will report `./hack/env-image-tag.sh: line 38: docker: command not found` errors.
After investigating the Makefile, the `test` target will recursively call `make failpoint-*` targets, which will call `docker` in the container, this is the reason for errors.
So I created a recipe to encapsulate the `failpoint-ctl` command, although we've done a refactoring before to avoid macros, I don't think this recipe is too complicated, so it's not a big problem.
```makefile
define failpoint-ctl
find $(ROOT)/* -type d | grep -vE "(\.git|bin|\.cache|ui)" | xargs failpoint-ctl $1
endef
```
> Must include at least …
> fix(test): docker command not found

- CHANGELOG.md
- helm/chaos-mesh/templates/dns-deployment.yaml
- helm/chaos-mesh/values.yaml
- install.sh
The current chaos-dns-server affinity is not applicable because the `k8s-app: chaos-dns` label is not created on chaos-dns-server pods. This PR allows that affinity to be defined by the end user.
Close #4259 
chaos-dns-server affinity is defined using the `dnsServer.affinity` key value from the helm chart values file.
```shell
```
> Allow chaos-dns-server affinity to be set in helm values

- CHANGELOG.md
- helm/chaos-mesh/templates/dns-configmap.yaml
- install.sh
> fix: enable prometheus directive within coredns (#4321)

- .github/workflows/e2e_test.yml
- .github/workflows/integration_test.yml
- .github/workflows/upload_image_pr.yml
> chore: upgrade upload/download-artifact to v4

- .github/workflows/e2e_test.yml
> chore(e2e): upgrade minikube

- CHANGELOG.md
- pkg/config/dashboard.go
The environment variable TTL_EXPERIMENT is incorrectly used for ScheduleTTL and WorkflowTTL.
Since the default values are accidentally the same, the unit test cannot catch this error.
reference:
https://github.com/chaos-mesh/chaos-mesh/blob/5a08714d88380d38b6f9b968253cbbbf839c2f9d/helm/chaos-mesh/values.yaml#L366
Change the ScheduleTTL source environment variable to TTL_SCHEDULE and the WorkflowTTL source environment variable to TTL_WORKFLOW.
```shell
git …
```
> fix: TTL configuration from wrong environment variables at dashboard.go

- CHANGELOG.md
- pkg/config/dashboard.go
> fix: TTL configuration from wrong environment variables (#4338)

- build/build_image.py
- build/get_env_shell.py
- build/utils.py
If I want to make a cross-build on Darwin (macOS M1), I can't build an amd64 image because the `--platform` only passes an arch param (`amd64`) but does not specify os. Since the `build-env` image based on `alpine:3.17` does not exist as `darwin/amd64`, I think we should force mark the `linux` prefix before the `--platform` param?
Add a `linux` prefix in `--platform`, like `f"linux/{os.getenv('TARGET_PLATFORM')}"`.
```shell
```
> fix: cross build on darwin

- CHANGELOG.md
- helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
Allows templating of dashboard `rootUrl`. In environment with multiple clusters and chaos mesh deployed in each of them, this will enable easier templating via ArgoCD without adding in specific functionality for chaos-mesh.
This is similar to https://github.com/kedacore/charts/pull/617
```shell
```
> feat(helm): allow templating of dashboard rootUrl

- pkg/chaosdaemon/util/util.go
Fix comments in `pkg/chaosdaemon/util.GetChildProcesses`.
```shell
```
> fix: comments in pkg/chaosdaemon/util.GetChildProcesses

- CHANGELOG.md
- pkg/helm/chart.go
A small optimization to solve a TODO.
Learning the logic of helm downloads, I found a TODO here that requires setting the context for the request.
```shell
```
> chore: add context to the http request to download the chart

- pkg/ctrl/server/exec.go
Fix unused code and clean method in `pkg/ctrl/server/exec.go`
```shell
```
> fix: deprecated Stream method in `pkg/ctrl/server/exec.go`

- .github/workflows/e2e_test.yml
- CHANGELOG.md
- e2e-test/e2e/chaos/stresschaos/misc.go
- images/build-env/Dockerfile
- images/chaos-daemon/Dockerfile
- images/dev-env/Dockerfile
The motivation for this PR comes from #4384.
Upgrade debian buster to bookwarm. I suppose that we can upgrade to the latest stable version.
```shell
```
> chore: upgrade the base image of dev/build-env

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- build/get_env_shell.py
- helm/chaos-mesh/values.schema.json
- helm/chaos-mesh/values.yaml
- images/dev-env/Dockerfile
Close #4310
Install `helm-values-schema-json` in the `dev-env` image and add a target named `helm-values-schema` in the Makefile.
```shell
```
> chore: integrate helm-values-schema-json to generate schema for values.yaml

- pkg/portforward/portforward.go
fix: context cancel leak in portforward.
> fix: context cancel leak in portforward

- .github/workflows/release_helm_chart.yml
Refactor the workflow of release Helm chart with `GITHUB_REF_NAME`. Also, this PR deprecates the old `CR_TOKEN`.
```shell
```
> refactor(ci): release helm chart

- .github/workflows/codecov_unittest.yaml
- codecov.yml
Recently, the codecov workflows always failed. After investigating, I found that we need to set `CODECOV_TOKEN` due to workflows reported:
Please upload with the Codecov repository upload token to resolve issue.
```shell
```
> fix: upgrade codecov

- .github/workflows/codecov_unittest.yaml
- .github/workflows/release_helm_chart.yml
> fix: add runs-on

- .github/workflows/integration_test.yml
- pkg/ctrl/server/generated/generated.go
- pkg/ctrl/server/schema.graphqls
- test/integration_test/chaosctl/debug.sh
> fix(integration test): upgrade localstack

- CHANGELOG.md
- images/chaos-daemon/Dockerfile
It upgrades the `toda` component to version v0.2.4. It mainly introduces the issue needed by https://github.com/chaos-mesh/chaos-mesh/issues/3680.
close #3680
https://github.com/chaos-mesh/toda/pull/42. This PR fixes the incorrect `mmap` argument :+1: .
```shell
```
> chore: bump version to toda to v0.2.4

- CHANGELOG.md
- controllers/utils/chaosdaemon/chaosdaemon.go
- helm/chaos-mesh/templates/controller-manager-rbac.yaml
- install.sh
Close https://github.com/chaos-mesh/chaos-mesh/issues/4287
This PR fixes chaos controller can't find daemonIP over 1000 nodes using endpoints.
use endpointslice instead of endpoint 
```shell
```
> fix: chaos controller can't find daemonIP over 1000 nodes using endpoints

- .github/workflows/release_helm_chart.yml
> ci: fix release chart token

- .github/workflows/codecov_unittest.yaml
Add token to codecov action.
> [!TIP]
```shell
```
> fix: add codecov token to action

- .github/workflows/codecov_unittest.yaml
> [!IMPORTANT]
>
>
> [!TIP]
Cherry-pick #4513 to `release-2.6`.
If you find the DCO check fails, please run commands like below …
> [release-2.6] fix: add codecov token to action

- .github/pull_request_template.md
We released 2.7 several days ago, and by our support policy, we would cherry-pick new prs to 2.6 and 2.7 now.
> [!TIP]
> [!TIP]
```shell
```
> chore: update cherrypick options becase of 2.7 released

- CHANGELOG.md
As the title.
> [!TIP]
```shell
```
> chore: update changelog after v2.7

- .github/workflows/ci.yml
- .github/workflows/upload_image.yml
> [!IMPORTANT]
>
>
We're facing some trouble with selfhosted arm runner, and we're switching to github hosted arm runners.
> [!TIP]
> [!TIP]
> You can also refer to a proposal or design doc …
> ci: use github large runner instead of self-hosted runner

- .github/workflows/integration_test.yml
- images/dev-env/Dockerfile
> [!IMPORTANT]
>
>
There are some compatibility problems in CI on arm ubuntu 24.04,I am trying to fix it.
> [!TIP]
> [!TIP]
> …
> ci: use ebtables-legacy for test to adopte the new version of debian

- CHANGELOG.md
- ui/app/src/components/NewExperimentNext/Step3.tsx
- ui/app/src/components/NewWorkflowNext/utils/convert.ts
- ui/app/src/components/Scope/TargetsTable/index.tsx
- ui/app/src/lib/formikhelpers.ts
Close #4566
We haven't handled the parsing of physical machines correctly. In the frontend code, all physical machines are originally recorded with this format:
```
namespace:machine-name
```
So we need to parse them into the below format:
```yaml
namespace:
- machine1
- machine2
```
This PR fixes all the places where this problem occurs.
> [!TIP]
```shell
```
> fix: parse physical machines

- .github/workflows/integration_test.yml
Ref: #4564
We took much time on the integration test with the arm64 arch, and it's still not working properly 🥲.
In the latest bi-weekly meeting, our maintainers/committers agreed we can temporarily disable the arm64 matrix in the `integration_test.yml` until we have enough energy to solve it deeply.
Disable the integration test on arm64.
> [!TIP]
```shell
```
> ci: remove arm64 in integration_test

- .github/dependabot.yml
- .github/workflows/e2e_test.yml
- .github/workflows/e2e_test_upload_cache.yml
- .github/workflows/integration_test.yml
We can use the negative pattern for `paths` and `paths-ignore` in CI.
> [!TIP]
```shell
```
> ci: use the negative pattern

- Makefile
- images/dev-env/Dockerfile
As https://pkg.go.dev/golang.org/x/tools/cmd/goimports says:
> In addition to fixing imports, goimports also formats your code in the same style as gofmt so it can be used as a replacement for your editor's gofmt-on-save hook.
Remove the extra format operation.
> [!TIP]
```shell
```
> refactor: fmt = goimports

- .github/workflows/upload_env_image.yml
- .github/workflows/upload_image.yml
Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Update related commands.
> [!TIP]
```shell
```
> chore: deprecate set-output

- .github/workflows/e2e_test.yml
- CHANGELOG.md
Upgrade k8s versions to recent releases in e2e tests.
> [!TIP]
```shell
```
> chore(e2e): upgrade k8s versions

- pkg/workflow/controllers/parallel_node_reconciler.go
- pkg/workflow/controllers/serial_node_reconciler.go
> [!IMPORTANT]
>
>
should use `updateErr`
> [!TIP]
> one, you can use `git rebase -i HEAD~n` to re-signoff …
> fix: use the correct error variable

- Makefile
In the original Makefile, `RUN_IN_DEV_SHELL` and `RUN_IN_BUILD_SHELL` were defined using = (recursively expanded variables). This notation defers evaluation until the variable is actually used, which can be helpful if the values need to reflect changes in other variables over time. However, for the variables updated in this PR, we do not require lazy (deferred) evaluation. 
Therefore, switching to := (simply expanded variables) is more appropriate, as each variable is expanded once at the time of definition and remains consistent throughout the build. This can improve performance and clarity by avoiding unnecessary re-evaluation.
This change prevents many repeated computations from being executed multiple times—a behavior that can be observed by setting SHELL := bash -x.
> This PR should …
> fix reduce useless recursively expanded variables in Makefile

- CHANGELOG.md
- ui/app/src/components/NewExperimentNext/Step3.tsx
- ui/app/src/components/ObjectConfiguration/index.tsx
- ui/app/src/i18n/en.json
- ui/app/src/i18n/zh.json
- ui/app/src/lib/formikhelpers.ts
Close #4461
Some types of chaos don't have `selectors`, like `AWSChaos`, `AzureChaos`, `GCPChaos`, so we need to process them separately.
> [!TIP]
```shell
```
> fix(ui): process no selector chaos

- CHANGELOG.md
- helm/chaos-mesh/values.yaml
This patch version mainly resolves [CVEs](https://github.com/chaos-mesh/chaos-mesh/issues/4669) by upgrading base images.
> chore: ready for v2.7.2

- .github/workflows/ci.yml
- .github/workflows/ci_skip.yml
- .github/workflows/must_update_changelog.yml
- .github/workflows/upload_env_image.yml
- .github/workflows/upload_image.yml
- .github/workflows/upload_latest_files.yml
- .github/workflows/upload_release_files.yml
- CHANGELOG.md
- helm/chaos-mesh/values.yaml
This patch version mainly resolves [CVEs](https://github.com/chaos-mesh/chaos-mesh/issues/4669) by upgrading base images.
And, if there are no serious CVEs to follow in the future, this will be the last version of `v2.6`.
> chore: ready for v2.6.7

- .github/workflows/upload_image_pr.yml
- images/chaos-daemon/Dockerfile
- images/chaos-dashboard/Dockerfile
- images/chaos-kernel/Dockerfile
In [#4676](https://github.com/chaos-mesh/chaos-mesh/pull/4676), I forgot to update `bullseye-security` and `bullseye-proposed-updates` to `bookworm-security` and `bookworm-proposed-updates`.
> [!TIP]
```shell
```
> fix: bullseye to bookworm

- ui/app/package.json
- ui/app/src/components/NewExperimentNext/ByYAML/index.tsx
- ui/app/src/components/NewWorkflow/index.tsx
- ui/app/src/components/NewWorkflowNext/SubmitWorkflow.tsx
- ui/app/src/components/TopContainer/index.tsx
- ui/app/src/pages/Archives/Single.tsx
- ui/app/src/pages/Dashboard/Predefined.tsx
- ui/app/src/pages/Experiments/Single.tsx
- ui/app/src/pages/Schedules/Single.tsx
- ui/app/src/pages/Workflows/Single.tsx
- ui/pnpm-lock.yaml
Ref: #4688
Replace `@loadable/component` with `React.lazy`.
> [!TIP]
```shell
```
> fix: deprecate @loadable/component

- ui/app/package.json
- ui/app/src/components/NewExperimentNext/ByYAML/index.tsx
- ui/app/src/components/NewWorkflow/index.tsx
- ui/app/src/components/YAMLEditor/index.tsx
- ui/app/src/pages/Dashboard/Predefined.tsx
- ui/pnpm-lock.yaml
Ref: #4688
Remove `ace-builds/webpack-resolver`.
> [!TIP]
```shell
```
> fix: update ace-builds

- CHANGELOG.md
- ui/app/src/components/NewExperimentNext/ByYAML/index.tsx
- ui/app/src/components/NewExperimentNext/Step1.tsx
- ui/app/src/components/NewExperimentNext/Step2.tsx
- ui/app/src/components/NewExperimentNext/Step3.tsx
- ui/app/src/components/NewExperimentNext/index.tsx
- ui/app/src/components/NewWorkflowNext/SubmitWorkflow.tsx
- ui/app/src/components/YAMLEditor/index.tsx
- ui/app/src/lib/formikhelpers.ts
Close #4703
Parsing `env` before transforming the original kind to the UI-specific kind.
> [!TIP]
```shell
```
> fix(ui): set the correct env

- .github/workflows/checklink.yaml
- .github/workflows/upload_image.yml
- CHANGELOG.md
CI: cosign versions below v2.0.0 are no longer supported.
> [!TIP]
```shell
```
> fix: upgrade cosign to v2
